// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/JoinLobbyResponse.proto

package POGOProtos.Networking.Responses;

/**
 * Protobuf type {@code POGOProtos.Networking.Responses.JoinLobbyResponse}
 */
public  final class JoinLobbyResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:POGOProtos.Networking.Responses.JoinLobbyResponse)
    JoinLobbyResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JoinLobbyResponse.newBuilder() to construct.
  private JoinLobbyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JoinLobbyResponse() {
    result_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JoinLobbyResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JoinLobbyResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            result_ = rawValue;
            break;
          }
          case 18: {
            POGOProtos.Data.Raid.Lobby.Builder subBuilder = null;
            if (lobby_ != null) {
              subBuilder = lobby_.toBuilder();
            }
            lobby_ = input.readMessage(POGOProtos.Data.Raid.Lobby.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lobby_);
              lobby_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return POGOProtos.Networking.Responses.JoinLobbyResponseOuterClass.internal_static_POGOProtos_Networking_Responses_JoinLobbyResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return POGOProtos.Networking.Responses.JoinLobbyResponseOuterClass.internal_static_POGOProtos_Networking_Responses_JoinLobbyResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            POGOProtos.Networking.Responses.JoinLobbyResponse.class, POGOProtos.Networking.Responses.JoinLobbyResponse.Builder.class);
  }

  /**
   * Protobuf enum {@code POGOProtos.Networking.Responses.JoinLobbyResponse.Result}
   */
  public enum Result
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNSET = 0;</code>
     */
    UNSET(0),
    /**
     * <code>SUCCESS = 1;</code>
     */
    SUCCESS(1),
    /**
     * <code>ERROR_NOT_IN_RANGE = 2;</code>
     */
    ERROR_NOT_IN_RANGE(2),
    /**
     * <code>ERROR_RAID_UNAVAILABLE = 3;</code>
     */
    ERROR_RAID_UNAVAILABLE(3),
    /**
     * <code>ERROR_RAID_COMPLETED = 4;</code>
     */
    ERROR_RAID_COMPLETED(4),
    /**
     * <code>ERROR_NO_AVAILABLE_LOBBIES = 5;</code>
     */
    ERROR_NO_AVAILABLE_LOBBIES(5),
    /**
     * <code>ERROR_PLAYER_BELOW_MINIMUM_LEVEL = 6;</code>
     */
    ERROR_PLAYER_BELOW_MINIMUM_LEVEL(6),
    /**
     * <code>ERROR_POI_INACCESSIBLE = 7;</code>
     */
    ERROR_POI_INACCESSIBLE(7),
    /**
     * <code>ERROR_GYM_LOCKOUT = 8;</code>
     */
    ERROR_GYM_LOCKOUT(8),
    /**
     * <code>ERROR_NO_TICKET = 9;</code>
     */
    ERROR_NO_TICKET(9),
    /**
     * <code>ERROR_NO_REMOTE_TICKET = 10;</code>
     */
    ERROR_NO_REMOTE_TICKET(10),
    /**
     * <code>ERROR_NO_INVITE = 11;</code>
     */
    ERROR_NO_INVITE(11),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNSET = 0;</code>
     */
    public static final int UNSET_VALUE = 0;
    /**
     * <code>SUCCESS = 1;</code>
     */
    public static final int SUCCESS_VALUE = 1;
    /**
     * <code>ERROR_NOT_IN_RANGE = 2;</code>
     */
    public static final int ERROR_NOT_IN_RANGE_VALUE = 2;
    /**
     * <code>ERROR_RAID_UNAVAILABLE = 3;</code>
     */
    public static final int ERROR_RAID_UNAVAILABLE_VALUE = 3;
    /**
     * <code>ERROR_RAID_COMPLETED = 4;</code>
     */
    public static final int ERROR_RAID_COMPLETED_VALUE = 4;
    /**
     * <code>ERROR_NO_AVAILABLE_LOBBIES = 5;</code>
     */
    public static final int ERROR_NO_AVAILABLE_LOBBIES_VALUE = 5;
    /**
     * <code>ERROR_PLAYER_BELOW_MINIMUM_LEVEL = 6;</code>
     */
    public static final int ERROR_PLAYER_BELOW_MINIMUM_LEVEL_VALUE = 6;
    /**
     * <code>ERROR_POI_INACCESSIBLE = 7;</code>
     */
    public static final int ERROR_POI_INACCESSIBLE_VALUE = 7;
    /**
     * <code>ERROR_GYM_LOCKOUT = 8;</code>
     */
    public static final int ERROR_GYM_LOCKOUT_VALUE = 8;
    /**
     * <code>ERROR_NO_TICKET = 9;</code>
     */
    public static final int ERROR_NO_TICKET_VALUE = 9;
    /**
     * <code>ERROR_NO_REMOTE_TICKET = 10;</code>
     */
    public static final int ERROR_NO_REMOTE_TICKET_VALUE = 10;
    /**
     * <code>ERROR_NO_INVITE = 11;</code>
     */
    public static final int ERROR_NO_INVITE_VALUE = 11;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Result valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Result forNumber(int value) {
      switch (value) {
        case 0: return UNSET;
        case 1: return SUCCESS;
        case 2: return ERROR_NOT_IN_RANGE;
        case 3: return ERROR_RAID_UNAVAILABLE;
        case 4: return ERROR_RAID_COMPLETED;
        case 5: return ERROR_NO_AVAILABLE_LOBBIES;
        case 6: return ERROR_PLAYER_BELOW_MINIMUM_LEVEL;
        case 7: return ERROR_POI_INACCESSIBLE;
        case 8: return ERROR_GYM_LOCKOUT;
        case 9: return ERROR_NO_TICKET;
        case 10: return ERROR_NO_REMOTE_TICKET;
        case 11: return ERROR_NO_INVITE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Result>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Result> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Result>() {
            public Result findValueByNumber(int number) {
              return Result.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return POGOProtos.Networking.Responses.JoinLobbyResponse.getDescriptor().getEnumTypes().get(0);
    }

    private static final Result[] VALUES = values();

    public static Result valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Result(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:POGOProtos.Networking.Responses.JoinLobbyResponse.Result)
  }

  public static final int RESULT_FIELD_NUMBER = 1;
  private int result_;
  /**
   * <code>.POGOProtos.Networking.Responses.JoinLobbyResponse.Result result = 1;</code>
   * @return The enum numeric value on the wire for result.
   */
  public int getResultValue() {
    return result_;
  }
  /**
   * <code>.POGOProtos.Networking.Responses.JoinLobbyResponse.Result result = 1;</code>
   * @return The result.
   */
  public POGOProtos.Networking.Responses.JoinLobbyResponse.Result getResult() {
    @SuppressWarnings("deprecation")
    POGOProtos.Networking.Responses.JoinLobbyResponse.Result result = POGOProtos.Networking.Responses.JoinLobbyResponse.Result.valueOf(result_);
    return result == null ? POGOProtos.Networking.Responses.JoinLobbyResponse.Result.UNRECOGNIZED : result;
  }

  public static final int LOBBY_FIELD_NUMBER = 2;
  private POGOProtos.Data.Raid.Lobby lobby_;
  /**
   * <code>.POGOProtos.Data.Raid.Lobby lobby = 2;</code>
   * @return Whether the lobby field is set.
   */
  public boolean hasLobby() {
    return lobby_ != null;
  }
  /**
   * <code>.POGOProtos.Data.Raid.Lobby lobby = 2;</code>
   * @return The lobby.
   */
  public POGOProtos.Data.Raid.Lobby getLobby() {
    return lobby_ == null ? POGOProtos.Data.Raid.Lobby.getDefaultInstance() : lobby_;
  }
  /**
   * <code>.POGOProtos.Data.Raid.Lobby lobby = 2;</code>
   */
  public POGOProtos.Data.Raid.LobbyOrBuilder getLobbyOrBuilder() {
    return getLobby();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (result_ != POGOProtos.Networking.Responses.JoinLobbyResponse.Result.UNSET.getNumber()) {
      output.writeEnum(1, result_);
    }
    if (lobby_ != null) {
      output.writeMessage(2, getLobby());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (result_ != POGOProtos.Networking.Responses.JoinLobbyResponse.Result.UNSET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, result_);
    }
    if (lobby_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getLobby());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof POGOProtos.Networking.Responses.JoinLobbyResponse)) {
      return super.equals(obj);
    }
    POGOProtos.Networking.Responses.JoinLobbyResponse other = (POGOProtos.Networking.Responses.JoinLobbyResponse) obj;

    if (result_ != other.result_) return false;
    if (hasLobby() != other.hasLobby()) return false;
    if (hasLobby()) {
      if (!getLobby()
          .equals(other.getLobby())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESULT_FIELD_NUMBER;
    hash = (53 * hash) + result_;
    if (hasLobby()) {
      hash = (37 * hash) + LOBBY_FIELD_NUMBER;
      hash = (53 * hash) + getLobby().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static POGOProtos.Networking.Responses.JoinLobbyResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Networking.Responses.JoinLobbyResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Networking.Responses.JoinLobbyResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Networking.Responses.JoinLobbyResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Networking.Responses.JoinLobbyResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Networking.Responses.JoinLobbyResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Networking.Responses.JoinLobbyResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Networking.Responses.JoinLobbyResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Networking.Responses.JoinLobbyResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static POGOProtos.Networking.Responses.JoinLobbyResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Networking.Responses.JoinLobbyResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Networking.Responses.JoinLobbyResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(POGOProtos.Networking.Responses.JoinLobbyResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code POGOProtos.Networking.Responses.JoinLobbyResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:POGOProtos.Networking.Responses.JoinLobbyResponse)
      POGOProtos.Networking.Responses.JoinLobbyResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Networking.Responses.JoinLobbyResponseOuterClass.internal_static_POGOProtos_Networking_Responses_JoinLobbyResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Networking.Responses.JoinLobbyResponseOuterClass.internal_static_POGOProtos_Networking_Responses_JoinLobbyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Networking.Responses.JoinLobbyResponse.class, POGOProtos.Networking.Responses.JoinLobbyResponse.Builder.class);
    }

    // Construct using POGOProtos.Networking.Responses.JoinLobbyResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      result_ = 0;

      if (lobbyBuilder_ == null) {
        lobby_ = null;
      } else {
        lobby_ = null;
        lobbyBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return POGOProtos.Networking.Responses.JoinLobbyResponseOuterClass.internal_static_POGOProtos_Networking_Responses_JoinLobbyResponse_descriptor;
    }

    @java.lang.Override
    public POGOProtos.Networking.Responses.JoinLobbyResponse getDefaultInstanceForType() {
      return POGOProtos.Networking.Responses.JoinLobbyResponse.getDefaultInstance();
    }

    @java.lang.Override
    public POGOProtos.Networking.Responses.JoinLobbyResponse build() {
      POGOProtos.Networking.Responses.JoinLobbyResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public POGOProtos.Networking.Responses.JoinLobbyResponse buildPartial() {
      POGOProtos.Networking.Responses.JoinLobbyResponse result = new POGOProtos.Networking.Responses.JoinLobbyResponse(this);
      result.result_ = result_;
      if (lobbyBuilder_ == null) {
        result.lobby_ = lobby_;
      } else {
        result.lobby_ = lobbyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof POGOProtos.Networking.Responses.JoinLobbyResponse) {
        return mergeFrom((POGOProtos.Networking.Responses.JoinLobbyResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(POGOProtos.Networking.Responses.JoinLobbyResponse other) {
      if (other == POGOProtos.Networking.Responses.JoinLobbyResponse.getDefaultInstance()) return this;
      if (other.result_ != 0) {
        setResultValue(other.getResultValue());
      }
      if (other.hasLobby()) {
        mergeLobby(other.getLobby());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      POGOProtos.Networking.Responses.JoinLobbyResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (POGOProtos.Networking.Responses.JoinLobbyResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int result_ = 0;
    /**
     * <code>.POGOProtos.Networking.Responses.JoinLobbyResponse.Result result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    public int getResultValue() {
      return result_;
    }
    /**
     * <code>.POGOProtos.Networking.Responses.JoinLobbyResponse.Result result = 1;</code>
     * @param value The enum numeric value on the wire for result to set.
     * @return This builder for chaining.
     */
    public Builder setResultValue(int value) {
      result_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Networking.Responses.JoinLobbyResponse.Result result = 1;</code>
     * @return The result.
     */
    public POGOProtos.Networking.Responses.JoinLobbyResponse.Result getResult() {
      @SuppressWarnings("deprecation")
      POGOProtos.Networking.Responses.JoinLobbyResponse.Result result = POGOProtos.Networking.Responses.JoinLobbyResponse.Result.valueOf(result_);
      return result == null ? POGOProtos.Networking.Responses.JoinLobbyResponse.Result.UNRECOGNIZED : result;
    }
    /**
     * <code>.POGOProtos.Networking.Responses.JoinLobbyResponse.Result result = 1;</code>
     * @param value The result to set.
     * @return This builder for chaining.
     */
    public Builder setResult(POGOProtos.Networking.Responses.JoinLobbyResponse.Result value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      result_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Networking.Responses.JoinLobbyResponse.Result result = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearResult() {
      
      result_ = 0;
      onChanged();
      return this;
    }

    private POGOProtos.Data.Raid.Lobby lobby_;
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Data.Raid.Lobby, POGOProtos.Data.Raid.Lobby.Builder, POGOProtos.Data.Raid.LobbyOrBuilder> lobbyBuilder_;
    /**
     * <code>.POGOProtos.Data.Raid.Lobby lobby = 2;</code>
     * @return Whether the lobby field is set.
     */
    public boolean hasLobby() {
      return lobbyBuilder_ != null || lobby_ != null;
    }
    /**
     * <code>.POGOProtos.Data.Raid.Lobby lobby = 2;</code>
     * @return The lobby.
     */
    public POGOProtos.Data.Raid.Lobby getLobby() {
      if (lobbyBuilder_ == null) {
        return lobby_ == null ? POGOProtos.Data.Raid.Lobby.getDefaultInstance() : lobby_;
      } else {
        return lobbyBuilder_.getMessage();
      }
    }
    /**
     * <code>.POGOProtos.Data.Raid.Lobby lobby = 2;</code>
     */
    public Builder setLobby(POGOProtos.Data.Raid.Lobby value) {
      if (lobbyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lobby_ = value;
        onChanged();
      } else {
        lobbyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Data.Raid.Lobby lobby = 2;</code>
     */
    public Builder setLobby(
        POGOProtos.Data.Raid.Lobby.Builder builderForValue) {
      if (lobbyBuilder_ == null) {
        lobby_ = builderForValue.build();
        onChanged();
      } else {
        lobbyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Data.Raid.Lobby lobby = 2;</code>
     */
    public Builder mergeLobby(POGOProtos.Data.Raid.Lobby value) {
      if (lobbyBuilder_ == null) {
        if (lobby_ != null) {
          lobby_ =
            POGOProtos.Data.Raid.Lobby.newBuilder(lobby_).mergeFrom(value).buildPartial();
        } else {
          lobby_ = value;
        }
        onChanged();
      } else {
        lobbyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Data.Raid.Lobby lobby = 2;</code>
     */
    public Builder clearLobby() {
      if (lobbyBuilder_ == null) {
        lobby_ = null;
        onChanged();
      } else {
        lobby_ = null;
        lobbyBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Data.Raid.Lobby lobby = 2;</code>
     */
    public POGOProtos.Data.Raid.Lobby.Builder getLobbyBuilder() {
      
      onChanged();
      return getLobbyFieldBuilder().getBuilder();
    }
    /**
     * <code>.POGOProtos.Data.Raid.Lobby lobby = 2;</code>
     */
    public POGOProtos.Data.Raid.LobbyOrBuilder getLobbyOrBuilder() {
      if (lobbyBuilder_ != null) {
        return lobbyBuilder_.getMessageOrBuilder();
      } else {
        return lobby_ == null ?
            POGOProtos.Data.Raid.Lobby.getDefaultInstance() : lobby_;
      }
    }
    /**
     * <code>.POGOProtos.Data.Raid.Lobby lobby = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Data.Raid.Lobby, POGOProtos.Data.Raid.Lobby.Builder, POGOProtos.Data.Raid.LobbyOrBuilder> 
        getLobbyFieldBuilder() {
      if (lobbyBuilder_ == null) {
        lobbyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            POGOProtos.Data.Raid.Lobby, POGOProtos.Data.Raid.Lobby.Builder, POGOProtos.Data.Raid.LobbyOrBuilder>(
                getLobby(),
                getParentForChildren(),
                isClean());
        lobby_ = null;
      }
      return lobbyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:POGOProtos.Networking.Responses.JoinLobbyResponse)
  }

  // @@protoc_insertion_point(class_scope:POGOProtos.Networking.Responses.JoinLobbyResponse)
  private static final POGOProtos.Networking.Responses.JoinLobbyResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new POGOProtos.Networking.Responses.JoinLobbyResponse();
  }

  public static POGOProtos.Networking.Responses.JoinLobbyResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JoinLobbyResponse>
      PARSER = new com.google.protobuf.AbstractParser<JoinLobbyResponse>() {
    @java.lang.Override
    public JoinLobbyResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JoinLobbyResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JoinLobbyResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JoinLobbyResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public POGOProtos.Networking.Responses.JoinLobbyResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

