// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Requests/Messages/EncounterTutorialCompleteMessage.proto

package POGOProtos.Networking.Requests.Messages;

public interface EncounterTutorialCompleteMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Networking.Requests.Messages.EncounterTutorialCompleteMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.POGOProtos.Enums.PokemonId pokemon_id = 1;</code>
   * @return The enum numeric value on the wire for pokemonId.
   */
  int getPokemonIdValue();
  /**
   * <code>.POGOProtos.Enums.PokemonId pokemon_id = 1;</code>
   * @return The pokemonId.
   */
  POGOProtos.Enums.PokemonId getPokemonId();
}
