// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Rpc/Rpc.proto

package POGOProtos.Rpc;

/**
 * Protobuf type {@code POGOProtos.Rpc.ALNJOFCBHPH}
 */
public  final class ALNJOFCBHPH extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:POGOProtos.Rpc.ALNJOFCBHPH)
    ALNJOFCBHPHOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ALNJOFCBHPH.newBuilder() to construct.
  private ALNJOFCBHPH(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ALNJOFCBHPH() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ALNJOFCBHPH();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ALNJOFCBHPH(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            POGOProtos.Rpc.EBADGCJAAGC.Builder subBuilder = null;
            if (knagdmgebok_ != null) {
              subBuilder = knagdmgebok_.toBuilder();
            }
            knagdmgebok_ = input.readMessage(POGOProtos.Rpc.EBADGCJAAGC.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(knagdmgebok_);
              knagdmgebok_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return POGOProtos.Rpc.Rpc.internal_static_POGOProtos_Rpc_ALNJOFCBHPH_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return POGOProtos.Rpc.Rpc.internal_static_POGOProtos_Rpc_ALNJOFCBHPH_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            POGOProtos.Rpc.ALNJOFCBHPH.class, POGOProtos.Rpc.ALNJOFCBHPH.Builder.class);
  }

  public static final int KNAGDMGEBOK_FIELD_NUMBER = 1;
  private POGOProtos.Rpc.EBADGCJAAGC knagdmgebok_;
  /**
   * <code>.POGOProtos.Rpc.EBADGCJAAGC knagdmgebok = 1;</code>
   * @return Whether the knagdmgebok field is set.
   */
  public boolean hasKnagdmgebok() {
    return knagdmgebok_ != null;
  }
  /**
   * <code>.POGOProtos.Rpc.EBADGCJAAGC knagdmgebok = 1;</code>
   * @return The knagdmgebok.
   */
  public POGOProtos.Rpc.EBADGCJAAGC getKnagdmgebok() {
    return knagdmgebok_ == null ? POGOProtos.Rpc.EBADGCJAAGC.getDefaultInstance() : knagdmgebok_;
  }
  /**
   * <code>.POGOProtos.Rpc.EBADGCJAAGC knagdmgebok = 1;</code>
   */
  public POGOProtos.Rpc.EBADGCJAAGCOrBuilder getKnagdmgebokOrBuilder() {
    return getKnagdmgebok();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (knagdmgebok_ != null) {
      output.writeMessage(1, getKnagdmgebok());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (knagdmgebok_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getKnagdmgebok());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof POGOProtos.Rpc.ALNJOFCBHPH)) {
      return super.equals(obj);
    }
    POGOProtos.Rpc.ALNJOFCBHPH other = (POGOProtos.Rpc.ALNJOFCBHPH) obj;

    if (hasKnagdmgebok() != other.hasKnagdmgebok()) return false;
    if (hasKnagdmgebok()) {
      if (!getKnagdmgebok()
          .equals(other.getKnagdmgebok())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasKnagdmgebok()) {
      hash = (37 * hash) + KNAGDMGEBOK_FIELD_NUMBER;
      hash = (53 * hash) + getKnagdmgebok().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static POGOProtos.Rpc.ALNJOFCBHPH parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.ALNJOFCBHPH parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.ALNJOFCBHPH parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.ALNJOFCBHPH parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.ALNJOFCBHPH parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.ALNJOFCBHPH parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.ALNJOFCBHPH parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.ALNJOFCBHPH parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.ALNJOFCBHPH parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.ALNJOFCBHPH parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.ALNJOFCBHPH parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.ALNJOFCBHPH parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(POGOProtos.Rpc.ALNJOFCBHPH prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code POGOProtos.Rpc.ALNJOFCBHPH}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:POGOProtos.Rpc.ALNJOFCBHPH)
      POGOProtos.Rpc.ALNJOFCBHPHOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Rpc.Rpc.internal_static_POGOProtos_Rpc_ALNJOFCBHPH_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Rpc.Rpc.internal_static_POGOProtos_Rpc_ALNJOFCBHPH_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Rpc.ALNJOFCBHPH.class, POGOProtos.Rpc.ALNJOFCBHPH.Builder.class);
    }

    // Construct using POGOProtos.Rpc.ALNJOFCBHPH.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (knagdmgebokBuilder_ == null) {
        knagdmgebok_ = null;
      } else {
        knagdmgebok_ = null;
        knagdmgebokBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return POGOProtos.Rpc.Rpc.internal_static_POGOProtos_Rpc_ALNJOFCBHPH_descriptor;
    }

    @java.lang.Override
    public POGOProtos.Rpc.ALNJOFCBHPH getDefaultInstanceForType() {
      return POGOProtos.Rpc.ALNJOFCBHPH.getDefaultInstance();
    }

    @java.lang.Override
    public POGOProtos.Rpc.ALNJOFCBHPH build() {
      POGOProtos.Rpc.ALNJOFCBHPH result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public POGOProtos.Rpc.ALNJOFCBHPH buildPartial() {
      POGOProtos.Rpc.ALNJOFCBHPH result = new POGOProtos.Rpc.ALNJOFCBHPH(this);
      if (knagdmgebokBuilder_ == null) {
        result.knagdmgebok_ = knagdmgebok_;
      } else {
        result.knagdmgebok_ = knagdmgebokBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof POGOProtos.Rpc.ALNJOFCBHPH) {
        return mergeFrom((POGOProtos.Rpc.ALNJOFCBHPH)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(POGOProtos.Rpc.ALNJOFCBHPH other) {
      if (other == POGOProtos.Rpc.ALNJOFCBHPH.getDefaultInstance()) return this;
      if (other.hasKnagdmgebok()) {
        mergeKnagdmgebok(other.getKnagdmgebok());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      POGOProtos.Rpc.ALNJOFCBHPH parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (POGOProtos.Rpc.ALNJOFCBHPH) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private POGOProtos.Rpc.EBADGCJAAGC knagdmgebok_;
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.EBADGCJAAGC, POGOProtos.Rpc.EBADGCJAAGC.Builder, POGOProtos.Rpc.EBADGCJAAGCOrBuilder> knagdmgebokBuilder_;
    /**
     * <code>.POGOProtos.Rpc.EBADGCJAAGC knagdmgebok = 1;</code>
     * @return Whether the knagdmgebok field is set.
     */
    public boolean hasKnagdmgebok() {
      return knagdmgebokBuilder_ != null || knagdmgebok_ != null;
    }
    /**
     * <code>.POGOProtos.Rpc.EBADGCJAAGC knagdmgebok = 1;</code>
     * @return The knagdmgebok.
     */
    public POGOProtos.Rpc.EBADGCJAAGC getKnagdmgebok() {
      if (knagdmgebokBuilder_ == null) {
        return knagdmgebok_ == null ? POGOProtos.Rpc.EBADGCJAAGC.getDefaultInstance() : knagdmgebok_;
      } else {
        return knagdmgebokBuilder_.getMessage();
      }
    }
    /**
     * <code>.POGOProtos.Rpc.EBADGCJAAGC knagdmgebok = 1;</code>
     */
    public Builder setKnagdmgebok(POGOProtos.Rpc.EBADGCJAAGC value) {
      if (knagdmgebokBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        knagdmgebok_ = value;
        onChanged();
      } else {
        knagdmgebokBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.EBADGCJAAGC knagdmgebok = 1;</code>
     */
    public Builder setKnagdmgebok(
        POGOProtos.Rpc.EBADGCJAAGC.Builder builderForValue) {
      if (knagdmgebokBuilder_ == null) {
        knagdmgebok_ = builderForValue.build();
        onChanged();
      } else {
        knagdmgebokBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.EBADGCJAAGC knagdmgebok = 1;</code>
     */
    public Builder mergeKnagdmgebok(POGOProtos.Rpc.EBADGCJAAGC value) {
      if (knagdmgebokBuilder_ == null) {
        if (knagdmgebok_ != null) {
          knagdmgebok_ =
            POGOProtos.Rpc.EBADGCJAAGC.newBuilder(knagdmgebok_).mergeFrom(value).buildPartial();
        } else {
          knagdmgebok_ = value;
        }
        onChanged();
      } else {
        knagdmgebokBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.EBADGCJAAGC knagdmgebok = 1;</code>
     */
    public Builder clearKnagdmgebok() {
      if (knagdmgebokBuilder_ == null) {
        knagdmgebok_ = null;
        onChanged();
      } else {
        knagdmgebok_ = null;
        knagdmgebokBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.EBADGCJAAGC knagdmgebok = 1;</code>
     */
    public POGOProtos.Rpc.EBADGCJAAGC.Builder getKnagdmgebokBuilder() {
      
      onChanged();
      return getKnagdmgebokFieldBuilder().getBuilder();
    }
    /**
     * <code>.POGOProtos.Rpc.EBADGCJAAGC knagdmgebok = 1;</code>
     */
    public POGOProtos.Rpc.EBADGCJAAGCOrBuilder getKnagdmgebokOrBuilder() {
      if (knagdmgebokBuilder_ != null) {
        return knagdmgebokBuilder_.getMessageOrBuilder();
      } else {
        return knagdmgebok_ == null ?
            POGOProtos.Rpc.EBADGCJAAGC.getDefaultInstance() : knagdmgebok_;
      }
    }
    /**
     * <code>.POGOProtos.Rpc.EBADGCJAAGC knagdmgebok = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.EBADGCJAAGC, POGOProtos.Rpc.EBADGCJAAGC.Builder, POGOProtos.Rpc.EBADGCJAAGCOrBuilder> 
        getKnagdmgebokFieldBuilder() {
      if (knagdmgebokBuilder_ == null) {
        knagdmgebokBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            POGOProtos.Rpc.EBADGCJAAGC, POGOProtos.Rpc.EBADGCJAAGC.Builder, POGOProtos.Rpc.EBADGCJAAGCOrBuilder>(
                getKnagdmgebok(),
                getParentForChildren(),
                isClean());
        knagdmgebok_ = null;
      }
      return knagdmgebokBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:POGOProtos.Rpc.ALNJOFCBHPH)
  }

  // @@protoc_insertion_point(class_scope:POGOProtos.Rpc.ALNJOFCBHPH)
  private static final POGOProtos.Rpc.ALNJOFCBHPH DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new POGOProtos.Rpc.ALNJOFCBHPH();
  }

  public static POGOProtos.Rpc.ALNJOFCBHPH getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ALNJOFCBHPH>
      PARSER = new com.google.protobuf.AbstractParser<ALNJOFCBHPH>() {
    @java.lang.Override
    public ALNJOFCBHPH parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ALNJOFCBHPH(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ALNJOFCBHPH> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ALNJOFCBHPH> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public POGOProtos.Rpc.ALNJOFCBHPH getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

