// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface BNBCECHBDALOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.BNBCECHBDAL)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.POGOProtos.Rpc.BNBCECHBDAL.Result result = 1;</code>
   * @return The enum numeric value on the wire for result.
   */
  int getResultValue();
  /**
   * <code>.POGOProtos.Rpc.BNBCECHBDAL.Result result = 1;</code>
   * @return The result.
   */
  POGOProtos.Rpc.BNBCECHBDAL.Result getResult();

  /**
   * <code>.POGOProtos.Rpc.BattleProto jpiinjpkhfb = 2;</code>
   * @return Whether the jpiinjpkhfb field is set.
   */
  boolean hasJpiinjpkhfb();
  /**
   * <code>.POGOProtos.Rpc.BattleProto jpiinjpkhfb = 2;</code>
   * @return The jpiinjpkhfb.
   */
  POGOProtos.Rpc.BattleProto getJpiinjpkhfb();
  /**
   * <code>.POGOProtos.Rpc.BattleProto jpiinjpkhfb = 2;</code>
   */
  POGOProtos.Rpc.BattleProtoOrBuilder getJpiinjpkhfbOrBuilder();
}
