// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

/**
 * <pre>
 * ref: BPGNLCIMNMM
 * </pre>
 *
 * Protobuf type {@code POGOProtos.Rpc.BPGNLCIMNMM}
 */
public final class BPGNLCIMNMM extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:POGOProtos.Rpc.BPGNLCIMNMM)
    BPGNLCIMNMMOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BPGNLCIMNMM.newBuilder() to construct.
  private BPGNLCIMNMM(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BPGNLCIMNMM() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BPGNLCIMNMM();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BPGNLCIMNMM(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            POGOProtos.Rpc.HLMHEHDLBOG.Builder subBuilder = null;
            if (pjngpbbccpe_ != null) {
              subBuilder = pjngpbbccpe_.toBuilder();
            }
            pjngpbbccpe_ = input.readMessage(POGOProtos.Rpc.HLMHEHDLBOG.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pjngpbbccpe_);
              pjngpbbccpe_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            POGOProtos.Rpc.KDPGFPGNEOK.Builder subBuilder = null;
            if (ekabbaofplg_ != null) {
              subBuilder = ekabbaofplg_.toBuilder();
            }
            ekabbaofplg_ = input.readMessage(POGOProtos.Rpc.KDPGFPGNEOK.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(ekabbaofplg_);
              ekabbaofplg_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            POGOProtos.Rpc.ABCJJNCNEEP.Builder subBuilder = null;
            if (fjifdhjahjl_ != null) {
              subBuilder = fjifdhjahjl_.toBuilder();
            }
            fjifdhjahjl_ = input.readMessage(POGOProtos.Rpc.ABCJJNCNEEP.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(fjifdhjahjl_);
              fjifdhjahjl_ = subBuilder.buildPartial();
            }

            break;
          }
          case 8010: {
            POGOProtos.Rpc.PlatformServerData.Builder subBuilder = null;
            if (oapiigkejkf_ != null) {
              subBuilder = oapiigkejkf_.toBuilder();
            }
            oapiigkejkf_ = input.readMessage(POGOProtos.Rpc.PlatformServerData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(oapiigkejkf_);
              oapiigkejkf_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_BPGNLCIMNMM_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_BPGNLCIMNMM_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            POGOProtos.Rpc.BPGNLCIMNMM.class, POGOProtos.Rpc.BPGNLCIMNMM.Builder.class);
  }

  public static final int PJNGPBBCCPE_FIELD_NUMBER = 1;
  private POGOProtos.Rpc.HLMHEHDLBOG pjngpbbccpe_;
  /**
   * <code>.POGOProtos.Rpc.HLMHEHDLBOG pjngpbbccpe = 1;</code>
   * @return Whether the pjngpbbccpe field is set.
   */
  @java.lang.Override
  public boolean hasPjngpbbccpe() {
    return pjngpbbccpe_ != null;
  }
  /**
   * <code>.POGOProtos.Rpc.HLMHEHDLBOG pjngpbbccpe = 1;</code>
   * @return The pjngpbbccpe.
   */
  @java.lang.Override
  public POGOProtos.Rpc.HLMHEHDLBOG getPjngpbbccpe() {
    return pjngpbbccpe_ == null ? POGOProtos.Rpc.HLMHEHDLBOG.getDefaultInstance() : pjngpbbccpe_;
  }
  /**
   * <code>.POGOProtos.Rpc.HLMHEHDLBOG pjngpbbccpe = 1;</code>
   */
  @java.lang.Override
  public POGOProtos.Rpc.HLMHEHDLBOGOrBuilder getPjngpbbccpeOrBuilder() {
    return getPjngpbbccpe();
  }

  public static final int EKABBAOFPLG_FIELD_NUMBER = 2;
  private POGOProtos.Rpc.KDPGFPGNEOK ekabbaofplg_;
  /**
   * <code>.POGOProtos.Rpc.KDPGFPGNEOK ekabbaofplg = 2;</code>
   * @return Whether the ekabbaofplg field is set.
   */
  @java.lang.Override
  public boolean hasEkabbaofplg() {
    return ekabbaofplg_ != null;
  }
  /**
   * <code>.POGOProtos.Rpc.KDPGFPGNEOK ekabbaofplg = 2;</code>
   * @return The ekabbaofplg.
   */
  @java.lang.Override
  public POGOProtos.Rpc.KDPGFPGNEOK getEkabbaofplg() {
    return ekabbaofplg_ == null ? POGOProtos.Rpc.KDPGFPGNEOK.getDefaultInstance() : ekabbaofplg_;
  }
  /**
   * <code>.POGOProtos.Rpc.KDPGFPGNEOK ekabbaofplg = 2;</code>
   */
  @java.lang.Override
  public POGOProtos.Rpc.KDPGFPGNEOKOrBuilder getEkabbaofplgOrBuilder() {
    return getEkabbaofplg();
  }

  public static final int FJIFDHJAHJL_FIELD_NUMBER = 3;
  private POGOProtos.Rpc.ABCJJNCNEEP fjifdhjahjl_;
  /**
   * <code>.POGOProtos.Rpc.ABCJJNCNEEP fjifdhjahjl = 3;</code>
   * @return Whether the fjifdhjahjl field is set.
   */
  @java.lang.Override
  public boolean hasFjifdhjahjl() {
    return fjifdhjahjl_ != null;
  }
  /**
   * <code>.POGOProtos.Rpc.ABCJJNCNEEP fjifdhjahjl = 3;</code>
   * @return The fjifdhjahjl.
   */
  @java.lang.Override
  public POGOProtos.Rpc.ABCJJNCNEEP getFjifdhjahjl() {
    return fjifdhjahjl_ == null ? POGOProtos.Rpc.ABCJJNCNEEP.getDefaultInstance() : fjifdhjahjl_;
  }
  /**
   * <code>.POGOProtos.Rpc.ABCJJNCNEEP fjifdhjahjl = 3;</code>
   */
  @java.lang.Override
  public POGOProtos.Rpc.ABCJJNCNEEPOrBuilder getFjifdhjahjlOrBuilder() {
    return getFjifdhjahjl();
  }

  public static final int OAPIIGKEJKF_FIELD_NUMBER = 1001;
  private POGOProtos.Rpc.PlatformServerData oapiigkejkf_;
  /**
   * <code>.POGOProtos.Rpc.PlatformServerData oapiigkejkf = 1001;</code>
   * @return Whether the oapiigkejkf field is set.
   */
  @java.lang.Override
  public boolean hasOapiigkejkf() {
    return oapiigkejkf_ != null;
  }
  /**
   * <code>.POGOProtos.Rpc.PlatformServerData oapiigkejkf = 1001;</code>
   * @return The oapiigkejkf.
   */
  @java.lang.Override
  public POGOProtos.Rpc.PlatformServerData getOapiigkejkf() {
    return oapiigkejkf_ == null ? POGOProtos.Rpc.PlatformServerData.getDefaultInstance() : oapiigkejkf_;
  }
  /**
   * <code>.POGOProtos.Rpc.PlatformServerData oapiigkejkf = 1001;</code>
   */
  @java.lang.Override
  public POGOProtos.Rpc.PlatformServerDataOrBuilder getOapiigkejkfOrBuilder() {
    return getOapiigkejkf();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pjngpbbccpe_ != null) {
      output.writeMessage(1, getPjngpbbccpe());
    }
    if (ekabbaofplg_ != null) {
      output.writeMessage(2, getEkabbaofplg());
    }
    if (fjifdhjahjl_ != null) {
      output.writeMessage(3, getFjifdhjahjl());
    }
    if (oapiigkejkf_ != null) {
      output.writeMessage(1001, getOapiigkejkf());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pjngpbbccpe_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPjngpbbccpe());
    }
    if (ekabbaofplg_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEkabbaofplg());
    }
    if (fjifdhjahjl_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getFjifdhjahjl());
    }
    if (oapiigkejkf_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1001, getOapiigkejkf());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof POGOProtos.Rpc.BPGNLCIMNMM)) {
      return super.equals(obj);
    }
    POGOProtos.Rpc.BPGNLCIMNMM other = (POGOProtos.Rpc.BPGNLCIMNMM) obj;

    if (hasPjngpbbccpe() != other.hasPjngpbbccpe()) return false;
    if (hasPjngpbbccpe()) {
      if (!getPjngpbbccpe()
          .equals(other.getPjngpbbccpe())) return false;
    }
    if (hasEkabbaofplg() != other.hasEkabbaofplg()) return false;
    if (hasEkabbaofplg()) {
      if (!getEkabbaofplg()
          .equals(other.getEkabbaofplg())) return false;
    }
    if (hasFjifdhjahjl() != other.hasFjifdhjahjl()) return false;
    if (hasFjifdhjahjl()) {
      if (!getFjifdhjahjl()
          .equals(other.getFjifdhjahjl())) return false;
    }
    if (hasOapiigkejkf() != other.hasOapiigkejkf()) return false;
    if (hasOapiigkejkf()) {
      if (!getOapiigkejkf()
          .equals(other.getOapiigkejkf())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPjngpbbccpe()) {
      hash = (37 * hash) + PJNGPBBCCPE_FIELD_NUMBER;
      hash = (53 * hash) + getPjngpbbccpe().hashCode();
    }
    if (hasEkabbaofplg()) {
      hash = (37 * hash) + EKABBAOFPLG_FIELD_NUMBER;
      hash = (53 * hash) + getEkabbaofplg().hashCode();
    }
    if (hasFjifdhjahjl()) {
      hash = (37 * hash) + FJIFDHJAHJL_FIELD_NUMBER;
      hash = (53 * hash) + getFjifdhjahjl().hashCode();
    }
    if (hasOapiigkejkf()) {
      hash = (37 * hash) + OAPIIGKEJKF_FIELD_NUMBER;
      hash = (53 * hash) + getOapiigkejkf().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static POGOProtos.Rpc.BPGNLCIMNMM parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.BPGNLCIMNMM parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.BPGNLCIMNMM parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.BPGNLCIMNMM parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.BPGNLCIMNMM parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.BPGNLCIMNMM parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.BPGNLCIMNMM parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.BPGNLCIMNMM parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.BPGNLCIMNMM parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.BPGNLCIMNMM parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.BPGNLCIMNMM parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.BPGNLCIMNMM parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(POGOProtos.Rpc.BPGNLCIMNMM prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ref: BPGNLCIMNMM
   * </pre>
   *
   * Protobuf type {@code POGOProtos.Rpc.BPGNLCIMNMM}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:POGOProtos.Rpc.BPGNLCIMNMM)
      POGOProtos.Rpc.BPGNLCIMNMMOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_BPGNLCIMNMM_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_BPGNLCIMNMM_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Rpc.BPGNLCIMNMM.class, POGOProtos.Rpc.BPGNLCIMNMM.Builder.class);
    }

    // Construct using POGOProtos.Rpc.BPGNLCIMNMM.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (pjngpbbccpeBuilder_ == null) {
        pjngpbbccpe_ = null;
      } else {
        pjngpbbccpe_ = null;
        pjngpbbccpeBuilder_ = null;
      }
      if (ekabbaofplgBuilder_ == null) {
        ekabbaofplg_ = null;
      } else {
        ekabbaofplg_ = null;
        ekabbaofplgBuilder_ = null;
      }
      if (fjifdhjahjlBuilder_ == null) {
        fjifdhjahjl_ = null;
      } else {
        fjifdhjahjl_ = null;
        fjifdhjahjlBuilder_ = null;
      }
      if (oapiigkejkfBuilder_ == null) {
        oapiigkejkf_ = null;
      } else {
        oapiigkejkf_ = null;
        oapiigkejkfBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_BPGNLCIMNMM_descriptor;
    }

    @java.lang.Override
    public POGOProtos.Rpc.BPGNLCIMNMM getDefaultInstanceForType() {
      return POGOProtos.Rpc.BPGNLCIMNMM.getDefaultInstance();
    }

    @java.lang.Override
    public POGOProtos.Rpc.BPGNLCIMNMM build() {
      POGOProtos.Rpc.BPGNLCIMNMM result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public POGOProtos.Rpc.BPGNLCIMNMM buildPartial() {
      POGOProtos.Rpc.BPGNLCIMNMM result = new POGOProtos.Rpc.BPGNLCIMNMM(this);
      if (pjngpbbccpeBuilder_ == null) {
        result.pjngpbbccpe_ = pjngpbbccpe_;
      } else {
        result.pjngpbbccpe_ = pjngpbbccpeBuilder_.build();
      }
      if (ekabbaofplgBuilder_ == null) {
        result.ekabbaofplg_ = ekabbaofplg_;
      } else {
        result.ekabbaofplg_ = ekabbaofplgBuilder_.build();
      }
      if (fjifdhjahjlBuilder_ == null) {
        result.fjifdhjahjl_ = fjifdhjahjl_;
      } else {
        result.fjifdhjahjl_ = fjifdhjahjlBuilder_.build();
      }
      if (oapiigkejkfBuilder_ == null) {
        result.oapiigkejkf_ = oapiigkejkf_;
      } else {
        result.oapiigkejkf_ = oapiigkejkfBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof POGOProtos.Rpc.BPGNLCIMNMM) {
        return mergeFrom((POGOProtos.Rpc.BPGNLCIMNMM)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(POGOProtos.Rpc.BPGNLCIMNMM other) {
      if (other == POGOProtos.Rpc.BPGNLCIMNMM.getDefaultInstance()) return this;
      if (other.hasPjngpbbccpe()) {
        mergePjngpbbccpe(other.getPjngpbbccpe());
      }
      if (other.hasEkabbaofplg()) {
        mergeEkabbaofplg(other.getEkabbaofplg());
      }
      if (other.hasFjifdhjahjl()) {
        mergeFjifdhjahjl(other.getFjifdhjahjl());
      }
      if (other.hasOapiigkejkf()) {
        mergeOapiigkejkf(other.getOapiigkejkf());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      POGOProtos.Rpc.BPGNLCIMNMM parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (POGOProtos.Rpc.BPGNLCIMNMM) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private POGOProtos.Rpc.HLMHEHDLBOG pjngpbbccpe_;
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.HLMHEHDLBOG, POGOProtos.Rpc.HLMHEHDLBOG.Builder, POGOProtos.Rpc.HLMHEHDLBOGOrBuilder> pjngpbbccpeBuilder_;
    /**
     * <code>.POGOProtos.Rpc.HLMHEHDLBOG pjngpbbccpe = 1;</code>
     * @return Whether the pjngpbbccpe field is set.
     */
    public boolean hasPjngpbbccpe() {
      return pjngpbbccpeBuilder_ != null || pjngpbbccpe_ != null;
    }
    /**
     * <code>.POGOProtos.Rpc.HLMHEHDLBOG pjngpbbccpe = 1;</code>
     * @return The pjngpbbccpe.
     */
    public POGOProtos.Rpc.HLMHEHDLBOG getPjngpbbccpe() {
      if (pjngpbbccpeBuilder_ == null) {
        return pjngpbbccpe_ == null ? POGOProtos.Rpc.HLMHEHDLBOG.getDefaultInstance() : pjngpbbccpe_;
      } else {
        return pjngpbbccpeBuilder_.getMessage();
      }
    }
    /**
     * <code>.POGOProtos.Rpc.HLMHEHDLBOG pjngpbbccpe = 1;</code>
     */
    public Builder setPjngpbbccpe(POGOProtos.Rpc.HLMHEHDLBOG value) {
      if (pjngpbbccpeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pjngpbbccpe_ = value;
        onChanged();
      } else {
        pjngpbbccpeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.HLMHEHDLBOG pjngpbbccpe = 1;</code>
     */
    public Builder setPjngpbbccpe(
        POGOProtos.Rpc.HLMHEHDLBOG.Builder builderForValue) {
      if (pjngpbbccpeBuilder_ == null) {
        pjngpbbccpe_ = builderForValue.build();
        onChanged();
      } else {
        pjngpbbccpeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.HLMHEHDLBOG pjngpbbccpe = 1;</code>
     */
    public Builder mergePjngpbbccpe(POGOProtos.Rpc.HLMHEHDLBOG value) {
      if (pjngpbbccpeBuilder_ == null) {
        if (pjngpbbccpe_ != null) {
          pjngpbbccpe_ =
            POGOProtos.Rpc.HLMHEHDLBOG.newBuilder(pjngpbbccpe_).mergeFrom(value).buildPartial();
        } else {
          pjngpbbccpe_ = value;
        }
        onChanged();
      } else {
        pjngpbbccpeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.HLMHEHDLBOG pjngpbbccpe = 1;</code>
     */
    public Builder clearPjngpbbccpe() {
      if (pjngpbbccpeBuilder_ == null) {
        pjngpbbccpe_ = null;
        onChanged();
      } else {
        pjngpbbccpe_ = null;
        pjngpbbccpeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.HLMHEHDLBOG pjngpbbccpe = 1;</code>
     */
    public POGOProtos.Rpc.HLMHEHDLBOG.Builder getPjngpbbccpeBuilder() {
      
      onChanged();
      return getPjngpbbccpeFieldBuilder().getBuilder();
    }
    /**
     * <code>.POGOProtos.Rpc.HLMHEHDLBOG pjngpbbccpe = 1;</code>
     */
    public POGOProtos.Rpc.HLMHEHDLBOGOrBuilder getPjngpbbccpeOrBuilder() {
      if (pjngpbbccpeBuilder_ != null) {
        return pjngpbbccpeBuilder_.getMessageOrBuilder();
      } else {
        return pjngpbbccpe_ == null ?
            POGOProtos.Rpc.HLMHEHDLBOG.getDefaultInstance() : pjngpbbccpe_;
      }
    }
    /**
     * <code>.POGOProtos.Rpc.HLMHEHDLBOG pjngpbbccpe = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.HLMHEHDLBOG, POGOProtos.Rpc.HLMHEHDLBOG.Builder, POGOProtos.Rpc.HLMHEHDLBOGOrBuilder> 
        getPjngpbbccpeFieldBuilder() {
      if (pjngpbbccpeBuilder_ == null) {
        pjngpbbccpeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            POGOProtos.Rpc.HLMHEHDLBOG, POGOProtos.Rpc.HLMHEHDLBOG.Builder, POGOProtos.Rpc.HLMHEHDLBOGOrBuilder>(
                getPjngpbbccpe(),
                getParentForChildren(),
                isClean());
        pjngpbbccpe_ = null;
      }
      return pjngpbbccpeBuilder_;
    }

    private POGOProtos.Rpc.KDPGFPGNEOK ekabbaofplg_;
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.KDPGFPGNEOK, POGOProtos.Rpc.KDPGFPGNEOK.Builder, POGOProtos.Rpc.KDPGFPGNEOKOrBuilder> ekabbaofplgBuilder_;
    /**
     * <code>.POGOProtos.Rpc.KDPGFPGNEOK ekabbaofplg = 2;</code>
     * @return Whether the ekabbaofplg field is set.
     */
    public boolean hasEkabbaofplg() {
      return ekabbaofplgBuilder_ != null || ekabbaofplg_ != null;
    }
    /**
     * <code>.POGOProtos.Rpc.KDPGFPGNEOK ekabbaofplg = 2;</code>
     * @return The ekabbaofplg.
     */
    public POGOProtos.Rpc.KDPGFPGNEOK getEkabbaofplg() {
      if (ekabbaofplgBuilder_ == null) {
        return ekabbaofplg_ == null ? POGOProtos.Rpc.KDPGFPGNEOK.getDefaultInstance() : ekabbaofplg_;
      } else {
        return ekabbaofplgBuilder_.getMessage();
      }
    }
    /**
     * <code>.POGOProtos.Rpc.KDPGFPGNEOK ekabbaofplg = 2;</code>
     */
    public Builder setEkabbaofplg(POGOProtos.Rpc.KDPGFPGNEOK value) {
      if (ekabbaofplgBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ekabbaofplg_ = value;
        onChanged();
      } else {
        ekabbaofplgBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.KDPGFPGNEOK ekabbaofplg = 2;</code>
     */
    public Builder setEkabbaofplg(
        POGOProtos.Rpc.KDPGFPGNEOK.Builder builderForValue) {
      if (ekabbaofplgBuilder_ == null) {
        ekabbaofplg_ = builderForValue.build();
        onChanged();
      } else {
        ekabbaofplgBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.KDPGFPGNEOK ekabbaofplg = 2;</code>
     */
    public Builder mergeEkabbaofplg(POGOProtos.Rpc.KDPGFPGNEOK value) {
      if (ekabbaofplgBuilder_ == null) {
        if (ekabbaofplg_ != null) {
          ekabbaofplg_ =
            POGOProtos.Rpc.KDPGFPGNEOK.newBuilder(ekabbaofplg_).mergeFrom(value).buildPartial();
        } else {
          ekabbaofplg_ = value;
        }
        onChanged();
      } else {
        ekabbaofplgBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.KDPGFPGNEOK ekabbaofplg = 2;</code>
     */
    public Builder clearEkabbaofplg() {
      if (ekabbaofplgBuilder_ == null) {
        ekabbaofplg_ = null;
        onChanged();
      } else {
        ekabbaofplg_ = null;
        ekabbaofplgBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.KDPGFPGNEOK ekabbaofplg = 2;</code>
     */
    public POGOProtos.Rpc.KDPGFPGNEOK.Builder getEkabbaofplgBuilder() {
      
      onChanged();
      return getEkabbaofplgFieldBuilder().getBuilder();
    }
    /**
     * <code>.POGOProtos.Rpc.KDPGFPGNEOK ekabbaofplg = 2;</code>
     */
    public POGOProtos.Rpc.KDPGFPGNEOKOrBuilder getEkabbaofplgOrBuilder() {
      if (ekabbaofplgBuilder_ != null) {
        return ekabbaofplgBuilder_.getMessageOrBuilder();
      } else {
        return ekabbaofplg_ == null ?
            POGOProtos.Rpc.KDPGFPGNEOK.getDefaultInstance() : ekabbaofplg_;
      }
    }
    /**
     * <code>.POGOProtos.Rpc.KDPGFPGNEOK ekabbaofplg = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.KDPGFPGNEOK, POGOProtos.Rpc.KDPGFPGNEOK.Builder, POGOProtos.Rpc.KDPGFPGNEOKOrBuilder> 
        getEkabbaofplgFieldBuilder() {
      if (ekabbaofplgBuilder_ == null) {
        ekabbaofplgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            POGOProtos.Rpc.KDPGFPGNEOK, POGOProtos.Rpc.KDPGFPGNEOK.Builder, POGOProtos.Rpc.KDPGFPGNEOKOrBuilder>(
                getEkabbaofplg(),
                getParentForChildren(),
                isClean());
        ekabbaofplg_ = null;
      }
      return ekabbaofplgBuilder_;
    }

    private POGOProtos.Rpc.ABCJJNCNEEP fjifdhjahjl_;
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.ABCJJNCNEEP, POGOProtos.Rpc.ABCJJNCNEEP.Builder, POGOProtos.Rpc.ABCJJNCNEEPOrBuilder> fjifdhjahjlBuilder_;
    /**
     * <code>.POGOProtos.Rpc.ABCJJNCNEEP fjifdhjahjl = 3;</code>
     * @return Whether the fjifdhjahjl field is set.
     */
    public boolean hasFjifdhjahjl() {
      return fjifdhjahjlBuilder_ != null || fjifdhjahjl_ != null;
    }
    /**
     * <code>.POGOProtos.Rpc.ABCJJNCNEEP fjifdhjahjl = 3;</code>
     * @return The fjifdhjahjl.
     */
    public POGOProtos.Rpc.ABCJJNCNEEP getFjifdhjahjl() {
      if (fjifdhjahjlBuilder_ == null) {
        return fjifdhjahjl_ == null ? POGOProtos.Rpc.ABCJJNCNEEP.getDefaultInstance() : fjifdhjahjl_;
      } else {
        return fjifdhjahjlBuilder_.getMessage();
      }
    }
    /**
     * <code>.POGOProtos.Rpc.ABCJJNCNEEP fjifdhjahjl = 3;</code>
     */
    public Builder setFjifdhjahjl(POGOProtos.Rpc.ABCJJNCNEEP value) {
      if (fjifdhjahjlBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fjifdhjahjl_ = value;
        onChanged();
      } else {
        fjifdhjahjlBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.ABCJJNCNEEP fjifdhjahjl = 3;</code>
     */
    public Builder setFjifdhjahjl(
        POGOProtos.Rpc.ABCJJNCNEEP.Builder builderForValue) {
      if (fjifdhjahjlBuilder_ == null) {
        fjifdhjahjl_ = builderForValue.build();
        onChanged();
      } else {
        fjifdhjahjlBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.ABCJJNCNEEP fjifdhjahjl = 3;</code>
     */
    public Builder mergeFjifdhjahjl(POGOProtos.Rpc.ABCJJNCNEEP value) {
      if (fjifdhjahjlBuilder_ == null) {
        if (fjifdhjahjl_ != null) {
          fjifdhjahjl_ =
            POGOProtos.Rpc.ABCJJNCNEEP.newBuilder(fjifdhjahjl_).mergeFrom(value).buildPartial();
        } else {
          fjifdhjahjl_ = value;
        }
        onChanged();
      } else {
        fjifdhjahjlBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.ABCJJNCNEEP fjifdhjahjl = 3;</code>
     */
    public Builder clearFjifdhjahjl() {
      if (fjifdhjahjlBuilder_ == null) {
        fjifdhjahjl_ = null;
        onChanged();
      } else {
        fjifdhjahjl_ = null;
        fjifdhjahjlBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.ABCJJNCNEEP fjifdhjahjl = 3;</code>
     */
    public POGOProtos.Rpc.ABCJJNCNEEP.Builder getFjifdhjahjlBuilder() {
      
      onChanged();
      return getFjifdhjahjlFieldBuilder().getBuilder();
    }
    /**
     * <code>.POGOProtos.Rpc.ABCJJNCNEEP fjifdhjahjl = 3;</code>
     */
    public POGOProtos.Rpc.ABCJJNCNEEPOrBuilder getFjifdhjahjlOrBuilder() {
      if (fjifdhjahjlBuilder_ != null) {
        return fjifdhjahjlBuilder_.getMessageOrBuilder();
      } else {
        return fjifdhjahjl_ == null ?
            POGOProtos.Rpc.ABCJJNCNEEP.getDefaultInstance() : fjifdhjahjl_;
      }
    }
    /**
     * <code>.POGOProtos.Rpc.ABCJJNCNEEP fjifdhjahjl = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.ABCJJNCNEEP, POGOProtos.Rpc.ABCJJNCNEEP.Builder, POGOProtos.Rpc.ABCJJNCNEEPOrBuilder> 
        getFjifdhjahjlFieldBuilder() {
      if (fjifdhjahjlBuilder_ == null) {
        fjifdhjahjlBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            POGOProtos.Rpc.ABCJJNCNEEP, POGOProtos.Rpc.ABCJJNCNEEP.Builder, POGOProtos.Rpc.ABCJJNCNEEPOrBuilder>(
                getFjifdhjahjl(),
                getParentForChildren(),
                isClean());
        fjifdhjahjl_ = null;
      }
      return fjifdhjahjlBuilder_;
    }

    private POGOProtos.Rpc.PlatformServerData oapiigkejkf_;
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.PlatformServerData, POGOProtos.Rpc.PlatformServerData.Builder, POGOProtos.Rpc.PlatformServerDataOrBuilder> oapiigkejkfBuilder_;
    /**
     * <code>.POGOProtos.Rpc.PlatformServerData oapiigkejkf = 1001;</code>
     * @return Whether the oapiigkejkf field is set.
     */
    public boolean hasOapiigkejkf() {
      return oapiigkejkfBuilder_ != null || oapiigkejkf_ != null;
    }
    /**
     * <code>.POGOProtos.Rpc.PlatformServerData oapiigkejkf = 1001;</code>
     * @return The oapiigkejkf.
     */
    public POGOProtos.Rpc.PlatformServerData getOapiigkejkf() {
      if (oapiigkejkfBuilder_ == null) {
        return oapiigkejkf_ == null ? POGOProtos.Rpc.PlatformServerData.getDefaultInstance() : oapiigkejkf_;
      } else {
        return oapiigkejkfBuilder_.getMessage();
      }
    }
    /**
     * <code>.POGOProtos.Rpc.PlatformServerData oapiigkejkf = 1001;</code>
     */
    public Builder setOapiigkejkf(POGOProtos.Rpc.PlatformServerData value) {
      if (oapiigkejkfBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        oapiigkejkf_ = value;
        onChanged();
      } else {
        oapiigkejkfBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.PlatformServerData oapiigkejkf = 1001;</code>
     */
    public Builder setOapiigkejkf(
        POGOProtos.Rpc.PlatformServerData.Builder builderForValue) {
      if (oapiigkejkfBuilder_ == null) {
        oapiigkejkf_ = builderForValue.build();
        onChanged();
      } else {
        oapiigkejkfBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.PlatformServerData oapiigkejkf = 1001;</code>
     */
    public Builder mergeOapiigkejkf(POGOProtos.Rpc.PlatformServerData value) {
      if (oapiigkejkfBuilder_ == null) {
        if (oapiigkejkf_ != null) {
          oapiigkejkf_ =
            POGOProtos.Rpc.PlatformServerData.newBuilder(oapiigkejkf_).mergeFrom(value).buildPartial();
        } else {
          oapiigkejkf_ = value;
        }
        onChanged();
      } else {
        oapiigkejkfBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.PlatformServerData oapiigkejkf = 1001;</code>
     */
    public Builder clearOapiigkejkf() {
      if (oapiigkejkfBuilder_ == null) {
        oapiigkejkf_ = null;
        onChanged();
      } else {
        oapiigkejkf_ = null;
        oapiigkejkfBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.PlatformServerData oapiigkejkf = 1001;</code>
     */
    public POGOProtos.Rpc.PlatformServerData.Builder getOapiigkejkfBuilder() {
      
      onChanged();
      return getOapiigkejkfFieldBuilder().getBuilder();
    }
    /**
     * <code>.POGOProtos.Rpc.PlatformServerData oapiigkejkf = 1001;</code>
     */
    public POGOProtos.Rpc.PlatformServerDataOrBuilder getOapiigkejkfOrBuilder() {
      if (oapiigkejkfBuilder_ != null) {
        return oapiigkejkfBuilder_.getMessageOrBuilder();
      } else {
        return oapiigkejkf_ == null ?
            POGOProtos.Rpc.PlatformServerData.getDefaultInstance() : oapiigkejkf_;
      }
    }
    /**
     * <code>.POGOProtos.Rpc.PlatformServerData oapiigkejkf = 1001;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.PlatformServerData, POGOProtos.Rpc.PlatformServerData.Builder, POGOProtos.Rpc.PlatformServerDataOrBuilder> 
        getOapiigkejkfFieldBuilder() {
      if (oapiigkejkfBuilder_ == null) {
        oapiigkejkfBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            POGOProtos.Rpc.PlatformServerData, POGOProtos.Rpc.PlatformServerData.Builder, POGOProtos.Rpc.PlatformServerDataOrBuilder>(
                getOapiigkejkf(),
                getParentForChildren(),
                isClean());
        oapiigkejkf_ = null;
      }
      return oapiigkejkfBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:POGOProtos.Rpc.BPGNLCIMNMM)
  }

  // @@protoc_insertion_point(class_scope:POGOProtos.Rpc.BPGNLCIMNMM)
  private static final POGOProtos.Rpc.BPGNLCIMNMM DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new POGOProtos.Rpc.BPGNLCIMNMM();
  }

  public static POGOProtos.Rpc.BPGNLCIMNMM getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BPGNLCIMNMM>
      PARSER = new com.google.protobuf.AbstractParser<BPGNLCIMNMM>() {
    @java.lang.Override
    public BPGNLCIMNMM parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BPGNLCIMNMM(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BPGNLCIMNMM> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BPGNLCIMNMM> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public POGOProtos.Rpc.BPGNLCIMNMM getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

