// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface DFEILPCLPIMOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.DFEILPCLPIM)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pjjnhmcllkp = 1;</code>
   * @return The pjjnhmcllkp.
   */
  java.lang.String getPjjnhmcllkp();
  /**
   * <code>string pjjnhmcllkp = 1;</code>
   * @return The bytes for pjjnhmcllkp.
   */
  com.google.protobuf.ByteString
      getPjjnhmcllkpBytes();

  /**
   * <code>int64 hpdjklhafgp = 2;</code>
   * @return The hpdjklhafgp.
   */
  long getHpdjklhafgp();

  /**
   * <code>bool kdkcccocbom = 3;</code>
   * @return The kdkcccocbom.
   */
  boolean getKdkcccocbom();
}
