// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface EHDBCCFKGCCOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.EHDBCCFKGCC)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.POGOProtos.Rpc.PokemonHomeIds fbkeklkhjfb = 1;</code>
   * @return The enum numeric value on the wire for fbkeklkhjfb.
   */
  int getFbkeklkhjfbValue();
  /**
   * <code>.POGOProtos.Rpc.PokemonHomeIds fbkeklkhjfb = 1;</code>
   * @return The fbkeklkhjfb.
   */
  POGOProtos.Rpc.PokemonHomeIds getFbkeklkhjfb();
}
