// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface FALKDEKNHNNOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.FALKDEKNHNN)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.POGOProtos.Rpc.FALKDEKNHNN.PJJFFKNDFAF jbflkcdndlp = 1;</code>
   * @return The enum numeric value on the wire for jbflkcdndlp.
   */
  int getJbflkcdndlpValue();
  /**
   * <code>.POGOProtos.Rpc.FALKDEKNHNN.PJJFFKNDFAF jbflkcdndlp = 1;</code>
   * @return The jbflkcdndlp.
   */
  POGOProtos.Rpc.FALKDEKNHNN.PJJFFKNDFAF getJbflkcdndlp();

  /**
   * <code>.POGOProtos.Rpc.GNEKCELDACL jkhebdnpedh = 2;</code>
   * @return Whether the jkhebdnpedh field is set.
   */
  boolean hasJkhebdnpedh();
  /**
   * <code>.POGOProtos.Rpc.GNEKCELDACL jkhebdnpedh = 2;</code>
   * @return The jkhebdnpedh.
   */
  POGOProtos.Rpc.GNEKCELDACL getJkhebdnpedh();
  /**
   * <code>.POGOProtos.Rpc.GNEKCELDACL jkhebdnpedh = 2;</code>
   */
  POGOProtos.Rpc.GNEKCELDACLOrBuilder getJkhebdnpedhOrBuilder();
}
