// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

/**
 * <pre>
 * ref: FLHBEFBLNBO
 * </pre>
 *
 * Protobuf type {@code POGOProtos.Rpc.FLHBEFBLNBO}
 */
public final class FLHBEFBLNBO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:POGOProtos.Rpc.FLHBEFBLNBO)
    FLHBEFBLNBOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FLHBEFBLNBO.newBuilder() to construct.
  private FLHBEFBLNBO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FLHBEFBLNBO() {
    ikcglhlgefo_ = java.util.Collections.emptyList();
    khbgnhalgbn_ = "";
    hjjajjmjlfd_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FLHBEFBLNBO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FLHBEFBLNBO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              ikcglhlgefo_ = new java.util.ArrayList<POGOProtos.Rpc.MNKEENFMLDC>();
              mutable_bitField0_ |= 0x00000001;
            }
            ikcglhlgefo_.add(
                input.readMessage(POGOProtos.Rpc.MNKEENFMLDC.parser(), extensionRegistry));
            break;
          }
          case 16: {

            nmhlioklddf_ = input.readInt32();
            break;
          }
          case 24: {

            eillmlikjal_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            khbgnhalgbn_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            hjjajjmjlfd_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        ikcglhlgefo_ = java.util.Collections.unmodifiableList(ikcglhlgefo_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_FLHBEFBLNBO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_FLHBEFBLNBO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            POGOProtos.Rpc.FLHBEFBLNBO.class, POGOProtos.Rpc.FLHBEFBLNBO.Builder.class);
  }

  public static final int IKCGLHLGEFO_FIELD_NUMBER = 1;
  private java.util.List<POGOProtos.Rpc.MNKEENFMLDC> ikcglhlgefo_;
  /**
   * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
   */
  @java.lang.Override
  public java.util.List<POGOProtos.Rpc.MNKEENFMLDC> getIkcglhlgefoList() {
    return ikcglhlgefo_;
  }
  /**
   * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends POGOProtos.Rpc.MNKEENFMLDCOrBuilder> 
      getIkcglhlgefoOrBuilderList() {
    return ikcglhlgefo_;
  }
  /**
   * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
   */
  @java.lang.Override
  public int getIkcglhlgefoCount() {
    return ikcglhlgefo_.size();
  }
  /**
   * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
   */
  @java.lang.Override
  public POGOProtos.Rpc.MNKEENFMLDC getIkcglhlgefo(int index) {
    return ikcglhlgefo_.get(index);
  }
  /**
   * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
   */
  @java.lang.Override
  public POGOProtos.Rpc.MNKEENFMLDCOrBuilder getIkcglhlgefoOrBuilder(
      int index) {
    return ikcglhlgefo_.get(index);
  }

  public static final int NMHLIOKLDDF_FIELD_NUMBER = 2;
  private int nmhlioklddf_;
  /**
   * <code>int32 nmhlioklddf = 2;</code>
   * @return The nmhlioklddf.
   */
  @java.lang.Override
  public int getNmhlioklddf() {
    return nmhlioklddf_;
  }

  public static final int EILLMLIKJAL_FIELD_NUMBER = 3;
  private int eillmlikjal_;
  /**
   * <code>int32 eillmlikjal = 3;</code>
   * @return The eillmlikjal.
   */
  @java.lang.Override
  public int getEillmlikjal() {
    return eillmlikjal_;
  }

  public static final int KHBGNHALGBN_FIELD_NUMBER = 4;
  private volatile java.lang.Object khbgnhalgbn_;
  /**
   * <code>string khbgnhalgbn = 4;</code>
   * @return The khbgnhalgbn.
   */
  @java.lang.Override
  public java.lang.String getKhbgnhalgbn() {
    java.lang.Object ref = khbgnhalgbn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      khbgnhalgbn_ = s;
      return s;
    }
  }
  /**
   * <code>string khbgnhalgbn = 4;</code>
   * @return The bytes for khbgnhalgbn.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKhbgnhalgbnBytes() {
    java.lang.Object ref = khbgnhalgbn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      khbgnhalgbn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HJJAJJMJLFD_FIELD_NUMBER = 5;
  private volatile java.lang.Object hjjajjmjlfd_;
  /**
   * <code>string hjjajjmjlfd = 5;</code>
   * @return The hjjajjmjlfd.
   */
  @java.lang.Override
  public java.lang.String getHjjajjmjlfd() {
    java.lang.Object ref = hjjajjmjlfd_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hjjajjmjlfd_ = s;
      return s;
    }
  }
  /**
   * <code>string hjjajjmjlfd = 5;</code>
   * @return The bytes for hjjajjmjlfd.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHjjajjmjlfdBytes() {
    java.lang.Object ref = hjjajjmjlfd_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hjjajjmjlfd_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < ikcglhlgefo_.size(); i++) {
      output.writeMessage(1, ikcglhlgefo_.get(i));
    }
    if (nmhlioklddf_ != 0) {
      output.writeInt32(2, nmhlioklddf_);
    }
    if (eillmlikjal_ != 0) {
      output.writeInt32(3, eillmlikjal_);
    }
    if (!getKhbgnhalgbnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, khbgnhalgbn_);
    }
    if (!getHjjajjmjlfdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, hjjajjmjlfd_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < ikcglhlgefo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, ikcglhlgefo_.get(i));
    }
    if (nmhlioklddf_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, nmhlioklddf_);
    }
    if (eillmlikjal_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, eillmlikjal_);
    }
    if (!getKhbgnhalgbnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, khbgnhalgbn_);
    }
    if (!getHjjajjmjlfdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, hjjajjmjlfd_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof POGOProtos.Rpc.FLHBEFBLNBO)) {
      return super.equals(obj);
    }
    POGOProtos.Rpc.FLHBEFBLNBO other = (POGOProtos.Rpc.FLHBEFBLNBO) obj;

    if (!getIkcglhlgefoList()
        .equals(other.getIkcglhlgefoList())) return false;
    if (getNmhlioklddf()
        != other.getNmhlioklddf()) return false;
    if (getEillmlikjal()
        != other.getEillmlikjal()) return false;
    if (!getKhbgnhalgbn()
        .equals(other.getKhbgnhalgbn())) return false;
    if (!getHjjajjmjlfd()
        .equals(other.getHjjajjmjlfd())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getIkcglhlgefoCount() > 0) {
      hash = (37 * hash) + IKCGLHLGEFO_FIELD_NUMBER;
      hash = (53 * hash) + getIkcglhlgefoList().hashCode();
    }
    hash = (37 * hash) + NMHLIOKLDDF_FIELD_NUMBER;
    hash = (53 * hash) + getNmhlioklddf();
    hash = (37 * hash) + EILLMLIKJAL_FIELD_NUMBER;
    hash = (53 * hash) + getEillmlikjal();
    hash = (37 * hash) + KHBGNHALGBN_FIELD_NUMBER;
    hash = (53 * hash) + getKhbgnhalgbn().hashCode();
    hash = (37 * hash) + HJJAJJMJLFD_FIELD_NUMBER;
    hash = (53 * hash) + getHjjajjmjlfd().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static POGOProtos.Rpc.FLHBEFBLNBO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.FLHBEFBLNBO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.FLHBEFBLNBO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.FLHBEFBLNBO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.FLHBEFBLNBO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.FLHBEFBLNBO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.FLHBEFBLNBO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.FLHBEFBLNBO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.FLHBEFBLNBO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.FLHBEFBLNBO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.FLHBEFBLNBO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.FLHBEFBLNBO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(POGOProtos.Rpc.FLHBEFBLNBO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ref: FLHBEFBLNBO
   * </pre>
   *
   * Protobuf type {@code POGOProtos.Rpc.FLHBEFBLNBO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:POGOProtos.Rpc.FLHBEFBLNBO)
      POGOProtos.Rpc.FLHBEFBLNBOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_FLHBEFBLNBO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_FLHBEFBLNBO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Rpc.FLHBEFBLNBO.class, POGOProtos.Rpc.FLHBEFBLNBO.Builder.class);
    }

    // Construct using POGOProtos.Rpc.FLHBEFBLNBO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getIkcglhlgefoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (ikcglhlgefoBuilder_ == null) {
        ikcglhlgefo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        ikcglhlgefoBuilder_.clear();
      }
      nmhlioklddf_ = 0;

      eillmlikjal_ = 0;

      khbgnhalgbn_ = "";

      hjjajjmjlfd_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_FLHBEFBLNBO_descriptor;
    }

    @java.lang.Override
    public POGOProtos.Rpc.FLHBEFBLNBO getDefaultInstanceForType() {
      return POGOProtos.Rpc.FLHBEFBLNBO.getDefaultInstance();
    }

    @java.lang.Override
    public POGOProtos.Rpc.FLHBEFBLNBO build() {
      POGOProtos.Rpc.FLHBEFBLNBO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public POGOProtos.Rpc.FLHBEFBLNBO buildPartial() {
      POGOProtos.Rpc.FLHBEFBLNBO result = new POGOProtos.Rpc.FLHBEFBLNBO(this);
      int from_bitField0_ = bitField0_;
      if (ikcglhlgefoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          ikcglhlgefo_ = java.util.Collections.unmodifiableList(ikcglhlgefo_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ikcglhlgefo_ = ikcglhlgefo_;
      } else {
        result.ikcglhlgefo_ = ikcglhlgefoBuilder_.build();
      }
      result.nmhlioklddf_ = nmhlioklddf_;
      result.eillmlikjal_ = eillmlikjal_;
      result.khbgnhalgbn_ = khbgnhalgbn_;
      result.hjjajjmjlfd_ = hjjajjmjlfd_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof POGOProtos.Rpc.FLHBEFBLNBO) {
        return mergeFrom((POGOProtos.Rpc.FLHBEFBLNBO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(POGOProtos.Rpc.FLHBEFBLNBO other) {
      if (other == POGOProtos.Rpc.FLHBEFBLNBO.getDefaultInstance()) return this;
      if (ikcglhlgefoBuilder_ == null) {
        if (!other.ikcglhlgefo_.isEmpty()) {
          if (ikcglhlgefo_.isEmpty()) {
            ikcglhlgefo_ = other.ikcglhlgefo_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIkcglhlgefoIsMutable();
            ikcglhlgefo_.addAll(other.ikcglhlgefo_);
          }
          onChanged();
        }
      } else {
        if (!other.ikcglhlgefo_.isEmpty()) {
          if (ikcglhlgefoBuilder_.isEmpty()) {
            ikcglhlgefoBuilder_.dispose();
            ikcglhlgefoBuilder_ = null;
            ikcglhlgefo_ = other.ikcglhlgefo_;
            bitField0_ = (bitField0_ & ~0x00000001);
            ikcglhlgefoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getIkcglhlgefoFieldBuilder() : null;
          } else {
            ikcglhlgefoBuilder_.addAllMessages(other.ikcglhlgefo_);
          }
        }
      }
      if (other.getNmhlioklddf() != 0) {
        setNmhlioklddf(other.getNmhlioklddf());
      }
      if (other.getEillmlikjal() != 0) {
        setEillmlikjal(other.getEillmlikjal());
      }
      if (!other.getKhbgnhalgbn().isEmpty()) {
        khbgnhalgbn_ = other.khbgnhalgbn_;
        onChanged();
      }
      if (!other.getHjjajjmjlfd().isEmpty()) {
        hjjajjmjlfd_ = other.hjjajjmjlfd_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      POGOProtos.Rpc.FLHBEFBLNBO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (POGOProtos.Rpc.FLHBEFBLNBO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<POGOProtos.Rpc.MNKEENFMLDC> ikcglhlgefo_ =
      java.util.Collections.emptyList();
    private void ensureIkcglhlgefoIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        ikcglhlgefo_ = new java.util.ArrayList<POGOProtos.Rpc.MNKEENFMLDC>(ikcglhlgefo_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        POGOProtos.Rpc.MNKEENFMLDC, POGOProtos.Rpc.MNKEENFMLDC.Builder, POGOProtos.Rpc.MNKEENFMLDCOrBuilder> ikcglhlgefoBuilder_;

    /**
     * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
     */
    public java.util.List<POGOProtos.Rpc.MNKEENFMLDC> getIkcglhlgefoList() {
      if (ikcglhlgefoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ikcglhlgefo_);
      } else {
        return ikcglhlgefoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
     */
    public int getIkcglhlgefoCount() {
      if (ikcglhlgefoBuilder_ == null) {
        return ikcglhlgefo_.size();
      } else {
        return ikcglhlgefoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
     */
    public POGOProtos.Rpc.MNKEENFMLDC getIkcglhlgefo(int index) {
      if (ikcglhlgefoBuilder_ == null) {
        return ikcglhlgefo_.get(index);
      } else {
        return ikcglhlgefoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
     */
    public Builder setIkcglhlgefo(
        int index, POGOProtos.Rpc.MNKEENFMLDC value) {
      if (ikcglhlgefoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIkcglhlgefoIsMutable();
        ikcglhlgefo_.set(index, value);
        onChanged();
      } else {
        ikcglhlgefoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
     */
    public Builder setIkcglhlgefo(
        int index, POGOProtos.Rpc.MNKEENFMLDC.Builder builderForValue) {
      if (ikcglhlgefoBuilder_ == null) {
        ensureIkcglhlgefoIsMutable();
        ikcglhlgefo_.set(index, builderForValue.build());
        onChanged();
      } else {
        ikcglhlgefoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
     */
    public Builder addIkcglhlgefo(POGOProtos.Rpc.MNKEENFMLDC value) {
      if (ikcglhlgefoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIkcglhlgefoIsMutable();
        ikcglhlgefo_.add(value);
        onChanged();
      } else {
        ikcglhlgefoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
     */
    public Builder addIkcglhlgefo(
        int index, POGOProtos.Rpc.MNKEENFMLDC value) {
      if (ikcglhlgefoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIkcglhlgefoIsMutable();
        ikcglhlgefo_.add(index, value);
        onChanged();
      } else {
        ikcglhlgefoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
     */
    public Builder addIkcglhlgefo(
        POGOProtos.Rpc.MNKEENFMLDC.Builder builderForValue) {
      if (ikcglhlgefoBuilder_ == null) {
        ensureIkcglhlgefoIsMutable();
        ikcglhlgefo_.add(builderForValue.build());
        onChanged();
      } else {
        ikcglhlgefoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
     */
    public Builder addIkcglhlgefo(
        int index, POGOProtos.Rpc.MNKEENFMLDC.Builder builderForValue) {
      if (ikcglhlgefoBuilder_ == null) {
        ensureIkcglhlgefoIsMutable();
        ikcglhlgefo_.add(index, builderForValue.build());
        onChanged();
      } else {
        ikcglhlgefoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
     */
    public Builder addAllIkcglhlgefo(
        java.lang.Iterable<? extends POGOProtos.Rpc.MNKEENFMLDC> values) {
      if (ikcglhlgefoBuilder_ == null) {
        ensureIkcglhlgefoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ikcglhlgefo_);
        onChanged();
      } else {
        ikcglhlgefoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
     */
    public Builder clearIkcglhlgefo() {
      if (ikcglhlgefoBuilder_ == null) {
        ikcglhlgefo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        ikcglhlgefoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
     */
    public Builder removeIkcglhlgefo(int index) {
      if (ikcglhlgefoBuilder_ == null) {
        ensureIkcglhlgefoIsMutable();
        ikcglhlgefo_.remove(index);
        onChanged();
      } else {
        ikcglhlgefoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
     */
    public POGOProtos.Rpc.MNKEENFMLDC.Builder getIkcglhlgefoBuilder(
        int index) {
      return getIkcglhlgefoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
     */
    public POGOProtos.Rpc.MNKEENFMLDCOrBuilder getIkcglhlgefoOrBuilder(
        int index) {
      if (ikcglhlgefoBuilder_ == null) {
        return ikcglhlgefo_.get(index);  } else {
        return ikcglhlgefoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
     */
    public java.util.List<? extends POGOProtos.Rpc.MNKEENFMLDCOrBuilder> 
         getIkcglhlgefoOrBuilderList() {
      if (ikcglhlgefoBuilder_ != null) {
        return ikcglhlgefoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ikcglhlgefo_);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
     */
    public POGOProtos.Rpc.MNKEENFMLDC.Builder addIkcglhlgefoBuilder() {
      return getIkcglhlgefoFieldBuilder().addBuilder(
          POGOProtos.Rpc.MNKEENFMLDC.getDefaultInstance());
    }
    /**
     * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
     */
    public POGOProtos.Rpc.MNKEENFMLDC.Builder addIkcglhlgefoBuilder(
        int index) {
      return getIkcglhlgefoFieldBuilder().addBuilder(
          index, POGOProtos.Rpc.MNKEENFMLDC.getDefaultInstance());
    }
    /**
     * <code>repeated .POGOProtos.Rpc.MNKEENFMLDC ikcglhlgefo = 1;</code>
     */
    public java.util.List<POGOProtos.Rpc.MNKEENFMLDC.Builder> 
         getIkcglhlgefoBuilderList() {
      return getIkcglhlgefoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        POGOProtos.Rpc.MNKEENFMLDC, POGOProtos.Rpc.MNKEENFMLDC.Builder, POGOProtos.Rpc.MNKEENFMLDCOrBuilder> 
        getIkcglhlgefoFieldBuilder() {
      if (ikcglhlgefoBuilder_ == null) {
        ikcglhlgefoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            POGOProtos.Rpc.MNKEENFMLDC, POGOProtos.Rpc.MNKEENFMLDC.Builder, POGOProtos.Rpc.MNKEENFMLDCOrBuilder>(
                ikcglhlgefo_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        ikcglhlgefo_ = null;
      }
      return ikcglhlgefoBuilder_;
    }

    private int nmhlioklddf_ ;
    /**
     * <code>int32 nmhlioklddf = 2;</code>
     * @return The nmhlioklddf.
     */
    @java.lang.Override
    public int getNmhlioklddf() {
      return nmhlioklddf_;
    }
    /**
     * <code>int32 nmhlioklddf = 2;</code>
     * @param value The nmhlioklddf to set.
     * @return This builder for chaining.
     */
    public Builder setNmhlioklddf(int value) {
      
      nmhlioklddf_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 nmhlioklddf = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNmhlioklddf() {
      
      nmhlioklddf_ = 0;
      onChanged();
      return this;
    }

    private int eillmlikjal_ ;
    /**
     * <code>int32 eillmlikjal = 3;</code>
     * @return The eillmlikjal.
     */
    @java.lang.Override
    public int getEillmlikjal() {
      return eillmlikjal_;
    }
    /**
     * <code>int32 eillmlikjal = 3;</code>
     * @param value The eillmlikjal to set.
     * @return This builder for chaining.
     */
    public Builder setEillmlikjal(int value) {
      
      eillmlikjal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 eillmlikjal = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEillmlikjal() {
      
      eillmlikjal_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object khbgnhalgbn_ = "";
    /**
     * <code>string khbgnhalgbn = 4;</code>
     * @return The khbgnhalgbn.
     */
    public java.lang.String getKhbgnhalgbn() {
      java.lang.Object ref = khbgnhalgbn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        khbgnhalgbn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string khbgnhalgbn = 4;</code>
     * @return The bytes for khbgnhalgbn.
     */
    public com.google.protobuf.ByteString
        getKhbgnhalgbnBytes() {
      java.lang.Object ref = khbgnhalgbn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        khbgnhalgbn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string khbgnhalgbn = 4;</code>
     * @param value The khbgnhalgbn to set.
     * @return This builder for chaining.
     */
    public Builder setKhbgnhalgbn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      khbgnhalgbn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string khbgnhalgbn = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearKhbgnhalgbn() {
      
      khbgnhalgbn_ = getDefaultInstance().getKhbgnhalgbn();
      onChanged();
      return this;
    }
    /**
     * <code>string khbgnhalgbn = 4;</code>
     * @param value The bytes for khbgnhalgbn to set.
     * @return This builder for chaining.
     */
    public Builder setKhbgnhalgbnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      khbgnhalgbn_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object hjjajjmjlfd_ = "";
    /**
     * <code>string hjjajjmjlfd = 5;</code>
     * @return The hjjajjmjlfd.
     */
    public java.lang.String getHjjajjmjlfd() {
      java.lang.Object ref = hjjajjmjlfd_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hjjajjmjlfd_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hjjajjmjlfd = 5;</code>
     * @return The bytes for hjjajjmjlfd.
     */
    public com.google.protobuf.ByteString
        getHjjajjmjlfdBytes() {
      java.lang.Object ref = hjjajjmjlfd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hjjajjmjlfd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hjjajjmjlfd = 5;</code>
     * @param value The hjjajjmjlfd to set.
     * @return This builder for chaining.
     */
    public Builder setHjjajjmjlfd(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hjjajjmjlfd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string hjjajjmjlfd = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearHjjajjmjlfd() {
      
      hjjajjmjlfd_ = getDefaultInstance().getHjjajjmjlfd();
      onChanged();
      return this;
    }
    /**
     * <code>string hjjajjmjlfd = 5;</code>
     * @param value The bytes for hjjajjmjlfd to set.
     * @return This builder for chaining.
     */
    public Builder setHjjajjmjlfdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hjjajjmjlfd_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:POGOProtos.Rpc.FLHBEFBLNBO)
  }

  // @@protoc_insertion_point(class_scope:POGOProtos.Rpc.FLHBEFBLNBO)
  private static final POGOProtos.Rpc.FLHBEFBLNBO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new POGOProtos.Rpc.FLHBEFBLNBO();
  }

  public static POGOProtos.Rpc.FLHBEFBLNBO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FLHBEFBLNBO>
      PARSER = new com.google.protobuf.AbstractParser<FLHBEFBLNBO>() {
    @java.lang.Override
    public FLHBEFBLNBO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FLHBEFBLNBO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FLHBEFBLNBO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FLHBEFBLNBO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public POGOProtos.Rpc.FLHBEFBLNBO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

