// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface FNDMBFLIIEMOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.FNDMBFLIIEM)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.POGOProtos.Rpc.DDNJCDIBALG aaligkbalda = 1;</code>
   * @return Whether the aaligkbalda field is set.
   */
  boolean hasAaligkbalda();
  /**
   * <code>.POGOProtos.Rpc.DDNJCDIBALG aaligkbalda = 1;</code>
   * @return The aaligkbalda.
   */
  POGOProtos.Rpc.DDNJCDIBALG getAaligkbalda();
  /**
   * <code>.POGOProtos.Rpc.DDNJCDIBALG aaligkbalda = 1;</code>
   */
  POGOProtos.Rpc.DDNJCDIBALGOrBuilder getAaligkbaldaOrBuilder();

  /**
   * <code>.POGOProtos.Rpc.FLEJIPPCOHB dfbkbddgjmh = 2;</code>
   * @return Whether the dfbkbddgjmh field is set.
   */
  boolean hasDfbkbddgjmh();
  /**
   * <code>.POGOProtos.Rpc.FLEJIPPCOHB dfbkbddgjmh = 2;</code>
   * @return The dfbkbddgjmh.
   */
  POGOProtos.Rpc.FLEJIPPCOHB getDfbkbddgjmh();
  /**
   * <code>.POGOProtos.Rpc.FLEJIPPCOHB dfbkbddgjmh = 2;</code>
   */
  POGOProtos.Rpc.FLEJIPPCOHBOrBuilder getDfbkbddgjmhOrBuilder();

  /**
   * <code>repeated .POGOProtos.Rpc.DDNJCDIBALG kjnoagohjjc = 3;</code>
   */
  java.util.List<POGOProtos.Rpc.DDNJCDIBALG> 
      getKjnoagohjjcList();
  /**
   * <code>repeated .POGOProtos.Rpc.DDNJCDIBALG kjnoagohjjc = 3;</code>
   */
  POGOProtos.Rpc.DDNJCDIBALG getKjnoagohjjc(int index);
  /**
   * <code>repeated .POGOProtos.Rpc.DDNJCDIBALG kjnoagohjjc = 3;</code>
   */
  int getKjnoagohjjcCount();
  /**
   * <code>repeated .POGOProtos.Rpc.DDNJCDIBALG kjnoagohjjc = 3;</code>
   */
  java.util.List<? extends POGOProtos.Rpc.DDNJCDIBALGOrBuilder> 
      getKjnoagohjjcOrBuilderList();
  /**
   * <code>repeated .POGOProtos.Rpc.DDNJCDIBALG kjnoagohjjc = 3;</code>
   */
  POGOProtos.Rpc.DDNJCDIBALGOrBuilder getKjnoagohjjcOrBuilder(
      int index);

  /**
   * <code>repeated .POGOProtos.Rpc.DDNJCDIBALG filekafoegj = 4;</code>
   */
  java.util.List<POGOProtos.Rpc.DDNJCDIBALG> 
      getFilekafoegjList();
  /**
   * <code>repeated .POGOProtos.Rpc.DDNJCDIBALG filekafoegj = 4;</code>
   */
  POGOProtos.Rpc.DDNJCDIBALG getFilekafoegj(int index);
  /**
   * <code>repeated .POGOProtos.Rpc.DDNJCDIBALG filekafoegj = 4;</code>
   */
  int getFilekafoegjCount();
  /**
   * <code>repeated .POGOProtos.Rpc.DDNJCDIBALG filekafoegj = 4;</code>
   */
  java.util.List<? extends POGOProtos.Rpc.DDNJCDIBALGOrBuilder> 
      getFilekafoegjOrBuilderList();
  /**
   * <code>repeated .POGOProtos.Rpc.DDNJCDIBALG filekafoegj = 4;</code>
   */
  POGOProtos.Rpc.DDNJCDIBALGOrBuilder getFilekafoegjOrBuilder(
      int index);

  /**
   * <code>repeated .POGOProtos.Rpc.AKOMDAPOLNB onldopnpema = 5;</code>
   */
  java.util.List<POGOProtos.Rpc.AKOMDAPOLNB> 
      getOnldopnpemaList();
  /**
   * <code>repeated .POGOProtos.Rpc.AKOMDAPOLNB onldopnpema = 5;</code>
   */
  POGOProtos.Rpc.AKOMDAPOLNB getOnldopnpema(int index);
  /**
   * <code>repeated .POGOProtos.Rpc.AKOMDAPOLNB onldopnpema = 5;</code>
   */
  int getOnldopnpemaCount();
  /**
   * <code>repeated .POGOProtos.Rpc.AKOMDAPOLNB onldopnpema = 5;</code>
   */
  java.util.List<? extends POGOProtos.Rpc.AKOMDAPOLNBOrBuilder> 
      getOnldopnpemaOrBuilderList();
  /**
   * <code>repeated .POGOProtos.Rpc.AKOMDAPOLNB onldopnpema = 5;</code>
   */
  POGOProtos.Rpc.AKOMDAPOLNBOrBuilder getOnldopnpemaOrBuilder(
      int index);

  /**
   * <code>int32 ckabhdmampc = 6;</code>
   * @return The ckabhdmampc.
   */
  int getCkabhdmampc();

  /**
   * <code>bool njkhpilhklp = 7;</code>
   * @return The njkhpilhklp.
   */
  boolean getNjkhpilhklp();

  /**
   * <code>bool ihdcmjeobdn = 8;</code>
   * @return The ihdcmjeobdn.
   */
  boolean getIhdcmjeobdn();

  /**
   * <code>.POGOProtos.Rpc.NEAJHKJEOAP idchebbhcji = 9;</code>
   * @return The enum numeric value on the wire for idchebbhcji.
   */
  int getIdchebbhcjiValue();
  /**
   * <code>.POGOProtos.Rpc.NEAJHKJEOAP idchebbhcji = 9;</code>
   * @return The idchebbhcji.
   */
  POGOProtos.Rpc.NEAJHKJEOAP getIdchebbhcji();

  /**
   * <code>repeated string kbkjjefcpic = 10;</code>
   * @return A list containing the kbkjjefcpic.
   */
  java.util.List<java.lang.String>
      getKbkjjefcpicList();
  /**
   * <code>repeated string kbkjjefcpic = 10;</code>
   * @return The count of kbkjjefcpic.
   */
  int getKbkjjefcpicCount();
  /**
   * <code>repeated string kbkjjefcpic = 10;</code>
   * @param index The index of the element to return.
   * @return The kbkjjefcpic at the given index.
   */
  java.lang.String getKbkjjefcpic(int index);
  /**
   * <code>repeated string kbkjjefcpic = 10;</code>
   * @param index The index of the value to return.
   * @return The bytes of the kbkjjefcpic at the given index.
   */
  com.google.protobuf.ByteString
      getKbkjjefcpicBytes(int index);

  /**
   * <code>bool oegddaiccep = 11;</code>
   * @return The oegddaiccep.
   */
  boolean getOegddaiccep();

  /**
   * <code>bool nejfmpocdba = 12;</code>
   * @return The nejfmpocdba.
   */
  boolean getNejfmpocdba();

  /**
   * <code>bool hpchnhkdmcf = 13;</code>
   * @return The hpchnhkdmcf.
   */
  boolean getHpchnhkdmcf();

  /**
   * <code>int64 gmngcmcglnp = 14;</code>
   * @return The gmngcmcglnp.
   */
  long getGmngcmcglnp();
}
