// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface HABFFNDINAMOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.HABFFNDINAM)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.POGOProtos.Rpc.HABFFNDINAM.LKKPNBEBOMD kmieohojnij = 1;</code>
   * @return The enum numeric value on the wire for kmieohojnij.
   */
  int getKmieohojnijValue();
  /**
   * <code>.POGOProtos.Rpc.HABFFNDINAM.LKKPNBEBOMD kmieohojnij = 1;</code>
   * @return The kmieohojnij.
   */
  POGOProtos.Rpc.HABFFNDINAM.LKKPNBEBOMD getKmieohojnij();

  /**
   * <code>.POGOProtos.Rpc.KIKHLAJCKFP klnafjahpce = 2;</code>
   * @return Whether the klnafjahpce field is set.
   */
  boolean hasKlnafjahpce();
  /**
   * <code>.POGOProtos.Rpc.KIKHLAJCKFP klnafjahpce = 2;</code>
   * @return The klnafjahpce.
   */
  POGOProtos.Rpc.KIKHLAJCKFP getKlnafjahpce();
  /**
   * <code>.POGOProtos.Rpc.KIKHLAJCKFP klnafjahpce = 2;</code>
   */
  POGOProtos.Rpc.KIKHLAJCKFPOrBuilder getKlnafjahpceOrBuilder();

  /**
   * <code>.POGOProtos.Rpc.GOCBJFKKCCF llfflapmphl = 3;</code>
   * @return The enum numeric value on the wire for llfflapmphl.
   */
  int getLlfflapmphlValue();
  /**
   * <code>.POGOProtos.Rpc.GOCBJFKKCCF llfflapmphl = 3;</code>
   * @return The llfflapmphl.
   */
  POGOProtos.Rpc.GOCBJFKKCCF getLlfflapmphl();
}
