// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

/**
 * Protobuf type {@code POGOProtos.Rpc.IncomingFriendInviteDisplayProto}
 */
public  final class IncomingFriendInviteDisplayProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:POGOProtos.Rpc.IncomingFriendInviteDisplayProto)
    IncomingFriendInviteDisplayProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IncomingFriendInviteDisplayProto.newBuilder() to construct.
  private IncomingFriendInviteDisplayProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IncomingFriendInviteDisplayProto() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IncomingFriendInviteDisplayProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private IncomingFriendInviteDisplayProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            POGOProtos.Rpc.IncomingFriendInviteProto.Builder subBuilder = null;
            if (invite_ != null) {
              subBuilder = invite_.toBuilder();
            }
            invite_ = input.readMessage(POGOProtos.Rpc.IncomingFriendInviteProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(invite_);
              invite_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            POGOProtos.Rpc.PlayerSummaryProto.Builder subBuilder = null;
            if (player_ != null) {
              subBuilder = player_.toBuilder();
            }
            player_ = input.readMessage(POGOProtos.Rpc.PlayerSummaryProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(player_);
              player_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_IncomingFriendInviteDisplayProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_IncomingFriendInviteDisplayProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            POGOProtos.Rpc.IncomingFriendInviteDisplayProto.class, POGOProtos.Rpc.IncomingFriendInviteDisplayProto.Builder.class);
  }

  public static final int INVITE_FIELD_NUMBER = 1;
  private POGOProtos.Rpc.IncomingFriendInviteProto invite_;
  /**
   * <code>.POGOProtos.Rpc.IncomingFriendInviteProto invite = 1;</code>
   * @return Whether the invite field is set.
   */
  public boolean hasInvite() {
    return invite_ != null;
  }
  /**
   * <code>.POGOProtos.Rpc.IncomingFriendInviteProto invite = 1;</code>
   * @return The invite.
   */
  public POGOProtos.Rpc.IncomingFriendInviteProto getInvite() {
    return invite_ == null ? POGOProtos.Rpc.IncomingFriendInviteProto.getDefaultInstance() : invite_;
  }
  /**
   * <code>.POGOProtos.Rpc.IncomingFriendInviteProto invite = 1;</code>
   */
  public POGOProtos.Rpc.IncomingFriendInviteProtoOrBuilder getInviteOrBuilder() {
    return getInvite();
  }

  public static final int PLAYER_FIELD_NUMBER = 2;
  private POGOProtos.Rpc.PlayerSummaryProto player_;
  /**
   * <code>.POGOProtos.Rpc.PlayerSummaryProto player = 2;</code>
   * @return Whether the player field is set.
   */
  public boolean hasPlayer() {
    return player_ != null;
  }
  /**
   * <code>.POGOProtos.Rpc.PlayerSummaryProto player = 2;</code>
   * @return The player.
   */
  public POGOProtos.Rpc.PlayerSummaryProto getPlayer() {
    return player_ == null ? POGOProtos.Rpc.PlayerSummaryProto.getDefaultInstance() : player_;
  }
  /**
   * <code>.POGOProtos.Rpc.PlayerSummaryProto player = 2;</code>
   */
  public POGOProtos.Rpc.PlayerSummaryProtoOrBuilder getPlayerOrBuilder() {
    return getPlayer();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (invite_ != null) {
      output.writeMessage(1, getInvite());
    }
    if (player_ != null) {
      output.writeMessage(2, getPlayer());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (invite_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getInvite());
    }
    if (player_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPlayer());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof POGOProtos.Rpc.IncomingFriendInviteDisplayProto)) {
      return super.equals(obj);
    }
    POGOProtos.Rpc.IncomingFriendInviteDisplayProto other = (POGOProtos.Rpc.IncomingFriendInviteDisplayProto) obj;

    if (hasInvite() != other.hasInvite()) return false;
    if (hasInvite()) {
      if (!getInvite()
          .equals(other.getInvite())) return false;
    }
    if (hasPlayer() != other.hasPlayer()) return false;
    if (hasPlayer()) {
      if (!getPlayer()
          .equals(other.getPlayer())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasInvite()) {
      hash = (37 * hash) + INVITE_FIELD_NUMBER;
      hash = (53 * hash) + getInvite().hashCode();
    }
    if (hasPlayer()) {
      hash = (37 * hash) + PLAYER_FIELD_NUMBER;
      hash = (53 * hash) + getPlayer().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static POGOProtos.Rpc.IncomingFriendInviteDisplayProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.IncomingFriendInviteDisplayProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.IncomingFriendInviteDisplayProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.IncomingFriendInviteDisplayProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.IncomingFriendInviteDisplayProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.IncomingFriendInviteDisplayProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.IncomingFriendInviteDisplayProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.IncomingFriendInviteDisplayProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.IncomingFriendInviteDisplayProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.IncomingFriendInviteDisplayProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.IncomingFriendInviteDisplayProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.IncomingFriendInviteDisplayProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(POGOProtos.Rpc.IncomingFriendInviteDisplayProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code POGOProtos.Rpc.IncomingFriendInviteDisplayProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:POGOProtos.Rpc.IncomingFriendInviteDisplayProto)
      POGOProtos.Rpc.IncomingFriendInviteDisplayProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_IncomingFriendInviteDisplayProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_IncomingFriendInviteDisplayProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Rpc.IncomingFriendInviteDisplayProto.class, POGOProtos.Rpc.IncomingFriendInviteDisplayProto.Builder.class);
    }

    // Construct using POGOProtos.Rpc.IncomingFriendInviteDisplayProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (inviteBuilder_ == null) {
        invite_ = null;
      } else {
        invite_ = null;
        inviteBuilder_ = null;
      }
      if (playerBuilder_ == null) {
        player_ = null;
      } else {
        player_ = null;
        playerBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_IncomingFriendInviteDisplayProto_descriptor;
    }

    @java.lang.Override
    public POGOProtos.Rpc.IncomingFriendInviteDisplayProto getDefaultInstanceForType() {
      return POGOProtos.Rpc.IncomingFriendInviteDisplayProto.getDefaultInstance();
    }

    @java.lang.Override
    public POGOProtos.Rpc.IncomingFriendInviteDisplayProto build() {
      POGOProtos.Rpc.IncomingFriendInviteDisplayProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public POGOProtos.Rpc.IncomingFriendInviteDisplayProto buildPartial() {
      POGOProtos.Rpc.IncomingFriendInviteDisplayProto result = new POGOProtos.Rpc.IncomingFriendInviteDisplayProto(this);
      if (inviteBuilder_ == null) {
        result.invite_ = invite_;
      } else {
        result.invite_ = inviteBuilder_.build();
      }
      if (playerBuilder_ == null) {
        result.player_ = player_;
      } else {
        result.player_ = playerBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof POGOProtos.Rpc.IncomingFriendInviteDisplayProto) {
        return mergeFrom((POGOProtos.Rpc.IncomingFriendInviteDisplayProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(POGOProtos.Rpc.IncomingFriendInviteDisplayProto other) {
      if (other == POGOProtos.Rpc.IncomingFriendInviteDisplayProto.getDefaultInstance()) return this;
      if (other.hasInvite()) {
        mergeInvite(other.getInvite());
      }
      if (other.hasPlayer()) {
        mergePlayer(other.getPlayer());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      POGOProtos.Rpc.IncomingFriendInviteDisplayProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (POGOProtos.Rpc.IncomingFriendInviteDisplayProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private POGOProtos.Rpc.IncomingFriendInviteProto invite_;
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.IncomingFriendInviteProto, POGOProtos.Rpc.IncomingFriendInviteProto.Builder, POGOProtos.Rpc.IncomingFriendInviteProtoOrBuilder> inviteBuilder_;
    /**
     * <code>.POGOProtos.Rpc.IncomingFriendInviteProto invite = 1;</code>
     * @return Whether the invite field is set.
     */
    public boolean hasInvite() {
      return inviteBuilder_ != null || invite_ != null;
    }
    /**
     * <code>.POGOProtos.Rpc.IncomingFriendInviteProto invite = 1;</code>
     * @return The invite.
     */
    public POGOProtos.Rpc.IncomingFriendInviteProto getInvite() {
      if (inviteBuilder_ == null) {
        return invite_ == null ? POGOProtos.Rpc.IncomingFriendInviteProto.getDefaultInstance() : invite_;
      } else {
        return inviteBuilder_.getMessage();
      }
    }
    /**
     * <code>.POGOProtos.Rpc.IncomingFriendInviteProto invite = 1;</code>
     */
    public Builder setInvite(POGOProtos.Rpc.IncomingFriendInviteProto value) {
      if (inviteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        invite_ = value;
        onChanged();
      } else {
        inviteBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.IncomingFriendInviteProto invite = 1;</code>
     */
    public Builder setInvite(
        POGOProtos.Rpc.IncomingFriendInviteProto.Builder builderForValue) {
      if (inviteBuilder_ == null) {
        invite_ = builderForValue.build();
        onChanged();
      } else {
        inviteBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.IncomingFriendInviteProto invite = 1;</code>
     */
    public Builder mergeInvite(POGOProtos.Rpc.IncomingFriendInviteProto value) {
      if (inviteBuilder_ == null) {
        if (invite_ != null) {
          invite_ =
            POGOProtos.Rpc.IncomingFriendInviteProto.newBuilder(invite_).mergeFrom(value).buildPartial();
        } else {
          invite_ = value;
        }
        onChanged();
      } else {
        inviteBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.IncomingFriendInviteProto invite = 1;</code>
     */
    public Builder clearInvite() {
      if (inviteBuilder_ == null) {
        invite_ = null;
        onChanged();
      } else {
        invite_ = null;
        inviteBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.IncomingFriendInviteProto invite = 1;</code>
     */
    public POGOProtos.Rpc.IncomingFriendInviteProto.Builder getInviteBuilder() {
      
      onChanged();
      return getInviteFieldBuilder().getBuilder();
    }
    /**
     * <code>.POGOProtos.Rpc.IncomingFriendInviteProto invite = 1;</code>
     */
    public POGOProtos.Rpc.IncomingFriendInviteProtoOrBuilder getInviteOrBuilder() {
      if (inviteBuilder_ != null) {
        return inviteBuilder_.getMessageOrBuilder();
      } else {
        return invite_ == null ?
            POGOProtos.Rpc.IncomingFriendInviteProto.getDefaultInstance() : invite_;
      }
    }
    /**
     * <code>.POGOProtos.Rpc.IncomingFriendInviteProto invite = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.IncomingFriendInviteProto, POGOProtos.Rpc.IncomingFriendInviteProto.Builder, POGOProtos.Rpc.IncomingFriendInviteProtoOrBuilder> 
        getInviteFieldBuilder() {
      if (inviteBuilder_ == null) {
        inviteBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            POGOProtos.Rpc.IncomingFriendInviteProto, POGOProtos.Rpc.IncomingFriendInviteProto.Builder, POGOProtos.Rpc.IncomingFriendInviteProtoOrBuilder>(
                getInvite(),
                getParentForChildren(),
                isClean());
        invite_ = null;
      }
      return inviteBuilder_;
    }

    private POGOProtos.Rpc.PlayerSummaryProto player_;
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.PlayerSummaryProto, POGOProtos.Rpc.PlayerSummaryProto.Builder, POGOProtos.Rpc.PlayerSummaryProtoOrBuilder> playerBuilder_;
    /**
     * <code>.POGOProtos.Rpc.PlayerSummaryProto player = 2;</code>
     * @return Whether the player field is set.
     */
    public boolean hasPlayer() {
      return playerBuilder_ != null || player_ != null;
    }
    /**
     * <code>.POGOProtos.Rpc.PlayerSummaryProto player = 2;</code>
     * @return The player.
     */
    public POGOProtos.Rpc.PlayerSummaryProto getPlayer() {
      if (playerBuilder_ == null) {
        return player_ == null ? POGOProtos.Rpc.PlayerSummaryProto.getDefaultInstance() : player_;
      } else {
        return playerBuilder_.getMessage();
      }
    }
    /**
     * <code>.POGOProtos.Rpc.PlayerSummaryProto player = 2;</code>
     */
    public Builder setPlayer(POGOProtos.Rpc.PlayerSummaryProto value) {
      if (playerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        player_ = value;
        onChanged();
      } else {
        playerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.PlayerSummaryProto player = 2;</code>
     */
    public Builder setPlayer(
        POGOProtos.Rpc.PlayerSummaryProto.Builder builderForValue) {
      if (playerBuilder_ == null) {
        player_ = builderForValue.build();
        onChanged();
      } else {
        playerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.PlayerSummaryProto player = 2;</code>
     */
    public Builder mergePlayer(POGOProtos.Rpc.PlayerSummaryProto value) {
      if (playerBuilder_ == null) {
        if (player_ != null) {
          player_ =
            POGOProtos.Rpc.PlayerSummaryProto.newBuilder(player_).mergeFrom(value).buildPartial();
        } else {
          player_ = value;
        }
        onChanged();
      } else {
        playerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.PlayerSummaryProto player = 2;</code>
     */
    public Builder clearPlayer() {
      if (playerBuilder_ == null) {
        player_ = null;
        onChanged();
      } else {
        player_ = null;
        playerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.PlayerSummaryProto player = 2;</code>
     */
    public POGOProtos.Rpc.PlayerSummaryProto.Builder getPlayerBuilder() {
      
      onChanged();
      return getPlayerFieldBuilder().getBuilder();
    }
    /**
     * <code>.POGOProtos.Rpc.PlayerSummaryProto player = 2;</code>
     */
    public POGOProtos.Rpc.PlayerSummaryProtoOrBuilder getPlayerOrBuilder() {
      if (playerBuilder_ != null) {
        return playerBuilder_.getMessageOrBuilder();
      } else {
        return player_ == null ?
            POGOProtos.Rpc.PlayerSummaryProto.getDefaultInstance() : player_;
      }
    }
    /**
     * <code>.POGOProtos.Rpc.PlayerSummaryProto player = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.PlayerSummaryProto, POGOProtos.Rpc.PlayerSummaryProto.Builder, POGOProtos.Rpc.PlayerSummaryProtoOrBuilder> 
        getPlayerFieldBuilder() {
      if (playerBuilder_ == null) {
        playerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            POGOProtos.Rpc.PlayerSummaryProto, POGOProtos.Rpc.PlayerSummaryProto.Builder, POGOProtos.Rpc.PlayerSummaryProtoOrBuilder>(
                getPlayer(),
                getParentForChildren(),
                isClean());
        player_ = null;
      }
      return playerBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:POGOProtos.Rpc.IncomingFriendInviteDisplayProto)
  }

  // @@protoc_insertion_point(class_scope:POGOProtos.Rpc.IncomingFriendInviteDisplayProto)
  private static final POGOProtos.Rpc.IncomingFriendInviteDisplayProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new POGOProtos.Rpc.IncomingFriendInviteDisplayProto();
  }

  public static POGOProtos.Rpc.IncomingFriendInviteDisplayProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IncomingFriendInviteDisplayProto>
      PARSER = new com.google.protobuf.AbstractParser<IncomingFriendInviteDisplayProto>() {
    @java.lang.Override
    public IncomingFriendInviteDisplayProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new IncomingFriendInviteDisplayProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<IncomingFriendInviteDisplayProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IncomingFriendInviteDisplayProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public POGOProtos.Rpc.IncomingFriendInviteDisplayProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

