// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface JAFHALLFAONOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.JAFHALLFAON)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 aacejoligog = 1;</code>
   * @return The aacejoligog.
   */
  long getAacejoligog();

  /**
   * <code>int64 ohoaecphocm = 25;</code>
   * @return The ohoaecphocm.
   */
  long getOhoaecphocm();

  /**
   * <code>int64 nnpocfpfndp = 28;</code>
   * @return The nnpocfpfndp.
   */
  long getNnpocfpfndp();

  /**
   * <code>int64 nbncinnjjcg = 29;</code>
   * @return The nbncinnjjcg.
   */
  long getNbncinnjjcg();

  /**
   * <code>bool mmgmnndeheh = 30;</code>
   * @return The mmgmnndeheh.
   */
  boolean getMmgmnndeheh();

  /**
   * <code>int32 lgajlgofkdb = 38;</code>
   * @return The lgajlgofkdb.
   */
  int getLgajlgofkdb();

  /**
   * <code>int64 nlhffkgabfk = 47;</code>
   * @return The nlhffkgabfk.
   */
  long getNlhffkgabfk();

  /**
   * <code>int32 ghfcbhmeiab = 51;</code>
   * @return The ghfcbhmeiab.
   */
  int getGhfcbhmeiab();

  /**
   * <code>int32 nopiaokpfbn = 52;</code>
   * @return The nopiaokpfbn.
   */
  int getNopiaokpfbn();

  /**
   * <code>int32 gaofnagngpp = 53;</code>
   * @return The gaofnagngpp.
   */
  int getGaofnagngpp();

  /**
   * <code>map&lt;int32, int64&gt; lfiklciecjc = 54;</code>
   */
  int getLfiklciecjcCount();
  /**
   * <code>map&lt;int32, int64&gt; lfiklciecjc = 54;</code>
   */
  boolean containsLfiklciecjc(
      int key);
  /**
   * Use {@link #getLfiklciecjcMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, java.lang.Long>
  getLfiklciecjc();
  /**
   * <code>map&lt;int32, int64&gt; lfiklciecjc = 54;</code>
   */
  java.util.Map<java.lang.Integer, java.lang.Long>
  getLfiklciecjcMap();
  /**
   * <code>map&lt;int32, int64&gt; lfiklciecjc = 54;</code>
   */

  long getLfiklciecjcOrDefault(
      int key,
      long defaultValue);
  /**
   * <code>map&lt;int32, int64&gt; lfiklciecjc = 54;</code>
   */

  long getLfiklciecjcOrThrow(
      int key);

  /**
   * <code>int64 nojanpnjnod = 55;</code>
   * @return The nojanpnjnod.
   */
  long getNojanpnjnod();

  /**
   * <code>int64 fcahdkhgoal = 56;</code>
   * @return The fcahdkhgoal.
   */
  long getFcahdkhgoal();

  /**
   * <code>float hgmfpkgciok = 57;</code>
   * @return The hgmfpkgciok.
   */
  float getHgmfpkgciok();

  /**
   * <code>int64 gjcgkbhnkja = 58;</code>
   * @return The gjcgkbhnkja.
   */
  long getGjcgkbhnkja();

  /**
   * <code>int64 gglhgmmhooo = 59;</code>
   * @return The gglhgmmhooo.
   */
  long getGglhgmmhooo();

  /**
   * <code>int64 pcgngkndaif = 60;</code>
   * @return The pcgngkndaif.
   */
  long getPcgngkndaif();

  /**
   * <code>int64 cjopdlepnfe = 61;</code>
   * @return The cjopdlepnfe.
   */
  long getCjopdlepnfe();

  /**
   * <code>int32 cmkpehdopel = 62;</code>
   * @return The cmkpehdopel.
   */
  int getCmkpehdopel();

  /**
   * <code>int32 jhggmpjgain = 63;</code>
   * @return The jhggmpjgain.
   */
  int getJhggmpjgain();

  /**
   * <code>int64 cdggkcmcleo = 64;</code>
   * @return The cdggkcmcleo.
   */
  long getCdggkcmcleo();

  /**
   * <code>float hlmfompbibm = 65;</code>
   * @return The hlmfompbibm.
   */
  float getHlmfompbibm();

  /**
   * <code>float mlpfepiajih = 66;</code>
   * @return The mlpfepiajih.
   */
  float getMlpfepiajih();

  /**
   * <code>.POGOProtos.Rpc.LKMMGBDLKFK bahemfkggoi = 67;</code>
   * @return Whether the bahemfkggoi field is set.
   */
  boolean hasBahemfkggoi();
  /**
   * <code>.POGOProtos.Rpc.LKMMGBDLKFK bahemfkggoi = 67;</code>
   * @return The bahemfkggoi.
   */
  POGOProtos.Rpc.LKMMGBDLKFK getBahemfkggoi();
  /**
   * <code>.POGOProtos.Rpc.LKMMGBDLKFK bahemfkggoi = 67;</code>
   */
  POGOProtos.Rpc.LKMMGBDLKFKOrBuilder getBahemfkggoiOrBuilder();

  /**
   * <code>map&lt;int32, .POGOProtos.Rpc.MFMAOEBOANM&gt; ghaomolmhmm = 68;</code>
   */
  int getGhaomolmhmmCount();
  /**
   * <code>map&lt;int32, .POGOProtos.Rpc.MFMAOEBOANM&gt; ghaomolmhmm = 68;</code>
   */
  boolean containsGhaomolmhmm(
      int key);
  /**
   * Use {@link #getGhaomolmhmmMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, POGOProtos.Rpc.MFMAOEBOANM>
  getGhaomolmhmm();
  /**
   * <code>map&lt;int32, .POGOProtos.Rpc.MFMAOEBOANM&gt; ghaomolmhmm = 68;</code>
   */
  java.util.Map<java.lang.Integer, POGOProtos.Rpc.MFMAOEBOANM>
  getGhaomolmhmmMap();
  /**
   * <code>map&lt;int32, .POGOProtos.Rpc.MFMAOEBOANM&gt; ghaomolmhmm = 68;</code>
   */

  POGOProtos.Rpc.MFMAOEBOANM getGhaomolmhmmOrDefault(
      int key,
      POGOProtos.Rpc.MFMAOEBOANM defaultValue);
  /**
   * <code>map&lt;int32, .POGOProtos.Rpc.MFMAOEBOANM&gt; ghaomolmhmm = 68;</code>
   */

  POGOProtos.Rpc.MFMAOEBOANM getGhaomolmhmmOrThrow(
      int key);

  /**
   * <code>map&lt;int32, .POGOProtos.Rpc.EMNEFBNBCMM&gt; ekimnhhdfna = 69;</code>
   */
  int getEkimnhhdfnaCount();
  /**
   * <code>map&lt;int32, .POGOProtos.Rpc.EMNEFBNBCMM&gt; ekimnhhdfna = 69;</code>
   */
  boolean containsEkimnhhdfna(
      int key);
  /**
   * Use {@link #getEkimnhhdfnaMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, POGOProtos.Rpc.EMNEFBNBCMM>
  getEkimnhhdfna();
  /**
   * <code>map&lt;int32, .POGOProtos.Rpc.EMNEFBNBCMM&gt; ekimnhhdfna = 69;</code>
   */
  java.util.Map<java.lang.Integer, POGOProtos.Rpc.EMNEFBNBCMM>
  getEkimnhhdfnaMap();
  /**
   * <code>map&lt;int32, .POGOProtos.Rpc.EMNEFBNBCMM&gt; ekimnhhdfna = 69;</code>
   */

  POGOProtos.Rpc.EMNEFBNBCMM getEkimnhhdfnaOrDefault(
      int key,
      POGOProtos.Rpc.EMNEFBNBCMM defaultValue);
  /**
   * <code>map&lt;int32, .POGOProtos.Rpc.EMNEFBNBCMM&gt; ekimnhhdfna = 69;</code>
   */

  POGOProtos.Rpc.EMNEFBNBCMM getEkimnhhdfnaOrThrow(
      int key);

  /**
   * <code>map&lt;int32, .POGOProtos.Rpc.EMNEFBNBCMM&gt; nliahieehoh = 70;</code>
   */
  int getNliahieehohCount();
  /**
   * <code>map&lt;int32, .POGOProtos.Rpc.EMNEFBNBCMM&gt; nliahieehoh = 70;</code>
   */
  boolean containsNliahieehoh(
      int key);
  /**
   * Use {@link #getNliahieehohMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, POGOProtos.Rpc.EMNEFBNBCMM>
  getNliahieehoh();
  /**
   * <code>map&lt;int32, .POGOProtos.Rpc.EMNEFBNBCMM&gt; nliahieehoh = 70;</code>
   */
  java.util.Map<java.lang.Integer, POGOProtos.Rpc.EMNEFBNBCMM>
  getNliahieehohMap();
  /**
   * <code>map&lt;int32, .POGOProtos.Rpc.EMNEFBNBCMM&gt; nliahieehoh = 70;</code>
   */

  POGOProtos.Rpc.EMNEFBNBCMM getNliahieehohOrDefault(
      int key,
      POGOProtos.Rpc.EMNEFBNBCMM defaultValue);
  /**
   * <code>map&lt;int32, .POGOProtos.Rpc.EMNEFBNBCMM&gt; nliahieehoh = 70;</code>
   */

  POGOProtos.Rpc.EMNEFBNBCMM getNliahieehohOrThrow(
      int key);

  /**
   * <code>.POGOProtos.Rpc.JAFHALLFAON.EKGPPMBJCKP fmipnpbhcnn = 71;</code>
   * @return Whether the fmipnpbhcnn field is set.
   */
  boolean hasFmipnpbhcnn();
  /**
   * <code>.POGOProtos.Rpc.JAFHALLFAON.EKGPPMBJCKP fmipnpbhcnn = 71;</code>
   * @return The fmipnpbhcnn.
   */
  POGOProtos.Rpc.JAFHALLFAON.EKGPPMBJCKP getFmipnpbhcnn();
  /**
   * <code>.POGOProtos.Rpc.JAFHALLFAON.EKGPPMBJCKP fmipnpbhcnn = 71;</code>
   */
  POGOProtos.Rpc.JAFHALLFAON.EKGPPMBJCKPOrBuilder getFmipnpbhcnnOrBuilder();

  /**
   * <code>.POGOProtos.Rpc.JCIPKJLHDFJ jolgcdaipak = 72;</code>
   * @return Whether the jolgcdaipak field is set.
   */
  boolean hasJolgcdaipak();
  /**
   * <code>.POGOProtos.Rpc.JCIPKJLHDFJ jolgcdaipak = 72;</code>
   * @return The jolgcdaipak.
   */
  POGOProtos.Rpc.JCIPKJLHDFJ getJolgcdaipak();
  /**
   * <code>.POGOProtos.Rpc.JCIPKJLHDFJ jolgcdaipak = 72;</code>
   */
  POGOProtos.Rpc.JCIPKJLHDFJOrBuilder getJolgcdaipakOrBuilder();

  /**
   * <code>bool kcindabpede = 73;</code>
   * @return The kcindabpede.
   */
  boolean getKcindabpede();

  /**
   * <code>string dckfckjcjng = 74;</code>
   * @return The dckfckjcjng.
   */
  java.lang.String getDckfckjcjng();
  /**
   * <code>string dckfckjcjng = 74;</code>
   * @return The bytes for dckfckjcjng.
   */
  com.google.protobuf.ByteString
      getDckfckjcjngBytes();

  /**
   * <code>int64 kebdpcfkphh = 75;</code>
   * @return The kebdpcfkphh.
   */
  long getKebdpcfkphh();

  /**
   * <code>.POGOProtos.Rpc.PNJAAHNHPDB lhnffnbipee = 76;</code>
   * @return The enum numeric value on the wire for lhnffnbipee.
   */
  int getLhnffnbipeeValue();
  /**
   * <code>.POGOProtos.Rpc.PNJAAHNHPDB lhnffnbipee = 76;</code>
   * @return The lhnffnbipee.
   */
  POGOProtos.Rpc.PNJAAHNHPDB getLhnffnbipee();

  /**
   * <code>int64 olkjffdhnnd = 77;</code>
   * @return The olkjffdhnnd.
   */
  long getOlkjffdhnnd();

  /**
   * <code>.POGOProtos.Rpc.PBEFDOIDGPH llgcjplofmm = 78;</code>
   * @return The enum numeric value on the wire for llgcjplofmm.
   */
  int getLlgcjplofmmValue();
  /**
   * <code>.POGOProtos.Rpc.PBEFDOIDGPH llgcjplofmm = 78;</code>
   * @return The llgcjplofmm.
   */
  POGOProtos.Rpc.PBEFDOIDGPH getLlgcjplofmm();

  /**
   * <code>string bmehiaaedoi = 79;</code>
   * @return The bmehiaaedoi.
   */
  java.lang.String getBmehiaaedoi();
  /**
   * <code>string bmehiaaedoi = 79;</code>
   * @return The bytes for bmehiaaedoi.
   */
  com.google.protobuf.ByteString
      getBmehiaaedoiBytes();

  /**
   * <code>int64 cfmeceoakjk = 80;</code>
   * @return The cfmeceoakjk.
   */
  long getCfmeceoakjk();

  /**
   * <code>string bkmjieljbhc = 81;</code>
   * @return The bkmjieljbhc.
   */
  java.lang.String getBkmjieljbhc();
  /**
   * <code>string bkmjieljbhc = 81;</code>
   * @return The bytes for bkmjieljbhc.
   */
  com.google.protobuf.ByteString
      getBkmjieljbhcBytes();

  /**
   * <code>int64 lffeeoldmoe = 82;</code>
   * @return The lffeeoldmoe.
   */
  long getLffeeoldmoe();

  /**
   * <code>int64 clappmhiafd = 83;</code>
   * @return The clappmhiafd.
   */
  long getClappmhiafd();

  /**
   * <code>bool gmckmdkbhma = 84;</code>
   * @return The gmckmdkbhma.
   */
  boolean getGmckmdkbhma();

  /**
   * <code>.POGOProtos.Rpc.JAFHALLFAON.EKGPPMBJCKP jhcalajppam = 85;</code>
   * @return Whether the jhcalajppam field is set.
   */
  boolean hasJhcalajppam();
  /**
   * <code>.POGOProtos.Rpc.JAFHALLFAON.EKGPPMBJCKP jhcalajppam = 85;</code>
   * @return The jhcalajppam.
   */
  POGOProtos.Rpc.JAFHALLFAON.EKGPPMBJCKP getJhcalajppam();
  /**
   * <code>.POGOProtos.Rpc.JAFHALLFAON.EKGPPMBJCKP jhcalajppam = 85;</code>
   */
  POGOProtos.Rpc.JAFHALLFAON.EKGPPMBJCKPOrBuilder getJhcalajppamOrBuilder();

  /**
   * <code>int32 mbdcipkapoe = 86;</code>
   * @return The mbdcipkapoe.
   */
  int getMbdcipkapoe();
}
