// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

/**
 * <pre>
 * ref: JENNNOKOOFM
 * </pre>
 *
 * Protobuf type {@code POGOProtos.Rpc.JENNNOKOOFM}
 */
public final class JENNNOKOOFM extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:POGOProtos.Rpc.JENNNOKOOFM)
    JENNNOKOOFMOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JENNNOKOOFM.newBuilder() to construct.
  private JENNNOKOOFM(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JENNNOKOOFM() {
    jgniofocoii_ = java.util.Collections.emptyList();
    pekhbkhoimi_ = 0;
    hjfgknbinoc_ = 0;
    oaobagdoolb_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JENNNOKOOFM();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JENNNOKOOFM(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              jgniofocoii_ = new java.util.ArrayList<POGOProtos.Rpc.ILMOJLKLIHM>();
              mutable_bitField0_ |= 0x00000001;
            }
            jgniofocoii_.add(
                input.readMessage(POGOProtos.Rpc.ILMOJLKLIHM.parser(), extensionRegistry));
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            pekhbkhoimi_ = rawValue;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            hjfgknbinoc_ = rawValue;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              oaobagdoolb_ = new java.util.ArrayList<POGOProtos.Rpc.ClientWeatherProto>();
              mutable_bitField0_ |= 0x00000002;
            }
            oaobagdoolb_.add(
                input.readMessage(POGOProtos.Rpc.ClientWeatherProto.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        jgniofocoii_ = java.util.Collections.unmodifiableList(jgniofocoii_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        oaobagdoolb_ = java.util.Collections.unmodifiableList(oaobagdoolb_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_JENNNOKOOFM_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_JENNNOKOOFM_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            POGOProtos.Rpc.JENNNOKOOFM.class, POGOProtos.Rpc.JENNNOKOOFM.Builder.class);
  }

  /**
   * <pre>
   * ref: JENNNOKOOFM/EGMDLFCCJOI/LMEEEGNBNIO
   * </pre>
   *
   * Protobuf enum {@code POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO}
   */
  public enum LMEEEGNBNIO
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNSET = 0;</code>
     */
    UNSET(0),
    /**
     * <code>SUCCESS = 1;</code>
     */
    SUCCESS(1),
    /**
     * <code>LOCATION_UNSET = 2;</code>
     */
    LOCATION_UNSET(2),
    /**
     * <code>ERROR = 3;</code>
     */
    ERROR(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNSET = 0;</code>
     */
    public static final int UNSET_VALUE = 0;
    /**
     * <code>SUCCESS = 1;</code>
     */
    public static final int SUCCESS_VALUE = 1;
    /**
     * <code>LOCATION_UNSET = 2;</code>
     */
    public static final int LOCATION_UNSET_VALUE = 2;
    /**
     * <code>ERROR = 3;</code>
     */
    public static final int ERROR_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LMEEEGNBNIO valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static LMEEEGNBNIO forNumber(int value) {
      switch (value) {
        case 0: return UNSET;
        case 1: return SUCCESS;
        case 2: return LOCATION_UNSET;
        case 3: return ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LMEEEGNBNIO>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LMEEEGNBNIO> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LMEEEGNBNIO>() {
            public LMEEEGNBNIO findValueByNumber(int number) {
              return LMEEEGNBNIO.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return POGOProtos.Rpc.JENNNOKOOFM.getDescriptor().getEnumTypes().get(0);
    }

    private static final LMEEEGNBNIO[] VALUES = values();

    public static LMEEEGNBNIO valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private LMEEEGNBNIO(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO)
  }

  /**
   * <pre>
   * ref: JENNNOKOOFM/EGMDLFCCJOI/MECJCIFNLBJ
   * </pre>
   *
   * Protobuf enum {@code POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ}
   */
  public enum MECJCIFNLBJ
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NONE = 0;</code>
     */
    NONE(0),
    /**
     * <code>DAY = 1;</code>
     */
    DAY(1),
    /**
     * <code>NIGHT = 2;</code>
     */
    NIGHT(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NONE = 0;</code>
     */
    public static final int NONE_VALUE = 0;
    /**
     * <code>DAY = 1;</code>
     */
    public static final int DAY_VALUE = 1;
    /**
     * <code>NIGHT = 2;</code>
     */
    public static final int NIGHT_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MECJCIFNLBJ valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MECJCIFNLBJ forNumber(int value) {
      switch (value) {
        case 0: return NONE;
        case 1: return DAY;
        case 2: return NIGHT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MECJCIFNLBJ>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MECJCIFNLBJ> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MECJCIFNLBJ>() {
            public MECJCIFNLBJ findValueByNumber(int number) {
              return MECJCIFNLBJ.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return POGOProtos.Rpc.JENNNOKOOFM.getDescriptor().getEnumTypes().get(1);
    }

    private static final MECJCIFNLBJ[] VALUES = values();

    public static MECJCIFNLBJ valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MECJCIFNLBJ(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ)
  }

  public static final int JGNIOFOCOII_FIELD_NUMBER = 1;
  private java.util.List<POGOProtos.Rpc.ILMOJLKLIHM> jgniofocoii_;
  /**
   * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
   */
  @java.lang.Override
  public java.util.List<POGOProtos.Rpc.ILMOJLKLIHM> getJgniofocoiiList() {
    return jgniofocoii_;
  }
  /**
   * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends POGOProtos.Rpc.ILMOJLKLIHMOrBuilder> 
      getJgniofocoiiOrBuilderList() {
    return jgniofocoii_;
  }
  /**
   * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
   */
  @java.lang.Override
  public int getJgniofocoiiCount() {
    return jgniofocoii_.size();
  }
  /**
   * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
   */
  @java.lang.Override
  public POGOProtos.Rpc.ILMOJLKLIHM getJgniofocoii(int index) {
    return jgniofocoii_.get(index);
  }
  /**
   * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
   */
  @java.lang.Override
  public POGOProtos.Rpc.ILMOJLKLIHMOrBuilder getJgniofocoiiOrBuilder(
      int index) {
    return jgniofocoii_.get(index);
  }

  public static final int PEKHBKHOIMI_FIELD_NUMBER = 2;
  private int pekhbkhoimi_;
  /**
   * <code>.POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO pekhbkhoimi = 2;</code>
   * @return The enum numeric value on the wire for pekhbkhoimi.
   */
  @java.lang.Override public int getPekhbkhoimiValue() {
    return pekhbkhoimi_;
  }
  /**
   * <code>.POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO pekhbkhoimi = 2;</code>
   * @return The pekhbkhoimi.
   */
  @java.lang.Override public POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO getPekhbkhoimi() {
    @SuppressWarnings("deprecation")
    POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO result = POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO.valueOf(pekhbkhoimi_);
    return result == null ? POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO.UNRECOGNIZED : result;
  }

  public static final int HJFGKNBINOC_FIELD_NUMBER = 3;
  private int hjfgknbinoc_;
  /**
   * <code>.POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ hjfgknbinoc = 3;</code>
   * @return The enum numeric value on the wire for hjfgknbinoc.
   */
  @java.lang.Override public int getHjfgknbinocValue() {
    return hjfgknbinoc_;
  }
  /**
   * <code>.POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ hjfgknbinoc = 3;</code>
   * @return The hjfgknbinoc.
   */
  @java.lang.Override public POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ getHjfgknbinoc() {
    @SuppressWarnings("deprecation")
    POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ result = POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ.valueOf(hjfgknbinoc_);
    return result == null ? POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ.UNRECOGNIZED : result;
  }

  public static final int OAOBAGDOOLB_FIELD_NUMBER = 4;
  private java.util.List<POGOProtos.Rpc.ClientWeatherProto> oaobagdoolb_;
  /**
   * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
   */
  @java.lang.Override
  public java.util.List<POGOProtos.Rpc.ClientWeatherProto> getOaobagdoolbList() {
    return oaobagdoolb_;
  }
  /**
   * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends POGOProtos.Rpc.ClientWeatherProtoOrBuilder> 
      getOaobagdoolbOrBuilderList() {
    return oaobagdoolb_;
  }
  /**
   * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
   */
  @java.lang.Override
  public int getOaobagdoolbCount() {
    return oaobagdoolb_.size();
  }
  /**
   * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
   */
  @java.lang.Override
  public POGOProtos.Rpc.ClientWeatherProto getOaobagdoolb(int index) {
    return oaobagdoolb_.get(index);
  }
  /**
   * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
   */
  @java.lang.Override
  public POGOProtos.Rpc.ClientWeatherProtoOrBuilder getOaobagdoolbOrBuilder(
      int index) {
    return oaobagdoolb_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < jgniofocoii_.size(); i++) {
      output.writeMessage(1, jgniofocoii_.get(i));
    }
    if (pekhbkhoimi_ != POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO.UNSET.getNumber()) {
      output.writeEnum(2, pekhbkhoimi_);
    }
    if (hjfgknbinoc_ != POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ.NONE.getNumber()) {
      output.writeEnum(3, hjfgknbinoc_);
    }
    for (int i = 0; i < oaobagdoolb_.size(); i++) {
      output.writeMessage(4, oaobagdoolb_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < jgniofocoii_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, jgniofocoii_.get(i));
    }
    if (pekhbkhoimi_ != POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO.UNSET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, pekhbkhoimi_);
    }
    if (hjfgknbinoc_ != POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ.NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, hjfgknbinoc_);
    }
    for (int i = 0; i < oaobagdoolb_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, oaobagdoolb_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof POGOProtos.Rpc.JENNNOKOOFM)) {
      return super.equals(obj);
    }
    POGOProtos.Rpc.JENNNOKOOFM other = (POGOProtos.Rpc.JENNNOKOOFM) obj;

    if (!getJgniofocoiiList()
        .equals(other.getJgniofocoiiList())) return false;
    if (pekhbkhoimi_ != other.pekhbkhoimi_) return false;
    if (hjfgknbinoc_ != other.hjfgknbinoc_) return false;
    if (!getOaobagdoolbList()
        .equals(other.getOaobagdoolbList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getJgniofocoiiCount() > 0) {
      hash = (37 * hash) + JGNIOFOCOII_FIELD_NUMBER;
      hash = (53 * hash) + getJgniofocoiiList().hashCode();
    }
    hash = (37 * hash) + PEKHBKHOIMI_FIELD_NUMBER;
    hash = (53 * hash) + pekhbkhoimi_;
    hash = (37 * hash) + HJFGKNBINOC_FIELD_NUMBER;
    hash = (53 * hash) + hjfgknbinoc_;
    if (getOaobagdoolbCount() > 0) {
      hash = (37 * hash) + OAOBAGDOOLB_FIELD_NUMBER;
      hash = (53 * hash) + getOaobagdoolbList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static POGOProtos.Rpc.JENNNOKOOFM parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.JENNNOKOOFM parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.JENNNOKOOFM parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.JENNNOKOOFM parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.JENNNOKOOFM parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.JENNNOKOOFM parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.JENNNOKOOFM parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.JENNNOKOOFM parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.JENNNOKOOFM parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.JENNNOKOOFM parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.JENNNOKOOFM parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.JENNNOKOOFM parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(POGOProtos.Rpc.JENNNOKOOFM prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ref: JENNNOKOOFM
   * </pre>
   *
   * Protobuf type {@code POGOProtos.Rpc.JENNNOKOOFM}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:POGOProtos.Rpc.JENNNOKOOFM)
      POGOProtos.Rpc.JENNNOKOOFMOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_JENNNOKOOFM_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_JENNNOKOOFM_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Rpc.JENNNOKOOFM.class, POGOProtos.Rpc.JENNNOKOOFM.Builder.class);
    }

    // Construct using POGOProtos.Rpc.JENNNOKOOFM.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getJgniofocoiiFieldBuilder();
        getOaobagdoolbFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (jgniofocoiiBuilder_ == null) {
        jgniofocoii_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        jgniofocoiiBuilder_.clear();
      }
      pekhbkhoimi_ = 0;

      hjfgknbinoc_ = 0;

      if (oaobagdoolbBuilder_ == null) {
        oaobagdoolb_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        oaobagdoolbBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_JENNNOKOOFM_descriptor;
    }

    @java.lang.Override
    public POGOProtos.Rpc.JENNNOKOOFM getDefaultInstanceForType() {
      return POGOProtos.Rpc.JENNNOKOOFM.getDefaultInstance();
    }

    @java.lang.Override
    public POGOProtos.Rpc.JENNNOKOOFM build() {
      POGOProtos.Rpc.JENNNOKOOFM result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public POGOProtos.Rpc.JENNNOKOOFM buildPartial() {
      POGOProtos.Rpc.JENNNOKOOFM result = new POGOProtos.Rpc.JENNNOKOOFM(this);
      int from_bitField0_ = bitField0_;
      if (jgniofocoiiBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          jgniofocoii_ = java.util.Collections.unmodifiableList(jgniofocoii_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.jgniofocoii_ = jgniofocoii_;
      } else {
        result.jgniofocoii_ = jgniofocoiiBuilder_.build();
      }
      result.pekhbkhoimi_ = pekhbkhoimi_;
      result.hjfgknbinoc_ = hjfgknbinoc_;
      if (oaobagdoolbBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          oaobagdoolb_ = java.util.Collections.unmodifiableList(oaobagdoolb_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.oaobagdoolb_ = oaobagdoolb_;
      } else {
        result.oaobagdoolb_ = oaobagdoolbBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof POGOProtos.Rpc.JENNNOKOOFM) {
        return mergeFrom((POGOProtos.Rpc.JENNNOKOOFM)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(POGOProtos.Rpc.JENNNOKOOFM other) {
      if (other == POGOProtos.Rpc.JENNNOKOOFM.getDefaultInstance()) return this;
      if (jgniofocoiiBuilder_ == null) {
        if (!other.jgniofocoii_.isEmpty()) {
          if (jgniofocoii_.isEmpty()) {
            jgniofocoii_ = other.jgniofocoii_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureJgniofocoiiIsMutable();
            jgniofocoii_.addAll(other.jgniofocoii_);
          }
          onChanged();
        }
      } else {
        if (!other.jgniofocoii_.isEmpty()) {
          if (jgniofocoiiBuilder_.isEmpty()) {
            jgniofocoiiBuilder_.dispose();
            jgniofocoiiBuilder_ = null;
            jgniofocoii_ = other.jgniofocoii_;
            bitField0_ = (bitField0_ & ~0x00000001);
            jgniofocoiiBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getJgniofocoiiFieldBuilder() : null;
          } else {
            jgniofocoiiBuilder_.addAllMessages(other.jgniofocoii_);
          }
        }
      }
      if (other.pekhbkhoimi_ != 0) {
        setPekhbkhoimiValue(other.getPekhbkhoimiValue());
      }
      if (other.hjfgknbinoc_ != 0) {
        setHjfgknbinocValue(other.getHjfgknbinocValue());
      }
      if (oaobagdoolbBuilder_ == null) {
        if (!other.oaobagdoolb_.isEmpty()) {
          if (oaobagdoolb_.isEmpty()) {
            oaobagdoolb_ = other.oaobagdoolb_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureOaobagdoolbIsMutable();
            oaobagdoolb_.addAll(other.oaobagdoolb_);
          }
          onChanged();
        }
      } else {
        if (!other.oaobagdoolb_.isEmpty()) {
          if (oaobagdoolbBuilder_.isEmpty()) {
            oaobagdoolbBuilder_.dispose();
            oaobagdoolbBuilder_ = null;
            oaobagdoolb_ = other.oaobagdoolb_;
            bitField0_ = (bitField0_ & ~0x00000002);
            oaobagdoolbBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOaobagdoolbFieldBuilder() : null;
          } else {
            oaobagdoolbBuilder_.addAllMessages(other.oaobagdoolb_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      POGOProtos.Rpc.JENNNOKOOFM parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (POGOProtos.Rpc.JENNNOKOOFM) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<POGOProtos.Rpc.ILMOJLKLIHM> jgniofocoii_ =
      java.util.Collections.emptyList();
    private void ensureJgniofocoiiIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        jgniofocoii_ = new java.util.ArrayList<POGOProtos.Rpc.ILMOJLKLIHM>(jgniofocoii_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        POGOProtos.Rpc.ILMOJLKLIHM, POGOProtos.Rpc.ILMOJLKLIHM.Builder, POGOProtos.Rpc.ILMOJLKLIHMOrBuilder> jgniofocoiiBuilder_;

    /**
     * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
     */
    public java.util.List<POGOProtos.Rpc.ILMOJLKLIHM> getJgniofocoiiList() {
      if (jgniofocoiiBuilder_ == null) {
        return java.util.Collections.unmodifiableList(jgniofocoii_);
      } else {
        return jgniofocoiiBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
     */
    public int getJgniofocoiiCount() {
      if (jgniofocoiiBuilder_ == null) {
        return jgniofocoii_.size();
      } else {
        return jgniofocoiiBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
     */
    public POGOProtos.Rpc.ILMOJLKLIHM getJgniofocoii(int index) {
      if (jgniofocoiiBuilder_ == null) {
        return jgniofocoii_.get(index);
      } else {
        return jgniofocoiiBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
     */
    public Builder setJgniofocoii(
        int index, POGOProtos.Rpc.ILMOJLKLIHM value) {
      if (jgniofocoiiBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJgniofocoiiIsMutable();
        jgniofocoii_.set(index, value);
        onChanged();
      } else {
        jgniofocoiiBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
     */
    public Builder setJgniofocoii(
        int index, POGOProtos.Rpc.ILMOJLKLIHM.Builder builderForValue) {
      if (jgniofocoiiBuilder_ == null) {
        ensureJgniofocoiiIsMutable();
        jgniofocoii_.set(index, builderForValue.build());
        onChanged();
      } else {
        jgniofocoiiBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
     */
    public Builder addJgniofocoii(POGOProtos.Rpc.ILMOJLKLIHM value) {
      if (jgniofocoiiBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJgniofocoiiIsMutable();
        jgniofocoii_.add(value);
        onChanged();
      } else {
        jgniofocoiiBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
     */
    public Builder addJgniofocoii(
        int index, POGOProtos.Rpc.ILMOJLKLIHM value) {
      if (jgniofocoiiBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJgniofocoiiIsMutable();
        jgniofocoii_.add(index, value);
        onChanged();
      } else {
        jgniofocoiiBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
     */
    public Builder addJgniofocoii(
        POGOProtos.Rpc.ILMOJLKLIHM.Builder builderForValue) {
      if (jgniofocoiiBuilder_ == null) {
        ensureJgniofocoiiIsMutable();
        jgniofocoii_.add(builderForValue.build());
        onChanged();
      } else {
        jgniofocoiiBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
     */
    public Builder addJgniofocoii(
        int index, POGOProtos.Rpc.ILMOJLKLIHM.Builder builderForValue) {
      if (jgniofocoiiBuilder_ == null) {
        ensureJgniofocoiiIsMutable();
        jgniofocoii_.add(index, builderForValue.build());
        onChanged();
      } else {
        jgniofocoiiBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
     */
    public Builder addAllJgniofocoii(
        java.lang.Iterable<? extends POGOProtos.Rpc.ILMOJLKLIHM> values) {
      if (jgniofocoiiBuilder_ == null) {
        ensureJgniofocoiiIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, jgniofocoii_);
        onChanged();
      } else {
        jgniofocoiiBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
     */
    public Builder clearJgniofocoii() {
      if (jgniofocoiiBuilder_ == null) {
        jgniofocoii_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        jgniofocoiiBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
     */
    public Builder removeJgniofocoii(int index) {
      if (jgniofocoiiBuilder_ == null) {
        ensureJgniofocoiiIsMutable();
        jgniofocoii_.remove(index);
        onChanged();
      } else {
        jgniofocoiiBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
     */
    public POGOProtos.Rpc.ILMOJLKLIHM.Builder getJgniofocoiiBuilder(
        int index) {
      return getJgniofocoiiFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
     */
    public POGOProtos.Rpc.ILMOJLKLIHMOrBuilder getJgniofocoiiOrBuilder(
        int index) {
      if (jgniofocoiiBuilder_ == null) {
        return jgniofocoii_.get(index);  } else {
        return jgniofocoiiBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
     */
    public java.util.List<? extends POGOProtos.Rpc.ILMOJLKLIHMOrBuilder> 
         getJgniofocoiiOrBuilderList() {
      if (jgniofocoiiBuilder_ != null) {
        return jgniofocoiiBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(jgniofocoii_);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
     */
    public POGOProtos.Rpc.ILMOJLKLIHM.Builder addJgniofocoiiBuilder() {
      return getJgniofocoiiFieldBuilder().addBuilder(
          POGOProtos.Rpc.ILMOJLKLIHM.getDefaultInstance());
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
     */
    public POGOProtos.Rpc.ILMOJLKLIHM.Builder addJgniofocoiiBuilder(
        int index) {
      return getJgniofocoiiFieldBuilder().addBuilder(
          index, POGOProtos.Rpc.ILMOJLKLIHM.getDefaultInstance());
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ILMOJLKLIHM jgniofocoii = 1;</code>
     */
    public java.util.List<POGOProtos.Rpc.ILMOJLKLIHM.Builder> 
         getJgniofocoiiBuilderList() {
      return getJgniofocoiiFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        POGOProtos.Rpc.ILMOJLKLIHM, POGOProtos.Rpc.ILMOJLKLIHM.Builder, POGOProtos.Rpc.ILMOJLKLIHMOrBuilder> 
        getJgniofocoiiFieldBuilder() {
      if (jgniofocoiiBuilder_ == null) {
        jgniofocoiiBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            POGOProtos.Rpc.ILMOJLKLIHM, POGOProtos.Rpc.ILMOJLKLIHM.Builder, POGOProtos.Rpc.ILMOJLKLIHMOrBuilder>(
                jgniofocoii_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        jgniofocoii_ = null;
      }
      return jgniofocoiiBuilder_;
    }

    private int pekhbkhoimi_ = 0;
    /**
     * <code>.POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO pekhbkhoimi = 2;</code>
     * @return The enum numeric value on the wire for pekhbkhoimi.
     */
    @java.lang.Override public int getPekhbkhoimiValue() {
      return pekhbkhoimi_;
    }
    /**
     * <code>.POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO pekhbkhoimi = 2;</code>
     * @param value The enum numeric value on the wire for pekhbkhoimi to set.
     * @return This builder for chaining.
     */
    public Builder setPekhbkhoimiValue(int value) {
      
      pekhbkhoimi_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO pekhbkhoimi = 2;</code>
     * @return The pekhbkhoimi.
     */
    @java.lang.Override
    public POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO getPekhbkhoimi() {
      @SuppressWarnings("deprecation")
      POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO result = POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO.valueOf(pekhbkhoimi_);
      return result == null ? POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO.UNRECOGNIZED : result;
    }
    /**
     * <code>.POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO pekhbkhoimi = 2;</code>
     * @param value The pekhbkhoimi to set.
     * @return This builder for chaining.
     */
    public Builder setPekhbkhoimi(POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      pekhbkhoimi_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.JENNNOKOOFM.LMEEEGNBNIO pekhbkhoimi = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPekhbkhoimi() {
      
      pekhbkhoimi_ = 0;
      onChanged();
      return this;
    }

    private int hjfgknbinoc_ = 0;
    /**
     * <code>.POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ hjfgknbinoc = 3;</code>
     * @return The enum numeric value on the wire for hjfgknbinoc.
     */
    @java.lang.Override public int getHjfgknbinocValue() {
      return hjfgknbinoc_;
    }
    /**
     * <code>.POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ hjfgknbinoc = 3;</code>
     * @param value The enum numeric value on the wire for hjfgknbinoc to set.
     * @return This builder for chaining.
     */
    public Builder setHjfgknbinocValue(int value) {
      
      hjfgknbinoc_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ hjfgknbinoc = 3;</code>
     * @return The hjfgknbinoc.
     */
    @java.lang.Override
    public POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ getHjfgknbinoc() {
      @SuppressWarnings("deprecation")
      POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ result = POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ.valueOf(hjfgknbinoc_);
      return result == null ? POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ.UNRECOGNIZED : result;
    }
    /**
     * <code>.POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ hjfgknbinoc = 3;</code>
     * @param value The hjfgknbinoc to set.
     * @return This builder for chaining.
     */
    public Builder setHjfgknbinoc(POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      hjfgknbinoc_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.JENNNOKOOFM.MECJCIFNLBJ hjfgknbinoc = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHjfgknbinoc() {
      
      hjfgknbinoc_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<POGOProtos.Rpc.ClientWeatherProto> oaobagdoolb_ =
      java.util.Collections.emptyList();
    private void ensureOaobagdoolbIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        oaobagdoolb_ = new java.util.ArrayList<POGOProtos.Rpc.ClientWeatherProto>(oaobagdoolb_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        POGOProtos.Rpc.ClientWeatherProto, POGOProtos.Rpc.ClientWeatherProto.Builder, POGOProtos.Rpc.ClientWeatherProtoOrBuilder> oaobagdoolbBuilder_;

    /**
     * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
     */
    public java.util.List<POGOProtos.Rpc.ClientWeatherProto> getOaobagdoolbList() {
      if (oaobagdoolbBuilder_ == null) {
        return java.util.Collections.unmodifiableList(oaobagdoolb_);
      } else {
        return oaobagdoolbBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
     */
    public int getOaobagdoolbCount() {
      if (oaobagdoolbBuilder_ == null) {
        return oaobagdoolb_.size();
      } else {
        return oaobagdoolbBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
     */
    public POGOProtos.Rpc.ClientWeatherProto getOaobagdoolb(int index) {
      if (oaobagdoolbBuilder_ == null) {
        return oaobagdoolb_.get(index);
      } else {
        return oaobagdoolbBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
     */
    public Builder setOaobagdoolb(
        int index, POGOProtos.Rpc.ClientWeatherProto value) {
      if (oaobagdoolbBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOaobagdoolbIsMutable();
        oaobagdoolb_.set(index, value);
        onChanged();
      } else {
        oaobagdoolbBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
     */
    public Builder setOaobagdoolb(
        int index, POGOProtos.Rpc.ClientWeatherProto.Builder builderForValue) {
      if (oaobagdoolbBuilder_ == null) {
        ensureOaobagdoolbIsMutable();
        oaobagdoolb_.set(index, builderForValue.build());
        onChanged();
      } else {
        oaobagdoolbBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
     */
    public Builder addOaobagdoolb(POGOProtos.Rpc.ClientWeatherProto value) {
      if (oaobagdoolbBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOaobagdoolbIsMutable();
        oaobagdoolb_.add(value);
        onChanged();
      } else {
        oaobagdoolbBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
     */
    public Builder addOaobagdoolb(
        int index, POGOProtos.Rpc.ClientWeatherProto value) {
      if (oaobagdoolbBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOaobagdoolbIsMutable();
        oaobagdoolb_.add(index, value);
        onChanged();
      } else {
        oaobagdoolbBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
     */
    public Builder addOaobagdoolb(
        POGOProtos.Rpc.ClientWeatherProto.Builder builderForValue) {
      if (oaobagdoolbBuilder_ == null) {
        ensureOaobagdoolbIsMutable();
        oaobagdoolb_.add(builderForValue.build());
        onChanged();
      } else {
        oaobagdoolbBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
     */
    public Builder addOaobagdoolb(
        int index, POGOProtos.Rpc.ClientWeatherProto.Builder builderForValue) {
      if (oaobagdoolbBuilder_ == null) {
        ensureOaobagdoolbIsMutable();
        oaobagdoolb_.add(index, builderForValue.build());
        onChanged();
      } else {
        oaobagdoolbBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
     */
    public Builder addAllOaobagdoolb(
        java.lang.Iterable<? extends POGOProtos.Rpc.ClientWeatherProto> values) {
      if (oaobagdoolbBuilder_ == null) {
        ensureOaobagdoolbIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, oaobagdoolb_);
        onChanged();
      } else {
        oaobagdoolbBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
     */
    public Builder clearOaobagdoolb() {
      if (oaobagdoolbBuilder_ == null) {
        oaobagdoolb_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        oaobagdoolbBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
     */
    public Builder removeOaobagdoolb(int index) {
      if (oaobagdoolbBuilder_ == null) {
        ensureOaobagdoolbIsMutable();
        oaobagdoolb_.remove(index);
        onChanged();
      } else {
        oaobagdoolbBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
     */
    public POGOProtos.Rpc.ClientWeatherProto.Builder getOaobagdoolbBuilder(
        int index) {
      return getOaobagdoolbFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
     */
    public POGOProtos.Rpc.ClientWeatherProtoOrBuilder getOaobagdoolbOrBuilder(
        int index) {
      if (oaobagdoolbBuilder_ == null) {
        return oaobagdoolb_.get(index);  } else {
        return oaobagdoolbBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
     */
    public java.util.List<? extends POGOProtos.Rpc.ClientWeatherProtoOrBuilder> 
         getOaobagdoolbOrBuilderList() {
      if (oaobagdoolbBuilder_ != null) {
        return oaobagdoolbBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(oaobagdoolb_);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
     */
    public POGOProtos.Rpc.ClientWeatherProto.Builder addOaobagdoolbBuilder() {
      return getOaobagdoolbFieldBuilder().addBuilder(
          POGOProtos.Rpc.ClientWeatherProto.getDefaultInstance());
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
     */
    public POGOProtos.Rpc.ClientWeatherProto.Builder addOaobagdoolbBuilder(
        int index) {
      return getOaobagdoolbFieldBuilder().addBuilder(
          index, POGOProtos.Rpc.ClientWeatherProto.getDefaultInstance());
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ClientWeatherProto oaobagdoolb = 4;</code>
     */
    public java.util.List<POGOProtos.Rpc.ClientWeatherProto.Builder> 
         getOaobagdoolbBuilderList() {
      return getOaobagdoolbFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        POGOProtos.Rpc.ClientWeatherProto, POGOProtos.Rpc.ClientWeatherProto.Builder, POGOProtos.Rpc.ClientWeatherProtoOrBuilder> 
        getOaobagdoolbFieldBuilder() {
      if (oaobagdoolbBuilder_ == null) {
        oaobagdoolbBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            POGOProtos.Rpc.ClientWeatherProto, POGOProtos.Rpc.ClientWeatherProto.Builder, POGOProtos.Rpc.ClientWeatherProtoOrBuilder>(
                oaobagdoolb_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        oaobagdoolb_ = null;
      }
      return oaobagdoolbBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:POGOProtos.Rpc.JENNNOKOOFM)
  }

  // @@protoc_insertion_point(class_scope:POGOProtos.Rpc.JENNNOKOOFM)
  private static final POGOProtos.Rpc.JENNNOKOOFM DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new POGOProtos.Rpc.JENNNOKOOFM();
  }

  public static POGOProtos.Rpc.JENNNOKOOFM getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JENNNOKOOFM>
      PARSER = new com.google.protobuf.AbstractParser<JENNNOKOOFM>() {
    @java.lang.Override
    public JENNNOKOOFM parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JENNNOKOOFM(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JENNNOKOOFM> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JENNNOKOOFM> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public POGOProtos.Rpc.JENNNOKOOFM getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

