// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Rpc/Rpc.proto

package POGOProtos.Rpc;

public interface JNLPOPHCMBFOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.JNLPOPHCMBF)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 opiapbcehbm = 1;</code>
   * @return The opiapbcehbm.
   */
  long getOpiapbcehbm();

  /**
   * <code>int32 pfjaoaigndk = 2;</code>
   * @return The pfjaoaigndk.
   */
  int getPfjaoaigndk();
}
