// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface MJAPBBMIDMOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.MJAPBBMIDMO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool lgehoepjopp = 1;</code>
   * @return The lgehoepjopp.
   */
  boolean getLgehoepjopp();

  /**
   * <code>.POGOProtos.Rpc.KDHELLCEOJD ockinehgelh = 2;</code>
   * @return Whether the ockinehgelh field is set.
   */
  boolean hasOckinehgelh();
  /**
   * <code>.POGOProtos.Rpc.KDHELLCEOJD ockinehgelh = 2;</code>
   * @return The ockinehgelh.
   */
  POGOProtos.Rpc.KDHELLCEOJD getOckinehgelh();
  /**
   * <code>.POGOProtos.Rpc.KDHELLCEOJD ockinehgelh = 2;</code>
   */
  POGOProtos.Rpc.KDHELLCEOJDOrBuilder getOckinehgelhOrBuilder();

  /**
   * <code>bool dfkdjgkebio = 3;</code>
   * @return The dfkdjgkebio.
   */
  boolean getDfkdjgkebio();

  /**
   * <code>bool icngjmjabgd = 4;</code>
   * @return The icngjmjabgd.
   */
  boolean getIcngjmjabgd();

  /**
   * <code>bool gfpdjkaeblh = 5;</code>
   * @return The gfpdjkaeblh.
   */
  boolean getGfpdjkaeblh();

  /**
   * <code>bool dlnmdoogiob = 6;</code>
   * @return The dlnmdoogiob.
   */
  boolean getDlnmdoogiob();

  /**
   * <code>bool pjjkcnjhjak = 7;</code>
   * @return The pjjkcnjhjak.
   */
  boolean getPjjkcnjhjak();

  /**
   * <code>bool opknfbmofpm = 8;</code>
   * @return The opknfbmofpm.
   */
  boolean getOpknfbmofpm();

  /**
   * <code>int64 bkgddphflbk = 9;</code>
   * @return The bkgddphflbk.
   */
  long getBkgddphflbk();

  /**
   * <code>repeated int32 ipjkhofihkd = 10;</code>
   * @return A list containing the ipjkhofihkd.
   */
  java.util.List<java.lang.Integer> getIpjkhofihkdList();
  /**
   * <code>repeated int32 ipjkhofihkd = 10;</code>
   * @return The count of ipjkhofihkd.
   */
  int getIpjkhofihkdCount();
  /**
   * <code>repeated int32 ipjkhofihkd = 10;</code>
   * @param index The index of the element to return.
   * @return The ipjkhofihkd at the given index.
   */
  int getIpjkhofihkd(int index);
}
