// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface NMBANBFMKEBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.NMBANBFMKEB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.POGOProtos.Rpc.FNBHEBOFJIC amdomjkfbon = 1;</code>
   * @return The enum numeric value on the wire for amdomjkfbon.
   */
  int getAmdomjkfbonValue();
  /**
   * <code>.POGOProtos.Rpc.FNBHEBOFJIC amdomjkfbon = 1;</code>
   * @return The amdomjkfbon.
   */
  POGOProtos.Rpc.FNBHEBOFJIC getAmdomjkfbon();

  /**
   * <code>int32 benhjkcimgd = 2;</code>
   * @return The benhjkcimgd.
   */
  int getBenhjkcimgd();
}
