// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

/**
 * Protobuf type {@code POGOProtos.Rpc.OCMADBJOKHO}
 */
public  final class OCMADBJOKHO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:POGOProtos.Rpc.OCMADBJOKHO)
    OCMADBJOKHOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OCMADBJOKHO.newBuilder() to construct.
  private OCMADBJOKHO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OCMADBJOKHO() {
    nfhdogdahmn_ = "";
    afnakjnnani_ = 0;
    onlojoajaac_ = java.util.Collections.emptyList();
    gkdagghbnae_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OCMADBJOKHO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OCMADBJOKHO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            nfhdogdahmn_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            afnakjnnani_ = rawValue;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              onlojoajaac_ = new java.util.ArrayList<POGOProtos.Rpc.ICGBHPDMKPI>();
              mutable_bitField0_ |= 0x00000001;
            }
            onlojoajaac_.add(
                input.readMessage(POGOProtos.Rpc.ICGBHPDMKPI.parser(), extensionRegistry));
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            gkdagghbnae_ = rawValue;
            break;
          }
          case 42: {
            POGOProtos.Rpc.DCJFLOGKNII.Builder subBuilder = null;
            if (igokappdngo_ != null) {
              subBuilder = igokappdngo_.toBuilder();
            }
            igokappdngo_ = input.readMessage(POGOProtos.Rpc.DCJFLOGKNII.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(igokappdngo_);
              igokappdngo_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        onlojoajaac_ = java.util.Collections.unmodifiableList(onlojoajaac_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_OCMADBJOKHO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_OCMADBJOKHO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            POGOProtos.Rpc.OCMADBJOKHO.class, POGOProtos.Rpc.OCMADBJOKHO.Builder.class);
  }

  public static final int NFHDOGDAHMN_FIELD_NUMBER = 1;
  private volatile java.lang.Object nfhdogdahmn_;
  /**
   * <code>string nfhdogdahmn = 1;</code>
   * @return The nfhdogdahmn.
   */
  public java.lang.String getNfhdogdahmn() {
    java.lang.Object ref = nfhdogdahmn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nfhdogdahmn_ = s;
      return s;
    }
  }
  /**
   * <code>string nfhdogdahmn = 1;</code>
   * @return The bytes for nfhdogdahmn.
   */
  public com.google.protobuf.ByteString
      getNfhdogdahmnBytes() {
    java.lang.Object ref = nfhdogdahmn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nfhdogdahmn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AFNAKJNNANI_FIELD_NUMBER = 2;
  private int afnakjnnani_;
  /**
   * <code>.POGOProtos.Rpc.QuestType afnakjnnani = 2;</code>
   * @return The enum numeric value on the wire for afnakjnnani.
   */
  public int getAfnakjnnaniValue() {
    return afnakjnnani_;
  }
  /**
   * <code>.POGOProtos.Rpc.QuestType afnakjnnani = 2;</code>
   * @return The afnakjnnani.
   */
  public POGOProtos.Rpc.QuestType getAfnakjnnani() {
    @SuppressWarnings("deprecation")
    POGOProtos.Rpc.QuestType result = POGOProtos.Rpc.QuestType.valueOf(afnakjnnani_);
    return result == null ? POGOProtos.Rpc.QuestType.UNRECOGNIZED : result;
  }

  public static final int ONLOJOAJAAC_FIELD_NUMBER = 3;
  private java.util.List<POGOProtos.Rpc.ICGBHPDMKPI> onlojoajaac_;
  /**
   * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
   */
  public java.util.List<POGOProtos.Rpc.ICGBHPDMKPI> getOnlojoajaacList() {
    return onlojoajaac_;
  }
  /**
   * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
   */
  public java.util.List<? extends POGOProtos.Rpc.ICGBHPDMKPIOrBuilder> 
      getOnlojoajaacOrBuilderList() {
    return onlojoajaac_;
  }
  /**
   * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
   */
  public int getOnlojoajaacCount() {
    return onlojoajaac_.size();
  }
  /**
   * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
   */
  public POGOProtos.Rpc.ICGBHPDMKPI getOnlojoajaac(int index) {
    return onlojoajaac_.get(index);
  }
  /**
   * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
   */
  public POGOProtos.Rpc.ICGBHPDMKPIOrBuilder getOnlojoajaacOrBuilder(
      int index) {
    return onlojoajaac_.get(index);
  }

  public static final int GKDAGGHBNAE_FIELD_NUMBER = 4;
  private int gkdagghbnae_;
  /**
   * <code>.POGOProtos.Rpc.QuestProto.EGGDDOBICIL gkdagghbnae = 4;</code>
   * @return The enum numeric value on the wire for gkdagghbnae.
   */
  public int getGkdagghbnaeValue() {
    return gkdagghbnae_;
  }
  /**
   * <code>.POGOProtos.Rpc.QuestProto.EGGDDOBICIL gkdagghbnae = 4;</code>
   * @return The gkdagghbnae.
   */
  public POGOProtos.Rpc.QuestProto.EGGDDOBICIL getGkdagghbnae() {
    @SuppressWarnings("deprecation")
    POGOProtos.Rpc.QuestProto.EGGDDOBICIL result = POGOProtos.Rpc.QuestProto.EGGDDOBICIL.valueOf(gkdagghbnae_);
    return result == null ? POGOProtos.Rpc.QuestProto.EGGDDOBICIL.UNRECOGNIZED : result;
  }

  public static final int IGOKAPPDNGO_FIELD_NUMBER = 5;
  private POGOProtos.Rpc.DCJFLOGKNII igokappdngo_;
  /**
   * <code>.POGOProtos.Rpc.DCJFLOGKNII igokappdngo = 5;</code>
   * @return Whether the igokappdngo field is set.
   */
  public boolean hasIgokappdngo() {
    return igokappdngo_ != null;
  }
  /**
   * <code>.POGOProtos.Rpc.DCJFLOGKNII igokappdngo = 5;</code>
   * @return The igokappdngo.
   */
  public POGOProtos.Rpc.DCJFLOGKNII getIgokappdngo() {
    return igokappdngo_ == null ? POGOProtos.Rpc.DCJFLOGKNII.getDefaultInstance() : igokappdngo_;
  }
  /**
   * <code>.POGOProtos.Rpc.DCJFLOGKNII igokappdngo = 5;</code>
   */
  public POGOProtos.Rpc.DCJFLOGKNIIOrBuilder getIgokappdngoOrBuilder() {
    return getIgokappdngo();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNfhdogdahmnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nfhdogdahmn_);
    }
    if (afnakjnnani_ != POGOProtos.Rpc.QuestType.QUEST_UNSET.getNumber()) {
      output.writeEnum(2, afnakjnnani_);
    }
    for (int i = 0; i < onlojoajaac_.size(); i++) {
      output.writeMessage(3, onlojoajaac_.get(i));
    }
    if (gkdagghbnae_ != POGOProtos.Rpc.QuestProto.EGGDDOBICIL.UNSET.getNumber()) {
      output.writeEnum(4, gkdagghbnae_);
    }
    if (igokappdngo_ != null) {
      output.writeMessage(5, getIgokappdngo());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNfhdogdahmnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nfhdogdahmn_);
    }
    if (afnakjnnani_ != POGOProtos.Rpc.QuestType.QUEST_UNSET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, afnakjnnani_);
    }
    for (int i = 0; i < onlojoajaac_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, onlojoajaac_.get(i));
    }
    if (gkdagghbnae_ != POGOProtos.Rpc.QuestProto.EGGDDOBICIL.UNSET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, gkdagghbnae_);
    }
    if (igokappdngo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getIgokappdngo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof POGOProtos.Rpc.OCMADBJOKHO)) {
      return super.equals(obj);
    }
    POGOProtos.Rpc.OCMADBJOKHO other = (POGOProtos.Rpc.OCMADBJOKHO) obj;

    if (!getNfhdogdahmn()
        .equals(other.getNfhdogdahmn())) return false;
    if (afnakjnnani_ != other.afnakjnnani_) return false;
    if (!getOnlojoajaacList()
        .equals(other.getOnlojoajaacList())) return false;
    if (gkdagghbnae_ != other.gkdagghbnae_) return false;
    if (hasIgokappdngo() != other.hasIgokappdngo()) return false;
    if (hasIgokappdngo()) {
      if (!getIgokappdngo()
          .equals(other.getIgokappdngo())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NFHDOGDAHMN_FIELD_NUMBER;
    hash = (53 * hash) + getNfhdogdahmn().hashCode();
    hash = (37 * hash) + AFNAKJNNANI_FIELD_NUMBER;
    hash = (53 * hash) + afnakjnnani_;
    if (getOnlojoajaacCount() > 0) {
      hash = (37 * hash) + ONLOJOAJAAC_FIELD_NUMBER;
      hash = (53 * hash) + getOnlojoajaacList().hashCode();
    }
    hash = (37 * hash) + GKDAGGHBNAE_FIELD_NUMBER;
    hash = (53 * hash) + gkdagghbnae_;
    if (hasIgokappdngo()) {
      hash = (37 * hash) + IGOKAPPDNGO_FIELD_NUMBER;
      hash = (53 * hash) + getIgokappdngo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static POGOProtos.Rpc.OCMADBJOKHO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.OCMADBJOKHO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.OCMADBJOKHO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.OCMADBJOKHO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.OCMADBJOKHO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.OCMADBJOKHO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.OCMADBJOKHO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.OCMADBJOKHO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.OCMADBJOKHO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.OCMADBJOKHO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.OCMADBJOKHO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.OCMADBJOKHO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(POGOProtos.Rpc.OCMADBJOKHO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code POGOProtos.Rpc.OCMADBJOKHO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:POGOProtos.Rpc.OCMADBJOKHO)
      POGOProtos.Rpc.OCMADBJOKHOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_OCMADBJOKHO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_OCMADBJOKHO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Rpc.OCMADBJOKHO.class, POGOProtos.Rpc.OCMADBJOKHO.Builder.class);
    }

    // Construct using POGOProtos.Rpc.OCMADBJOKHO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOnlojoajaacFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      nfhdogdahmn_ = "";

      afnakjnnani_ = 0;

      if (onlojoajaacBuilder_ == null) {
        onlojoajaac_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        onlojoajaacBuilder_.clear();
      }
      gkdagghbnae_ = 0;

      if (igokappdngoBuilder_ == null) {
        igokappdngo_ = null;
      } else {
        igokappdngo_ = null;
        igokappdngoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_OCMADBJOKHO_descriptor;
    }

    @java.lang.Override
    public POGOProtos.Rpc.OCMADBJOKHO getDefaultInstanceForType() {
      return POGOProtos.Rpc.OCMADBJOKHO.getDefaultInstance();
    }

    @java.lang.Override
    public POGOProtos.Rpc.OCMADBJOKHO build() {
      POGOProtos.Rpc.OCMADBJOKHO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public POGOProtos.Rpc.OCMADBJOKHO buildPartial() {
      POGOProtos.Rpc.OCMADBJOKHO result = new POGOProtos.Rpc.OCMADBJOKHO(this);
      int from_bitField0_ = bitField0_;
      result.nfhdogdahmn_ = nfhdogdahmn_;
      result.afnakjnnani_ = afnakjnnani_;
      if (onlojoajaacBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          onlojoajaac_ = java.util.Collections.unmodifiableList(onlojoajaac_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.onlojoajaac_ = onlojoajaac_;
      } else {
        result.onlojoajaac_ = onlojoajaacBuilder_.build();
      }
      result.gkdagghbnae_ = gkdagghbnae_;
      if (igokappdngoBuilder_ == null) {
        result.igokappdngo_ = igokappdngo_;
      } else {
        result.igokappdngo_ = igokappdngoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof POGOProtos.Rpc.OCMADBJOKHO) {
        return mergeFrom((POGOProtos.Rpc.OCMADBJOKHO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(POGOProtos.Rpc.OCMADBJOKHO other) {
      if (other == POGOProtos.Rpc.OCMADBJOKHO.getDefaultInstance()) return this;
      if (!other.getNfhdogdahmn().isEmpty()) {
        nfhdogdahmn_ = other.nfhdogdahmn_;
        onChanged();
      }
      if (other.afnakjnnani_ != 0) {
        setAfnakjnnaniValue(other.getAfnakjnnaniValue());
      }
      if (onlojoajaacBuilder_ == null) {
        if (!other.onlojoajaac_.isEmpty()) {
          if (onlojoajaac_.isEmpty()) {
            onlojoajaac_ = other.onlojoajaac_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOnlojoajaacIsMutable();
            onlojoajaac_.addAll(other.onlojoajaac_);
          }
          onChanged();
        }
      } else {
        if (!other.onlojoajaac_.isEmpty()) {
          if (onlojoajaacBuilder_.isEmpty()) {
            onlojoajaacBuilder_.dispose();
            onlojoajaacBuilder_ = null;
            onlojoajaac_ = other.onlojoajaac_;
            bitField0_ = (bitField0_ & ~0x00000001);
            onlojoajaacBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOnlojoajaacFieldBuilder() : null;
          } else {
            onlojoajaacBuilder_.addAllMessages(other.onlojoajaac_);
          }
        }
      }
      if (other.gkdagghbnae_ != 0) {
        setGkdagghbnaeValue(other.getGkdagghbnaeValue());
      }
      if (other.hasIgokappdngo()) {
        mergeIgokappdngo(other.getIgokappdngo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      POGOProtos.Rpc.OCMADBJOKHO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (POGOProtos.Rpc.OCMADBJOKHO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object nfhdogdahmn_ = "";
    /**
     * <code>string nfhdogdahmn = 1;</code>
     * @return The nfhdogdahmn.
     */
    public java.lang.String getNfhdogdahmn() {
      java.lang.Object ref = nfhdogdahmn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nfhdogdahmn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nfhdogdahmn = 1;</code>
     * @return The bytes for nfhdogdahmn.
     */
    public com.google.protobuf.ByteString
        getNfhdogdahmnBytes() {
      java.lang.Object ref = nfhdogdahmn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nfhdogdahmn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nfhdogdahmn = 1;</code>
     * @param value The nfhdogdahmn to set.
     * @return This builder for chaining.
     */
    public Builder setNfhdogdahmn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nfhdogdahmn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nfhdogdahmn = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNfhdogdahmn() {
      
      nfhdogdahmn_ = getDefaultInstance().getNfhdogdahmn();
      onChanged();
      return this;
    }
    /**
     * <code>string nfhdogdahmn = 1;</code>
     * @param value The bytes for nfhdogdahmn to set.
     * @return This builder for chaining.
     */
    public Builder setNfhdogdahmnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nfhdogdahmn_ = value;
      onChanged();
      return this;
    }

    private int afnakjnnani_ = 0;
    /**
     * <code>.POGOProtos.Rpc.QuestType afnakjnnani = 2;</code>
     * @return The enum numeric value on the wire for afnakjnnani.
     */
    public int getAfnakjnnaniValue() {
      return afnakjnnani_;
    }
    /**
     * <code>.POGOProtos.Rpc.QuestType afnakjnnani = 2;</code>
     * @param value The enum numeric value on the wire for afnakjnnani to set.
     * @return This builder for chaining.
     */
    public Builder setAfnakjnnaniValue(int value) {
      afnakjnnani_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.QuestType afnakjnnani = 2;</code>
     * @return The afnakjnnani.
     */
    public POGOProtos.Rpc.QuestType getAfnakjnnani() {
      @SuppressWarnings("deprecation")
      POGOProtos.Rpc.QuestType result = POGOProtos.Rpc.QuestType.valueOf(afnakjnnani_);
      return result == null ? POGOProtos.Rpc.QuestType.UNRECOGNIZED : result;
    }
    /**
     * <code>.POGOProtos.Rpc.QuestType afnakjnnani = 2;</code>
     * @param value The afnakjnnani to set.
     * @return This builder for chaining.
     */
    public Builder setAfnakjnnani(POGOProtos.Rpc.QuestType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      afnakjnnani_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.QuestType afnakjnnani = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAfnakjnnani() {
      
      afnakjnnani_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<POGOProtos.Rpc.ICGBHPDMKPI> onlojoajaac_ =
      java.util.Collections.emptyList();
    private void ensureOnlojoajaacIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        onlojoajaac_ = new java.util.ArrayList<POGOProtos.Rpc.ICGBHPDMKPI>(onlojoajaac_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        POGOProtos.Rpc.ICGBHPDMKPI, POGOProtos.Rpc.ICGBHPDMKPI.Builder, POGOProtos.Rpc.ICGBHPDMKPIOrBuilder> onlojoajaacBuilder_;

    /**
     * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
     */
    public java.util.List<POGOProtos.Rpc.ICGBHPDMKPI> getOnlojoajaacList() {
      if (onlojoajaacBuilder_ == null) {
        return java.util.Collections.unmodifiableList(onlojoajaac_);
      } else {
        return onlojoajaacBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
     */
    public int getOnlojoajaacCount() {
      if (onlojoajaacBuilder_ == null) {
        return onlojoajaac_.size();
      } else {
        return onlojoajaacBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
     */
    public POGOProtos.Rpc.ICGBHPDMKPI getOnlojoajaac(int index) {
      if (onlojoajaacBuilder_ == null) {
        return onlojoajaac_.get(index);
      } else {
        return onlojoajaacBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
     */
    public Builder setOnlojoajaac(
        int index, POGOProtos.Rpc.ICGBHPDMKPI value) {
      if (onlojoajaacBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOnlojoajaacIsMutable();
        onlojoajaac_.set(index, value);
        onChanged();
      } else {
        onlojoajaacBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
     */
    public Builder setOnlojoajaac(
        int index, POGOProtos.Rpc.ICGBHPDMKPI.Builder builderForValue) {
      if (onlojoajaacBuilder_ == null) {
        ensureOnlojoajaacIsMutable();
        onlojoajaac_.set(index, builderForValue.build());
        onChanged();
      } else {
        onlojoajaacBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
     */
    public Builder addOnlojoajaac(POGOProtos.Rpc.ICGBHPDMKPI value) {
      if (onlojoajaacBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOnlojoajaacIsMutable();
        onlojoajaac_.add(value);
        onChanged();
      } else {
        onlojoajaacBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
     */
    public Builder addOnlojoajaac(
        int index, POGOProtos.Rpc.ICGBHPDMKPI value) {
      if (onlojoajaacBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOnlojoajaacIsMutable();
        onlojoajaac_.add(index, value);
        onChanged();
      } else {
        onlojoajaacBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
     */
    public Builder addOnlojoajaac(
        POGOProtos.Rpc.ICGBHPDMKPI.Builder builderForValue) {
      if (onlojoajaacBuilder_ == null) {
        ensureOnlojoajaacIsMutable();
        onlojoajaac_.add(builderForValue.build());
        onChanged();
      } else {
        onlojoajaacBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
     */
    public Builder addOnlojoajaac(
        int index, POGOProtos.Rpc.ICGBHPDMKPI.Builder builderForValue) {
      if (onlojoajaacBuilder_ == null) {
        ensureOnlojoajaacIsMutable();
        onlojoajaac_.add(index, builderForValue.build());
        onChanged();
      } else {
        onlojoajaacBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
     */
    public Builder addAllOnlojoajaac(
        java.lang.Iterable<? extends POGOProtos.Rpc.ICGBHPDMKPI> values) {
      if (onlojoajaacBuilder_ == null) {
        ensureOnlojoajaacIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, onlojoajaac_);
        onChanged();
      } else {
        onlojoajaacBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
     */
    public Builder clearOnlojoajaac() {
      if (onlojoajaacBuilder_ == null) {
        onlojoajaac_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        onlojoajaacBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
     */
    public Builder removeOnlojoajaac(int index) {
      if (onlojoajaacBuilder_ == null) {
        ensureOnlojoajaacIsMutable();
        onlojoajaac_.remove(index);
        onChanged();
      } else {
        onlojoajaacBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
     */
    public POGOProtos.Rpc.ICGBHPDMKPI.Builder getOnlojoajaacBuilder(
        int index) {
      return getOnlojoajaacFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
     */
    public POGOProtos.Rpc.ICGBHPDMKPIOrBuilder getOnlojoajaacOrBuilder(
        int index) {
      if (onlojoajaacBuilder_ == null) {
        return onlojoajaac_.get(index);  } else {
        return onlojoajaacBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
     */
    public java.util.List<? extends POGOProtos.Rpc.ICGBHPDMKPIOrBuilder> 
         getOnlojoajaacOrBuilderList() {
      if (onlojoajaacBuilder_ != null) {
        return onlojoajaacBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(onlojoajaac_);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
     */
    public POGOProtos.Rpc.ICGBHPDMKPI.Builder addOnlojoajaacBuilder() {
      return getOnlojoajaacFieldBuilder().addBuilder(
          POGOProtos.Rpc.ICGBHPDMKPI.getDefaultInstance());
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
     */
    public POGOProtos.Rpc.ICGBHPDMKPI.Builder addOnlojoajaacBuilder(
        int index) {
      return getOnlojoajaacFieldBuilder().addBuilder(
          index, POGOProtos.Rpc.ICGBHPDMKPI.getDefaultInstance());
    }
    /**
     * <code>repeated .POGOProtos.Rpc.ICGBHPDMKPI onlojoajaac = 3;</code>
     */
    public java.util.List<POGOProtos.Rpc.ICGBHPDMKPI.Builder> 
         getOnlojoajaacBuilderList() {
      return getOnlojoajaacFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        POGOProtos.Rpc.ICGBHPDMKPI, POGOProtos.Rpc.ICGBHPDMKPI.Builder, POGOProtos.Rpc.ICGBHPDMKPIOrBuilder> 
        getOnlojoajaacFieldBuilder() {
      if (onlojoajaacBuilder_ == null) {
        onlojoajaacBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            POGOProtos.Rpc.ICGBHPDMKPI, POGOProtos.Rpc.ICGBHPDMKPI.Builder, POGOProtos.Rpc.ICGBHPDMKPIOrBuilder>(
                onlojoajaac_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        onlojoajaac_ = null;
      }
      return onlojoajaacBuilder_;
    }

    private int gkdagghbnae_ = 0;
    /**
     * <code>.POGOProtos.Rpc.QuestProto.EGGDDOBICIL gkdagghbnae = 4;</code>
     * @return The enum numeric value on the wire for gkdagghbnae.
     */
    public int getGkdagghbnaeValue() {
      return gkdagghbnae_;
    }
    /**
     * <code>.POGOProtos.Rpc.QuestProto.EGGDDOBICIL gkdagghbnae = 4;</code>
     * @param value The enum numeric value on the wire for gkdagghbnae to set.
     * @return This builder for chaining.
     */
    public Builder setGkdagghbnaeValue(int value) {
      gkdagghbnae_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.QuestProto.EGGDDOBICIL gkdagghbnae = 4;</code>
     * @return The gkdagghbnae.
     */
    public POGOProtos.Rpc.QuestProto.EGGDDOBICIL getGkdagghbnae() {
      @SuppressWarnings("deprecation")
      POGOProtos.Rpc.QuestProto.EGGDDOBICIL result = POGOProtos.Rpc.QuestProto.EGGDDOBICIL.valueOf(gkdagghbnae_);
      return result == null ? POGOProtos.Rpc.QuestProto.EGGDDOBICIL.UNRECOGNIZED : result;
    }
    /**
     * <code>.POGOProtos.Rpc.QuestProto.EGGDDOBICIL gkdagghbnae = 4;</code>
     * @param value The gkdagghbnae to set.
     * @return This builder for chaining.
     */
    public Builder setGkdagghbnae(POGOProtos.Rpc.QuestProto.EGGDDOBICIL value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      gkdagghbnae_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.QuestProto.EGGDDOBICIL gkdagghbnae = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGkdagghbnae() {
      
      gkdagghbnae_ = 0;
      onChanged();
      return this;
    }

    private POGOProtos.Rpc.DCJFLOGKNII igokappdngo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.DCJFLOGKNII, POGOProtos.Rpc.DCJFLOGKNII.Builder, POGOProtos.Rpc.DCJFLOGKNIIOrBuilder> igokappdngoBuilder_;
    /**
     * <code>.POGOProtos.Rpc.DCJFLOGKNII igokappdngo = 5;</code>
     * @return Whether the igokappdngo field is set.
     */
    public boolean hasIgokappdngo() {
      return igokappdngoBuilder_ != null || igokappdngo_ != null;
    }
    /**
     * <code>.POGOProtos.Rpc.DCJFLOGKNII igokappdngo = 5;</code>
     * @return The igokappdngo.
     */
    public POGOProtos.Rpc.DCJFLOGKNII getIgokappdngo() {
      if (igokappdngoBuilder_ == null) {
        return igokappdngo_ == null ? POGOProtos.Rpc.DCJFLOGKNII.getDefaultInstance() : igokappdngo_;
      } else {
        return igokappdngoBuilder_.getMessage();
      }
    }
    /**
     * <code>.POGOProtos.Rpc.DCJFLOGKNII igokappdngo = 5;</code>
     */
    public Builder setIgokappdngo(POGOProtos.Rpc.DCJFLOGKNII value) {
      if (igokappdngoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        igokappdngo_ = value;
        onChanged();
      } else {
        igokappdngoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.DCJFLOGKNII igokappdngo = 5;</code>
     */
    public Builder setIgokappdngo(
        POGOProtos.Rpc.DCJFLOGKNII.Builder builderForValue) {
      if (igokappdngoBuilder_ == null) {
        igokappdngo_ = builderForValue.build();
        onChanged();
      } else {
        igokappdngoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.DCJFLOGKNII igokappdngo = 5;</code>
     */
    public Builder mergeIgokappdngo(POGOProtos.Rpc.DCJFLOGKNII value) {
      if (igokappdngoBuilder_ == null) {
        if (igokappdngo_ != null) {
          igokappdngo_ =
            POGOProtos.Rpc.DCJFLOGKNII.newBuilder(igokappdngo_).mergeFrom(value).buildPartial();
        } else {
          igokappdngo_ = value;
        }
        onChanged();
      } else {
        igokappdngoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.DCJFLOGKNII igokappdngo = 5;</code>
     */
    public Builder clearIgokappdngo() {
      if (igokappdngoBuilder_ == null) {
        igokappdngo_ = null;
        onChanged();
      } else {
        igokappdngo_ = null;
        igokappdngoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.DCJFLOGKNII igokappdngo = 5;</code>
     */
    public POGOProtos.Rpc.DCJFLOGKNII.Builder getIgokappdngoBuilder() {
      
      onChanged();
      return getIgokappdngoFieldBuilder().getBuilder();
    }
    /**
     * <code>.POGOProtos.Rpc.DCJFLOGKNII igokappdngo = 5;</code>
     */
    public POGOProtos.Rpc.DCJFLOGKNIIOrBuilder getIgokappdngoOrBuilder() {
      if (igokappdngoBuilder_ != null) {
        return igokappdngoBuilder_.getMessageOrBuilder();
      } else {
        return igokappdngo_ == null ?
            POGOProtos.Rpc.DCJFLOGKNII.getDefaultInstance() : igokappdngo_;
      }
    }
    /**
     * <code>.POGOProtos.Rpc.DCJFLOGKNII igokappdngo = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.DCJFLOGKNII, POGOProtos.Rpc.DCJFLOGKNII.Builder, POGOProtos.Rpc.DCJFLOGKNIIOrBuilder> 
        getIgokappdngoFieldBuilder() {
      if (igokappdngoBuilder_ == null) {
        igokappdngoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            POGOProtos.Rpc.DCJFLOGKNII, POGOProtos.Rpc.DCJFLOGKNII.Builder, POGOProtos.Rpc.DCJFLOGKNIIOrBuilder>(
                getIgokappdngo(),
                getParentForChildren(),
                isClean());
        igokappdngo_ = null;
      }
      return igokappdngoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:POGOProtos.Rpc.OCMADBJOKHO)
  }

  // @@protoc_insertion_point(class_scope:POGOProtos.Rpc.OCMADBJOKHO)
  private static final POGOProtos.Rpc.OCMADBJOKHO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new POGOProtos.Rpc.OCMADBJOKHO();
  }

  public static POGOProtos.Rpc.OCMADBJOKHO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OCMADBJOKHO>
      PARSER = new com.google.protobuf.AbstractParser<OCMADBJOKHO>() {
    @java.lang.Override
    public OCMADBJOKHO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OCMADBJOKHO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OCMADBJOKHO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OCMADBJOKHO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public POGOProtos.Rpc.OCMADBJOKHO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

