// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Rpc/Rpc.proto

package POGOProtos.Rpc;

/**
 * Protobuf type {@code POGOProtos.Rpc.PEEANGPNCDN}
 */
public  final class PEEANGPNCDN extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:POGOProtos.Rpc.PEEANGPNCDN)
    PEEANGPNCDNOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PEEANGPNCDN.newBuilder() to construct.
  private PEEANGPNCDN(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PEEANGPNCDN() {
    aacijcchnmd_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PEEANGPNCDN();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PEEANGPNCDN(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            aacijcchnmd_ = rawValue;
            break;
          }
          case 18: {
            POGOProtos.Rpc.NMDHABMPFFG.Builder subBuilder = null;
            if (akhnjpdnpcd_ != null) {
              subBuilder = akhnjpdnpcd_.toBuilder();
            }
            akhnjpdnpcd_ = input.readMessage(POGOProtos.Rpc.NMDHABMPFFG.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(akhnjpdnpcd_);
              akhnjpdnpcd_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return POGOProtos.Rpc.Rpc.internal_static_POGOProtos_Rpc_PEEANGPNCDN_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return POGOProtos.Rpc.Rpc.internal_static_POGOProtos_Rpc_PEEANGPNCDN_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            POGOProtos.Rpc.PEEANGPNCDN.class, POGOProtos.Rpc.PEEANGPNCDN.Builder.class);
  }

  /**
   * Protobuf enum {@code POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA}
   */
  public enum ONBOILJELLA
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ONBOILJELLA_UNSET = 0;</code>
     */
    ONBOILJELLA_UNSET(0),
    /**
     * <code>ONBOILJELLA_SUCCESS = 1;</code>
     */
    ONBOILJELLA_SUCCESS(1),
    /**
     * <code>ONBOILJELLA_ERROR_INCUBATOR_NOT_FOUND = 2;</code>
     */
    ONBOILJELLA_ERROR_INCUBATOR_NOT_FOUND(2),
    /**
     * <code>ONBOILJELLA_ERROR_POKEMON_EGG_NOT_FOUND = 3;</code>
     */
    ONBOILJELLA_ERROR_POKEMON_EGG_NOT_FOUND(3),
    /**
     * <code>ONBOILJELLA_ERROR_POKEMON_ID_NOT_EGG = 4;</code>
     */
    ONBOILJELLA_ERROR_POKEMON_ID_NOT_EGG(4),
    /**
     * <code>ONBOILJELLA_ERROR_INCUBATOR_ALREADY_IN_USE = 5;</code>
     */
    ONBOILJELLA_ERROR_INCUBATOR_ALREADY_IN_USE(5),
    /**
     * <code>ONBOILJELLA_ERROR_POKEMON_ALREADY_INCUBATING = 6;</code>
     */
    ONBOILJELLA_ERROR_POKEMON_ALREADY_INCUBATING(6),
    /**
     * <code>ONBOILJELLA_ERROR_INCUBATOR_NO_USES_REMAINING = 7;</code>
     */
    ONBOILJELLA_ERROR_INCUBATOR_NO_USES_REMAINING(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ONBOILJELLA_UNSET = 0;</code>
     */
    public static final int ONBOILJELLA_UNSET_VALUE = 0;
    /**
     * <code>ONBOILJELLA_SUCCESS = 1;</code>
     */
    public static final int ONBOILJELLA_SUCCESS_VALUE = 1;
    /**
     * <code>ONBOILJELLA_ERROR_INCUBATOR_NOT_FOUND = 2;</code>
     */
    public static final int ONBOILJELLA_ERROR_INCUBATOR_NOT_FOUND_VALUE = 2;
    /**
     * <code>ONBOILJELLA_ERROR_POKEMON_EGG_NOT_FOUND = 3;</code>
     */
    public static final int ONBOILJELLA_ERROR_POKEMON_EGG_NOT_FOUND_VALUE = 3;
    /**
     * <code>ONBOILJELLA_ERROR_POKEMON_ID_NOT_EGG = 4;</code>
     */
    public static final int ONBOILJELLA_ERROR_POKEMON_ID_NOT_EGG_VALUE = 4;
    /**
     * <code>ONBOILJELLA_ERROR_INCUBATOR_ALREADY_IN_USE = 5;</code>
     */
    public static final int ONBOILJELLA_ERROR_INCUBATOR_ALREADY_IN_USE_VALUE = 5;
    /**
     * <code>ONBOILJELLA_ERROR_POKEMON_ALREADY_INCUBATING = 6;</code>
     */
    public static final int ONBOILJELLA_ERROR_POKEMON_ALREADY_INCUBATING_VALUE = 6;
    /**
     * <code>ONBOILJELLA_ERROR_INCUBATOR_NO_USES_REMAINING = 7;</code>
     */
    public static final int ONBOILJELLA_ERROR_INCUBATOR_NO_USES_REMAINING_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ONBOILJELLA valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ONBOILJELLA forNumber(int value) {
      switch (value) {
        case 0: return ONBOILJELLA_UNSET;
        case 1: return ONBOILJELLA_SUCCESS;
        case 2: return ONBOILJELLA_ERROR_INCUBATOR_NOT_FOUND;
        case 3: return ONBOILJELLA_ERROR_POKEMON_EGG_NOT_FOUND;
        case 4: return ONBOILJELLA_ERROR_POKEMON_ID_NOT_EGG;
        case 5: return ONBOILJELLA_ERROR_INCUBATOR_ALREADY_IN_USE;
        case 6: return ONBOILJELLA_ERROR_POKEMON_ALREADY_INCUBATING;
        case 7: return ONBOILJELLA_ERROR_INCUBATOR_NO_USES_REMAINING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ONBOILJELLA>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ONBOILJELLA> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ONBOILJELLA>() {
            public ONBOILJELLA findValueByNumber(int number) {
              return ONBOILJELLA.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return POGOProtos.Rpc.PEEANGPNCDN.getDescriptor().getEnumTypes().get(0);
    }

    private static final ONBOILJELLA[] VALUES = values();

    public static ONBOILJELLA valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ONBOILJELLA(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA)
  }

  public interface CJHJHDICLPIOrBuilder extends
      // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI}
   */
  public  static final class CJHJHDICLPI extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI)
      CJHJHDICLPIOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CJHJHDICLPI.newBuilder() to construct.
    private CJHJHDICLPI(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CJHJHDICLPI() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CJHJHDICLPI();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CJHJHDICLPI(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Rpc.Rpc.internal_static_POGOProtos_Rpc_PEEANGPNCDN_CJHJHDICLPI_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Rpc.Rpc.internal_static_POGOProtos_Rpc_PEEANGPNCDN_CJHJHDICLPI_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI.class, POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI.Builder.class);
    }

    /**
     * Protobuf enum {@code POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI.ONBOILJELLA}
     */
    public enum ONBOILJELLA
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ONBOILJELLA_UNSET = 0;</code>
       */
      ONBOILJELLA_UNSET(0),
      /**
       * <code>ONBOILJELLA_SUCCESS = 1;</code>
       */
      ONBOILJELLA_SUCCESS(1),
      /**
       * <code>ONBOILJELLA_ERROR_INCUBATOR_NOT_FOUND = 2;</code>
       */
      ONBOILJELLA_ERROR_INCUBATOR_NOT_FOUND(2),
      /**
       * <code>ONBOILJELLA_ERROR_POKEMON_EGG_NOT_FOUND = 3;</code>
       */
      ONBOILJELLA_ERROR_POKEMON_EGG_NOT_FOUND(3),
      /**
       * <code>ONBOILJELLA_ERROR_POKEMON_ID_NOT_EGG = 4;</code>
       */
      ONBOILJELLA_ERROR_POKEMON_ID_NOT_EGG(4),
      /**
       * <code>ONBOILJELLA_ERROR_INCUBATOR_ALREADY_IN_USE = 5;</code>
       */
      ONBOILJELLA_ERROR_INCUBATOR_ALREADY_IN_USE(5),
      /**
       * <code>ONBOILJELLA_ERROR_POKEMON_ALREADY_INCUBATING = 6;</code>
       */
      ONBOILJELLA_ERROR_POKEMON_ALREADY_INCUBATING(6),
      /**
       * <code>ONBOILJELLA_ERROR_INCUBATOR_NO_USES_REMAINING = 7;</code>
       */
      ONBOILJELLA_ERROR_INCUBATOR_NO_USES_REMAINING(7),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ONBOILJELLA_UNSET = 0;</code>
       */
      public static final int ONBOILJELLA_UNSET_VALUE = 0;
      /**
       * <code>ONBOILJELLA_SUCCESS = 1;</code>
       */
      public static final int ONBOILJELLA_SUCCESS_VALUE = 1;
      /**
       * <code>ONBOILJELLA_ERROR_INCUBATOR_NOT_FOUND = 2;</code>
       */
      public static final int ONBOILJELLA_ERROR_INCUBATOR_NOT_FOUND_VALUE = 2;
      /**
       * <code>ONBOILJELLA_ERROR_POKEMON_EGG_NOT_FOUND = 3;</code>
       */
      public static final int ONBOILJELLA_ERROR_POKEMON_EGG_NOT_FOUND_VALUE = 3;
      /**
       * <code>ONBOILJELLA_ERROR_POKEMON_ID_NOT_EGG = 4;</code>
       */
      public static final int ONBOILJELLA_ERROR_POKEMON_ID_NOT_EGG_VALUE = 4;
      /**
       * <code>ONBOILJELLA_ERROR_INCUBATOR_ALREADY_IN_USE = 5;</code>
       */
      public static final int ONBOILJELLA_ERROR_INCUBATOR_ALREADY_IN_USE_VALUE = 5;
      /**
       * <code>ONBOILJELLA_ERROR_POKEMON_ALREADY_INCUBATING = 6;</code>
       */
      public static final int ONBOILJELLA_ERROR_POKEMON_ALREADY_INCUBATING_VALUE = 6;
      /**
       * <code>ONBOILJELLA_ERROR_INCUBATOR_NO_USES_REMAINING = 7;</code>
       */
      public static final int ONBOILJELLA_ERROR_INCUBATOR_NO_USES_REMAINING_VALUE = 7;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ONBOILJELLA valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ONBOILJELLA forNumber(int value) {
        switch (value) {
          case 0: return ONBOILJELLA_UNSET;
          case 1: return ONBOILJELLA_SUCCESS;
          case 2: return ONBOILJELLA_ERROR_INCUBATOR_NOT_FOUND;
          case 3: return ONBOILJELLA_ERROR_POKEMON_EGG_NOT_FOUND;
          case 4: return ONBOILJELLA_ERROR_POKEMON_ID_NOT_EGG;
          case 5: return ONBOILJELLA_ERROR_INCUBATOR_ALREADY_IN_USE;
          case 6: return ONBOILJELLA_ERROR_POKEMON_ALREADY_INCUBATING;
          case 7: return ONBOILJELLA_ERROR_INCUBATOR_NO_USES_REMAINING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ONBOILJELLA>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ONBOILJELLA> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ONBOILJELLA>() {
              public ONBOILJELLA findValueByNumber(int number) {
                return ONBOILJELLA.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI.getDescriptor().getEnumTypes().get(0);
      }

      private static final ONBOILJELLA[] VALUES = values();

      public static ONBOILJELLA valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ONBOILJELLA(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI.ONBOILJELLA)
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI)) {
        return super.equals(obj);
      }
      POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI other = (POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI)
        POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPIOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return POGOProtos.Rpc.Rpc.internal_static_POGOProtos_Rpc_PEEANGPNCDN_CJHJHDICLPI_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return POGOProtos.Rpc.Rpc.internal_static_POGOProtos_Rpc_PEEANGPNCDN_CJHJHDICLPI_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI.class, POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI.Builder.class);
      }

      // Construct using POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return POGOProtos.Rpc.Rpc.internal_static_POGOProtos_Rpc_PEEANGPNCDN_CJHJHDICLPI_descriptor;
      }

      @java.lang.Override
      public POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI getDefaultInstanceForType() {
        return POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI.getDefaultInstance();
      }

      @java.lang.Override
      public POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI build() {
        POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI buildPartial() {
        POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI result = new POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI) {
          return mergeFrom((POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI other) {
        if (other == POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI)
    }

    // @@protoc_insertion_point(class_scope:POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI)
    private static final POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI();
    }

    public static POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CJHJHDICLPI>
        PARSER = new com.google.protobuf.AbstractParser<CJHJHDICLPI>() {
      @java.lang.Override
      public CJHJHDICLPI parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CJHJHDICLPI(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CJHJHDICLPI> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CJHJHDICLPI> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public POGOProtos.Rpc.PEEANGPNCDN.CJHJHDICLPI getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int AACIJCCHNMD_FIELD_NUMBER = 1;
  private int aacijcchnmd_;
  /**
   * <code>.POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA aacijcchnmd = 1;</code>
   * @return The enum numeric value on the wire for aacijcchnmd.
   */
  public int getAacijcchnmdValue() {
    return aacijcchnmd_;
  }
  /**
   * <code>.POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA aacijcchnmd = 1;</code>
   * @return The aacijcchnmd.
   */
  public POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA getAacijcchnmd() {
    @SuppressWarnings("deprecation")
    POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA result = POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA.valueOf(aacijcchnmd_);
    return result == null ? POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA.UNRECOGNIZED : result;
  }

  public static final int AKHNJPDNPCD_FIELD_NUMBER = 2;
  private POGOProtos.Rpc.NMDHABMPFFG akhnjpdnpcd_;
  /**
   * <code>.POGOProtos.Rpc.NMDHABMPFFG akhnjpdnpcd = 2;</code>
   * @return Whether the akhnjpdnpcd field is set.
   */
  public boolean hasAkhnjpdnpcd() {
    return akhnjpdnpcd_ != null;
  }
  /**
   * <code>.POGOProtos.Rpc.NMDHABMPFFG akhnjpdnpcd = 2;</code>
   * @return The akhnjpdnpcd.
   */
  public POGOProtos.Rpc.NMDHABMPFFG getAkhnjpdnpcd() {
    return akhnjpdnpcd_ == null ? POGOProtos.Rpc.NMDHABMPFFG.getDefaultInstance() : akhnjpdnpcd_;
  }
  /**
   * <code>.POGOProtos.Rpc.NMDHABMPFFG akhnjpdnpcd = 2;</code>
   */
  public POGOProtos.Rpc.NMDHABMPFFGOrBuilder getAkhnjpdnpcdOrBuilder() {
    return getAkhnjpdnpcd();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (aacijcchnmd_ != POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA.ONBOILJELLA_UNSET.getNumber()) {
      output.writeEnum(1, aacijcchnmd_);
    }
    if (akhnjpdnpcd_ != null) {
      output.writeMessage(2, getAkhnjpdnpcd());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (aacijcchnmd_ != POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA.ONBOILJELLA_UNSET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, aacijcchnmd_);
    }
    if (akhnjpdnpcd_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAkhnjpdnpcd());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof POGOProtos.Rpc.PEEANGPNCDN)) {
      return super.equals(obj);
    }
    POGOProtos.Rpc.PEEANGPNCDN other = (POGOProtos.Rpc.PEEANGPNCDN) obj;

    if (aacijcchnmd_ != other.aacijcchnmd_) return false;
    if (hasAkhnjpdnpcd() != other.hasAkhnjpdnpcd()) return false;
    if (hasAkhnjpdnpcd()) {
      if (!getAkhnjpdnpcd()
          .equals(other.getAkhnjpdnpcd())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AACIJCCHNMD_FIELD_NUMBER;
    hash = (53 * hash) + aacijcchnmd_;
    if (hasAkhnjpdnpcd()) {
      hash = (37 * hash) + AKHNJPDNPCD_FIELD_NUMBER;
      hash = (53 * hash) + getAkhnjpdnpcd().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static POGOProtos.Rpc.PEEANGPNCDN parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.PEEANGPNCDN parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.PEEANGPNCDN parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.PEEANGPNCDN parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.PEEANGPNCDN parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.PEEANGPNCDN parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.PEEANGPNCDN parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.PEEANGPNCDN parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.PEEANGPNCDN parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.PEEANGPNCDN parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.PEEANGPNCDN parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.PEEANGPNCDN parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(POGOProtos.Rpc.PEEANGPNCDN prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code POGOProtos.Rpc.PEEANGPNCDN}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:POGOProtos.Rpc.PEEANGPNCDN)
      POGOProtos.Rpc.PEEANGPNCDNOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Rpc.Rpc.internal_static_POGOProtos_Rpc_PEEANGPNCDN_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Rpc.Rpc.internal_static_POGOProtos_Rpc_PEEANGPNCDN_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Rpc.PEEANGPNCDN.class, POGOProtos.Rpc.PEEANGPNCDN.Builder.class);
    }

    // Construct using POGOProtos.Rpc.PEEANGPNCDN.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      aacijcchnmd_ = 0;

      if (akhnjpdnpcdBuilder_ == null) {
        akhnjpdnpcd_ = null;
      } else {
        akhnjpdnpcd_ = null;
        akhnjpdnpcdBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return POGOProtos.Rpc.Rpc.internal_static_POGOProtos_Rpc_PEEANGPNCDN_descriptor;
    }

    @java.lang.Override
    public POGOProtos.Rpc.PEEANGPNCDN getDefaultInstanceForType() {
      return POGOProtos.Rpc.PEEANGPNCDN.getDefaultInstance();
    }

    @java.lang.Override
    public POGOProtos.Rpc.PEEANGPNCDN build() {
      POGOProtos.Rpc.PEEANGPNCDN result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public POGOProtos.Rpc.PEEANGPNCDN buildPartial() {
      POGOProtos.Rpc.PEEANGPNCDN result = new POGOProtos.Rpc.PEEANGPNCDN(this);
      result.aacijcchnmd_ = aacijcchnmd_;
      if (akhnjpdnpcdBuilder_ == null) {
        result.akhnjpdnpcd_ = akhnjpdnpcd_;
      } else {
        result.akhnjpdnpcd_ = akhnjpdnpcdBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof POGOProtos.Rpc.PEEANGPNCDN) {
        return mergeFrom((POGOProtos.Rpc.PEEANGPNCDN)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(POGOProtos.Rpc.PEEANGPNCDN other) {
      if (other == POGOProtos.Rpc.PEEANGPNCDN.getDefaultInstance()) return this;
      if (other.aacijcchnmd_ != 0) {
        setAacijcchnmdValue(other.getAacijcchnmdValue());
      }
      if (other.hasAkhnjpdnpcd()) {
        mergeAkhnjpdnpcd(other.getAkhnjpdnpcd());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      POGOProtos.Rpc.PEEANGPNCDN parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (POGOProtos.Rpc.PEEANGPNCDN) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int aacijcchnmd_ = 0;
    /**
     * <code>.POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA aacijcchnmd = 1;</code>
     * @return The enum numeric value on the wire for aacijcchnmd.
     */
    public int getAacijcchnmdValue() {
      return aacijcchnmd_;
    }
    /**
     * <code>.POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA aacijcchnmd = 1;</code>
     * @param value The enum numeric value on the wire for aacijcchnmd to set.
     * @return This builder for chaining.
     */
    public Builder setAacijcchnmdValue(int value) {
      aacijcchnmd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA aacijcchnmd = 1;</code>
     * @return The aacijcchnmd.
     */
    public POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA getAacijcchnmd() {
      @SuppressWarnings("deprecation")
      POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA result = POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA.valueOf(aacijcchnmd_);
      return result == null ? POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA.UNRECOGNIZED : result;
    }
    /**
     * <code>.POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA aacijcchnmd = 1;</code>
     * @param value The aacijcchnmd to set.
     * @return This builder for chaining.
     */
    public Builder setAacijcchnmd(POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      aacijcchnmd_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.PEEANGPNCDN.ONBOILJELLA aacijcchnmd = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAacijcchnmd() {
      
      aacijcchnmd_ = 0;
      onChanged();
      return this;
    }

    private POGOProtos.Rpc.NMDHABMPFFG akhnjpdnpcd_;
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.NMDHABMPFFG, POGOProtos.Rpc.NMDHABMPFFG.Builder, POGOProtos.Rpc.NMDHABMPFFGOrBuilder> akhnjpdnpcdBuilder_;
    /**
     * <code>.POGOProtos.Rpc.NMDHABMPFFG akhnjpdnpcd = 2;</code>
     * @return Whether the akhnjpdnpcd field is set.
     */
    public boolean hasAkhnjpdnpcd() {
      return akhnjpdnpcdBuilder_ != null || akhnjpdnpcd_ != null;
    }
    /**
     * <code>.POGOProtos.Rpc.NMDHABMPFFG akhnjpdnpcd = 2;</code>
     * @return The akhnjpdnpcd.
     */
    public POGOProtos.Rpc.NMDHABMPFFG getAkhnjpdnpcd() {
      if (akhnjpdnpcdBuilder_ == null) {
        return akhnjpdnpcd_ == null ? POGOProtos.Rpc.NMDHABMPFFG.getDefaultInstance() : akhnjpdnpcd_;
      } else {
        return akhnjpdnpcdBuilder_.getMessage();
      }
    }
    /**
     * <code>.POGOProtos.Rpc.NMDHABMPFFG akhnjpdnpcd = 2;</code>
     */
    public Builder setAkhnjpdnpcd(POGOProtos.Rpc.NMDHABMPFFG value) {
      if (akhnjpdnpcdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        akhnjpdnpcd_ = value;
        onChanged();
      } else {
        akhnjpdnpcdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.NMDHABMPFFG akhnjpdnpcd = 2;</code>
     */
    public Builder setAkhnjpdnpcd(
        POGOProtos.Rpc.NMDHABMPFFG.Builder builderForValue) {
      if (akhnjpdnpcdBuilder_ == null) {
        akhnjpdnpcd_ = builderForValue.build();
        onChanged();
      } else {
        akhnjpdnpcdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.NMDHABMPFFG akhnjpdnpcd = 2;</code>
     */
    public Builder mergeAkhnjpdnpcd(POGOProtos.Rpc.NMDHABMPFFG value) {
      if (akhnjpdnpcdBuilder_ == null) {
        if (akhnjpdnpcd_ != null) {
          akhnjpdnpcd_ =
            POGOProtos.Rpc.NMDHABMPFFG.newBuilder(akhnjpdnpcd_).mergeFrom(value).buildPartial();
        } else {
          akhnjpdnpcd_ = value;
        }
        onChanged();
      } else {
        akhnjpdnpcdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.NMDHABMPFFG akhnjpdnpcd = 2;</code>
     */
    public Builder clearAkhnjpdnpcd() {
      if (akhnjpdnpcdBuilder_ == null) {
        akhnjpdnpcd_ = null;
        onChanged();
      } else {
        akhnjpdnpcd_ = null;
        akhnjpdnpcdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.NMDHABMPFFG akhnjpdnpcd = 2;</code>
     */
    public POGOProtos.Rpc.NMDHABMPFFG.Builder getAkhnjpdnpcdBuilder() {
      
      onChanged();
      return getAkhnjpdnpcdFieldBuilder().getBuilder();
    }
    /**
     * <code>.POGOProtos.Rpc.NMDHABMPFFG akhnjpdnpcd = 2;</code>
     */
    public POGOProtos.Rpc.NMDHABMPFFGOrBuilder getAkhnjpdnpcdOrBuilder() {
      if (akhnjpdnpcdBuilder_ != null) {
        return akhnjpdnpcdBuilder_.getMessageOrBuilder();
      } else {
        return akhnjpdnpcd_ == null ?
            POGOProtos.Rpc.NMDHABMPFFG.getDefaultInstance() : akhnjpdnpcd_;
      }
    }
    /**
     * <code>.POGOProtos.Rpc.NMDHABMPFFG akhnjpdnpcd = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.NMDHABMPFFG, POGOProtos.Rpc.NMDHABMPFFG.Builder, POGOProtos.Rpc.NMDHABMPFFGOrBuilder> 
        getAkhnjpdnpcdFieldBuilder() {
      if (akhnjpdnpcdBuilder_ == null) {
        akhnjpdnpcdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            POGOProtos.Rpc.NMDHABMPFFG, POGOProtos.Rpc.NMDHABMPFFG.Builder, POGOProtos.Rpc.NMDHABMPFFGOrBuilder>(
                getAkhnjpdnpcd(),
                getParentForChildren(),
                isClean());
        akhnjpdnpcd_ = null;
      }
      return akhnjpdnpcdBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:POGOProtos.Rpc.PEEANGPNCDN)
  }

  // @@protoc_insertion_point(class_scope:POGOProtos.Rpc.PEEANGPNCDN)
  private static final POGOProtos.Rpc.PEEANGPNCDN DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new POGOProtos.Rpc.PEEANGPNCDN();
  }

  public static POGOProtos.Rpc.PEEANGPNCDN getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PEEANGPNCDN>
      PARSER = new com.google.protobuf.AbstractParser<PEEANGPNCDN>() {
    @java.lang.Override
    public PEEANGPNCDN parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PEEANGPNCDN(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PEEANGPNCDN> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PEEANGPNCDN> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public POGOProtos.Rpc.PEEANGPNCDN getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

