// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

/**
 * Protobuf enum {@code POGOProtos.Rpc.Team}
 */
public enum Team
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TEAM_UNSET = 0;</code>
   */
  TEAM_UNSET(0),
  /**
   * <code>TEAM_BLUE = 1;</code>
   */
  TEAM_BLUE(1),
  /**
   * <code>TEAM_RED = 2;</code>
   */
  TEAM_RED(2),
  /**
   * <code>TEAM_YELLOW = 3;</code>
   */
  TEAM_YELLOW(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>TEAM_UNSET = 0;</code>
   */
  public static final int TEAM_UNSET_VALUE = 0;
  /**
   * <code>TEAM_BLUE = 1;</code>
   */
  public static final int TEAM_BLUE_VALUE = 1;
  /**
   * <code>TEAM_RED = 2;</code>
   */
  public static final int TEAM_RED_VALUE = 2;
  /**
   * <code>TEAM_YELLOW = 3;</code>
   */
  public static final int TEAM_YELLOW_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Team valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Team forNumber(int value) {
    switch (value) {
      case 0: return TEAM_UNSET;
      case 1: return TEAM_BLUE;
      case 2: return TEAM_RED;
      case 3: return TEAM_YELLOW;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Team>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Team> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Team>() {
          public Team findValueByNumber(int number) {
            return Team.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return POGOProtos.Rpc.POGOProtosRpc.getDescriptor().getEnumTypes().get(140);
  }

  private static final Team[] VALUES = values();

  public static Team valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Team(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:POGOProtos.Rpc.Team)
}

